#!/bin/bash
# Attendance System - Quick Test Commands Reference
# Run this file as a reference for all testing commands

echo "═══════════════════════════════════════════════════════"
echo "   ATTENDANCE SYSTEM - TEST COMMANDS QUICK REFERENCE"
echo "═══════════════════════════════════════════════════════"
echo ""

# ==================== INSTALLATION ====================
echo "📦 INSTALLATION COMMANDS"
echo "───────────────────────────────────────────────────────"
echo ""
echo "Backend Testing Dependencies:"
echo "  cd server && npm install --save-dev jest @types/jest ts-jest supertest @types/supertest"
echo ""
echo "Frontend Testing Dependencies:"
echo "  cd client && npm install --save-dev @testing-library/react @testing-library/jest-dom @testing-library/user-event"
echo ""
echo "E2E Testing Dependencies:"
echo "  cd client && npm install --save-dev cypress"
echo ""
echo ""

# ==================== BACKEND TESTS ====================
echo "✅ BACKEND TEST COMMANDS"
echo "───────────────────────────────────────────────────────"
echo ""
echo "Run all backend tests:"
echo "  cd server && npm test"
echo ""
echo "Run specific test file:"
echo "  cd server && npm test -- --testPathPattern=attendance.controller"
echo "  cd server && npm test -- --testPathPattern=attendance.service"
echo "  cd server && npm test -- --testPathPattern=attendance.integration"
echo ""
echo "Run tests in watch mode (auto-rerun on file changes):"
echo "  cd server && npm run test:watch"
echo ""
echo "Generate coverage report:"
echo "  cd server && npm run test:coverage"
echo ""
echo "Run tests with verbose output:"
echo "  cd server && npm test -- --verbose"
echo ""
echo ""

# ==================== FRONTEND TESTS ====================
echo "✅ FRONTEND COMPONENT TEST COMMANDS"
echo "───────────────────────────────────────────────────────"
echo ""
echo "Run all component tests:"
echo "  cd client && npm test -- --watchAll=false"
echo ""
echo "Run specific component tests:"
echo "  cd client && npm test -- AttendancePage --watchAll=false"
echo "  cd client && npm test -- MyAttendancePage --watchAll=false"
echo "  cd client && npm test -- AttendanceReportsPage --watchAll=false"
echo ""
echo "Run tests in watch mode:"
echo "  cd client && npm test"
echo ""
echo "Generate coverage report:"
echo "  cd client && npm test -- --coverage --watchAll=false"
echo ""
echo "Run with specific test name:"
echo "  cd client && npm test -- -t 'should mark attendance' --watchAll=false"
echo ""
echo ""

# ==================== E2E TESTS ====================
echo "✅ E2E TEST COMMANDS (CYPRESS)"
echo "───────────────────────────────────────────────────────"
echo ""
echo "Open Cypress interactive mode:"
echo "  cd client && npm run cypress:open"
echo ""
echo "Run all E2E tests headless:"
echo "  cd client && npm run cypress:run"
echo ""
echo "Run specific test suite:"
echo "  cd client && npx cypress run --spec 'cypress/e2e/attendance.cy.ts'"
echo ""
echo "Run E2E tests with verbose output:"
echo "  cd client && npx cypress run --verbose"
echo ""
echo "Run E2E tests in specific browser:"
echo "  cd client && npx cypress run --browser chrome"
echo "  cd client && npx cypress run --browser firefox"
echo ""
echo "Generate E2E test report:"
echo "  cd client && npx cypress run --reporter junit"
echo ""
echo ""

# ==================== ALL TESTS ====================
echo "🎯 RUN ALL TESTS COMPLETE FLOW"
echo "───────────────────────────────────────────────────────"
echo ""
echo "Run all tests sequentially:"
echo "  cd server && npm test && cd ../client && npm test -- --watchAll=false && npm run cypress:run"
echo ""
echo "Or create root package.json script and run:"
echo "  npm run test:all"
echo ""
echo ""

# ==================== COVERAGE ====================
echo "📊 CODE COVERAGE COMMANDS"
echo "───────────────────────────────────────────────────────"
echo ""
echo "Backend coverage:"
echo "  cd server && npm run test:coverage"
echo "  # View: open coverage/lcov-report/index.html"
echo ""
echo "Frontend coverage:"
echo "  cd client && npm test -- --coverage --watchAll=false"
echo "  # View: open coverage/lcov-report/index.html"
echo ""
echo "Find coverage reports:"
echo "  # Backend: server/coverage/lcov-report/index.html"
echo "  # Frontend: client/coverage/lcov-report/index.html"
echo ""
echo ""

# ==================== DEBUGGING ====================
echo "🐛 DEBUG & DEVELOPMENT COMMANDS"
echo "───────────────────────────────────────────────────────"
echo ""
echo "Run tests with debugging:"
echo "  cd server && npm test -- --detectOpenHandles"
echo ""
echo "Run failing tests only:"
echo "  cd server && npm test -- --onlyChanged"
echo ""
echo "Update snapshots (if using snapshots):"
echo "  cd server && npm test -- -u"
echo ""
echo "Run single test:"
echo "  cd server && npm test -- --testNamePattern='should mark attendance'"
echo ""
echo "Show test timings:"
echo "  cd server && npm test -- --logHeapUsage"
echo ""
echo ""

# ==================== CI/CD ====================
echo "🔧 CI/CD COMMANDS"
echo "───────────────────────────────────────────────────────"
echo ""
echo "GitHub Actions workflow (save as .github/workflows/test.yml):"
echo "  - name: Run Backend Tests"
echo "    run: cd server && npm install && npm test"
echo ""
echo "  - name: Run Frontend Tests"
echo "    run: cd client && npm install && npm test -- --watchAll=false"
echo ""
echo "  - name: Run E2E Tests"
echo "    run: cd client && npm run cypress:run"
echo ""
echo ""

# ==================== MAINTENANCE ====================
echo "🧹 MAINTENANCE COMMANDS"
echo "───────────────────────────────────────────────────────"
echo ""
echo "Clear jest cache:"
echo "  cd server && npm test -- --clearCache"
echo ""
echo "Update dependencies:"
echo "  npm update"
echo ""
echo "List outdated packages:"
echo "  npm outdated"
echo ""
echo "Update to latest version:"
echo "  npm install --save-dev jest@latest"
echo ""
echo ""

# ==================== USEFUL PATTERNS ====================
echo "📝 USEFUL TEST PATTERNS"
echo "───────────────────────────────────────────────────────"
echo ""
echo "Test specific feature:"
echo "  cd server && npm test -- attendance.controller.test.ts -t 'markAttendance'"
echo ""
echo "Test all containing 'present':"
echo "  cd server && npm test -- -t 'present'"
echo ""
echo "Test excluding certain patterns:"
echo "  cd server && npm test -- --testPathIgnorePatterns='integration'"
echo ""
echo "Test with notify on completion:"
echo "  cd server && npm test -- --notify"
echo ""
echo ""

# ==================== PERFORMANCE ====================
echo "⚡ PERFORMANCE TESTING"
echo "───────────────────────────────────────────────────────"
echo ""
echo "Measure test execution time:"
echo "  cd server && npm test -- --verbose"
echo ""
echo "Find slowest tests:"
echo "  cd server && npm test -- --testTimeout=5000"
echo ""
echo "Parallel test execution (default):"
echo "  cd server && npm test -- --maxWorkers=4"
echo ""
echo "Single worker (slower but deterministic):"
echo "  cd server && npm test -- --maxWorkers=1"
echo ""
echo ""

# ==================== SUMMARY ====================
echo "═══════════════════════════════════════════════════════"
echo "   TEST FILES CREATED"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "Backend Tests (57 tests):"
echo "  ✅ server/src/tests/attendance.controller.test.ts (15 tests)"
echo "  ✅ server/src/tests/attendance.service.test.ts (19 tests)"
echo "  ✅ server/src/tests/attendance.integration.test.ts (23 tests)"
echo ""
echo "Frontend Tests (46 tests):"
echo "  ✅ client/src/tests/AttendancePage.test.tsx (13 tests)"
echo "  ✅ client/src/tests/MyAttendancePage.test.tsx (16 tests)"
echo "  ✅ client/src/tests/AttendanceReportsPage.test.tsx (17 tests)"
echo ""
echo "E2E Tests (39 tests):"
echo "  ✅ client/cypress/e2e/attendance.cy.ts (39 tests)"
echo ""
echo "Documentation:"
echo "  📚 TESTING_GUIDE_ATTENDANCE.md"
echo "  📚 TEST_FILES_SUMMARY.md"
echo "  📚 TEST_COMMANDS.sh (this file)"
echo ""
echo "═══════════════════════════════════════════════════════"
echo "Total Test Cases: 142"
echo "Test Coverage: ~75-85%"
echo "═══════════════════════════════════════════════════════"
echo ""
