import { TopicSeed, UnitSeed } from './year1MegaCurriculum';

/**
 * The Year-2 curriculum, decomposed into the units it actually teaches. Stage key: `build`.
 *
 * ── ONE UNIT IS ONE SITTING ───────────────────────────────────────────────────────────────
 *
 * The same rule Year 1 holds: a unit is one idea, worked through once. "Object-Oriented
 * Programming" is a module; "Keeping data behind behaviour" is a unit. Nothing here is called
 * "basics" or "fundamentals" — the validator refuses a dataset that hides four lessons behind one
 * title, and it is right to.
 *
 * ── MERGED WHERE THE DRAFT SPLIT TOO FINELY ───────────────────────────────────────────────
 *
 * The draft lists Primary Keys, Foreign Keys and One-to-One / One-to-Many / Many-to-Many as three
 * subtopics. They are one lesson: you cannot teach a foreign key without the relationship it
 * expresses. Merging like this is what takes 298 subtopics to a bank a real programme can fit —
 * see the capacity test. Nothing is dropped; it is taught together.
 *
 * ── A BANK, NOT A SCHEDULE ────────────────────────────────────────────────────────────────
 *
 * No day numbers. There are more units here than any programme length can hold, which is the
 * point: the backbone reaches every student, and the rest is selected by evidence, direction and
 * the room the admin's length leaves. See year2StageMap for which topics are mandatory.
 */

/** Compact constructor, so the dataset reads as a syllabus. Mirrors year1MegaCurriculum's. */
const u = (
  slug: string, title: string, description: string,
  learningOutcomes: string[], estimatedMinutes: number,
  extra: Partial<UnitSeed> = {},
): UnitSeed => ({ slug, title, description, learningOutcomes, estimatedMinutes, ...extra });

/** The ending every teaching topic shares: find the fault, drill it, then build something with it. */
const closeOut = (what: string, after: string, debugMin = 45, practiceMin = 55, projectMin = 110): UnitSeed[] => [
  u('DEBUGGING', `Debugging ${what}`,
    `Reading what goes wrong in ${what.toLowerCase()}, and finding the cause rather than guessing.`,
    [`Diagnose a broken ${what.toLowerCase()} example without rewriting it at random`],
    debugMin, { unitType: 'DEBUG', after: [after] }),
  u('PRACTICE', `${what} Practice`,
    `Enough repetition that ${what.toLowerCase()} stops needing thought.`,
    [`Work ${what.toLowerCase()} problems without looking things up`],
    practiceMin, { unitType: 'PRACTICE', after: ['DEBUGGING'] }),
  u('MINI_PROJECT', `Mini Project — ${what}`,
    'One thing built end to end with it, and explained afterwards.',
    [`Build and describe something that uses ${what.toLowerCase()}`],
    projectMin, { unitType: 'PROJECT', after: ['PRACTICE'] }),
];

export const YEAR2: Record<string, TopicSeed> = {
  /* ── B01 · Year-2 readiness ─────────────────────────────────────────────────────────── */
  T2_BRIDGE: {
    category: 'UNIVERSAL',
    units: [
      u('PROGRAMMING_CHECK', 'Where Your Programming Actually Stands',
        'A short practical check of variables, conditions and loops — not a lesson, a measurement.',
        ['Show that the first-year programming fundamentals are in place'], 45, { unitType: 'PRACTICE' }),
      u('FUNCTIONS_AND_DATA_CHECK', 'Functions, Lists and Strings in Practice',
        'Writing small functions over lists and strings, to see what is fluent and what is not.',
        ['Solve small problems with functions over lists and strings'], 50, { unitType: 'PRACTICE', after: ['PROGRAMMING_CHECK'] }),
      u('PROBLEM_SOLVING_CHECK', 'Breaking a Problem Down, Under Time',
        'Taking an unfamiliar problem apart before writing any code.',
        ['Turn an unfamiliar problem into steps you could code'], 50, { unitType: 'PRACTICE', after: ['FUNCTIONS_AND_DATA_CHECK'] }),
      u('TOOLING_CHECK', 'Git, the Shell and Your Editor',
        'Cloning, committing, moving around a machine and running code — the tools the year assumes.',
        ['Work in Git and the shell without stopping to look things up'], 45, { unitType: 'PRACTICE', after: ['PROBLEM_SOLVING_CHECK'] }),
      u('SQL_CHECK', 'Asking a Database a Question',
        'SELECT, WHERE and ORDER BY against real tables, to confirm the ground Year 2 builds on.',
        ['Answer a question from a single table in SQL'], 45, { unitType: 'PRACTICE', after: ['TOOLING_CHECK'] }),
      u('READINESS_REVIEW', 'What You Are Ready For',
        'Reading your own results: what is proven, what needs work, and what the year will do about it.',
        ['Say which fundamentals you have shown and which you have not'], 40, { unitType: 'CHECKPOINT', after: ['SQL_CHECK'] }),
    ],
  },

  /* ── B02 · Object-oriented programming ──────────────────────────────────────────────── */
  T2_OOP_OBJECTS: {
    category: 'UNIVERSAL',
    units: [
      u('WHY_OBJECTS', 'Why Objects, and What They Replace',
        'The same program written with loose functions and with objects, and what changes.',
        ['Say what objects give you that functions and dictionaries do not'], 45),
      u('CLASSES_AND_INSTANCES', 'Classes, Instances and State',
        'A class as a description, an instance as the thing, and the state it carries.',
        ['Write a class and create instances that hold their own state'], 50, { after: ['WHY_OBJECTS'] }),
      u('CONSTRUCTORS', 'Constructors and the Life of an Object',
        'Making an object ready to use, and what happens to it afterwards.',
        ['Write a constructor that leaves an object in a valid state'], 45, { after: ['CLASSES_AND_INSTANCES'] }),
      u('METHODS', 'Behaviour That Belongs to the Data',
        'Methods, and why a function that only ever acts on one class belongs inside it.',
        ['Move behaviour onto the class whose data it uses'], 45, { after: ['CONSTRUCTORS'] }),
      u('ENCAPSULATION', 'Keeping Data Behind Behaviour',
        'Why a caller should not reach inside an object, and what to expose instead.',
        ['Expose an interface that keeps an object consistent'], 50, { after: ['METHODS'] }),
      ...closeOut('Objects', 'ENCAPSULATION'),
    ],
  },

  T2_OOP_PRINCIPLES: {
    category: 'UNIVERSAL',
    units: [
      u('INHERITANCE', 'Reusing a Class by Extending It',
        'What a subclass inherits, what it overrides, and when inheritance is the wrong tool.',
        ['Extend a class without breaking what it promised'], 50),
      u('POLYMORPHISM', 'One Call, Several Behaviours',
        'Calling the same method on different types and getting the right behaviour each time.',
        ['Write code that works across several types without checking which it has'], 50, { after: ['INHERITANCE'] }),
      u('ABSTRACTION', 'Hiding What a Caller Does Not Need',
        'Interfaces and abstract classes: naming what something does without saying how.',
        ['Design an interface that hides its implementation'], 50, { after: ['POLYMORPHISM'] }),
      u('COMPOSITION', 'Building From Parts Instead of Ancestors',
        'Composition over inheritance, and the hierarchies it saves you from.',
        ['Choose between extending a class and holding one'], 45, { after: ['ABSTRACTION'] }),
      u('MODELLING', 'Modelling a Real Problem as Objects',
        'Going from a description of a system to the classes that represent it.',
        ['Turn a written brief into a workable set of classes'], 55, { after: ['COMPOSITION'] }),
      ...closeOut('Object Design', 'MODELLING'),
    ],
  },

  /* ── B03 · Data structures, algorithms, interviews ──────────────────────────────────── */
  T2_DS_LINEAR: {
    category: 'UNIVERSAL',
    units: [
      u('DYNAMIC_ARRAYS', 'Arrays That Grow',
        'What a dynamic list costs when it grows, and why appending is usually cheap anyway.',
        ['Say what indexing, appending and inserting each cost'], 45),
      u('STRINGS', 'Strings as Data',
        'Immutability, slicing, building strings without quadratic cost.',
        ['Work on strings without accidentally copying them repeatedly'], 45, { after: ['DYNAMIC_ARRAYS'] }),
      u('STACKS', 'Stacks, and the Problems Shaped Like Them',
        'Last in, first out — undo, matching brackets, and walking back out of something.',
        ['Recognise and solve a problem that wants a stack'], 45, { after: ['STRINGS'] }),
      u('QUEUES', 'Queues, and Waiting in Order',
        'First in, first out, and where it shows up in real systems.',
        ['Recognise and solve a problem that wants a queue'], 45, { after: ['STACKS'] }),
      u('LINKED_LISTS', 'Linked Lists, and What Pointers Buy',
        'Nodes and links, what becomes cheap, and what becomes expensive.',
        ['Say when a linked list beats an array, and when it does not'], 50, { after: ['QUEUES'] }),
      ...closeOut('Linear Structures', 'LINKED_LISTS'),
    ],
  },

  T2_DS_KEYED: {
    category: 'UNIVERSAL',
    units: [
      u('HASH_MAPS', 'Looking Something Up Without Searching',
        'Dictionaries and hash maps: how a key becomes a place, and what that costs.',
        ['Use a map to turn a search into a lookup'], 50),
      u('SETS', 'Sets, and Questions About Membership',
        'Uniqueness, intersection and difference, and the loops they replace.',
        ['Answer membership and overlap questions with sets'], 45, { after: ['HASH_MAPS'] }),
      u('TREES', 'Trees, and Data With a Shape',
        'Parents and children, depth, and the problems that are naturally hierarchical.',
        ['Walk a tree, and say what its depth costs you'], 50, { after: ['SETS'] }),
      u('BINARY_SEARCH_TREES', 'Keeping a Tree in Order',
        'Ordered trees, why lookup gets fast, and what happens when one goes lopsided.',
        ['Explain why a balanced tree searches quickly and an unbalanced one does not'], 50, { after: ['TREES'] }),
      u('CHOOSING', 'Choosing the Structure a Problem Wants',
        'Reading a problem and naming the structure before writing any code.',
        ['Pick a structure from a problem statement and justify it'], 50, { after: ['BINARY_SEARCH_TREES'] }),
      ...closeOut('Maps and Trees', 'CHOOSING'),
    ],
  },

  T2_ALGORITHMS: {
    category: 'UNIVERSAL',
    units: [
      u('ALGORITHMIC_THINKING', 'Thinking in Steps a Machine Can Follow',
        'Turning an intention into a procedure, and checking it on paper before coding it.',
        ['Write a procedure that provably terminates with the right answer'], 45),
      u('LINEAR_SEARCH', 'Searching Without Order',
        'Looking through everything, and what that costs as the data grows.',
        ['Say what a linear search costs, and when it is the right answer'], 40, { after: ['ALGORITHMIC_THINKING'] }),
      u('BINARY_SEARCH', 'Searching What Is Already Sorted',
        'Halving the problem, and the off-by-one mistakes that make it wrong.',
        ['Write a correct binary search and say why it is faster'], 50, { after: ['LINEAR_SEARCH'] }),
      u('SIMPLE_SORTS', 'Sorting the Obvious Ways',
        'Bubble, selection and insertion sort — taught so the cost of a bad sort is felt, not memorised.',
        ['Trace a simple sort and say what it costs'], 50, { after: ['BINARY_SEARCH'] }),
      u('DIVIDE_AND_CONQUER', 'Splitting a Problem in Half',
        'Merge sort and the pattern behind it: solve the halves, combine the answers.',
        ['Explain why merge sort beats the simple sorts'], 55, { after: ['SIMPLE_SORTS'] }),
      u('RECURSION', 'Solving a Problem With Itself',
        'Base case, recursive case, and what the call stack is doing while you wait.',
        ['Write a recursive solution with a base case that is actually reached'], 55, { after: ['DIVIDE_AND_CONQUER'] }),
      u('BIG_O', 'Saying What Code Costs',
        'Big-O as a sentence about growth, not an exam answer.',
        ['State the time and space cost of code you wrote'], 50, { after: ['RECURSION'] }),
      ...closeOut('Algorithms', 'BIG_O'),
    ],
  },

  T2_DSA_INTERVIEW: {
    category: 'UNIVERSAL',
    units: [
      u('READING_A_PROBLEM', 'Reading the Question Properly',
        'Constraints, examples and the edge cases hidden in the wording.',
        ['Restate a problem, with its constraints and edge cases, before coding'], 45),
      u('BRUTE_FORCE_FIRST', 'Get It Working, Then Get It Fast',
        'Why the obvious solution first is the right move, in an interview and out of one.',
        ['Produce a correct slow solution and state its cost'], 45, { after: ['READING_A_PROBLEM'] }),
      u('OPTIMISING', 'Making It Faster on Purpose',
        'Finding the repeated work, and the structure that removes it.',
        ['Improve a solution and explain exactly what you removed'], 50, { after: ['BRUTE_FORCE_FIRST'] }),
      u('ARRAY_PATTERNS', 'Array and String Patterns',
        'Two pointers, sliding windows, prefix sums — the shapes that keep coming back.',
        ['Recognise and apply the common array patterns'], 55, { after: ['OPTIMISING'] }),
      u('MAP_PATTERNS', 'Counting, Grouping and Seen-Before',
        'Hash-map patterns: frequencies, grouping, and detecting what you have seen.',
        ['Solve counting and grouping problems with a map'], 50, { after: ['ARRAY_PATTERNS'] }),
      u('STACK_QUEUE_PATTERNS', 'Stack and Queue Patterns',
        'Matching, nearest-greater, and breadth-first walks.',
        ['Solve problems that want a stack or a queue'], 50, { after: ['MAP_PATTERNS'] }),
      u('RECURSION_PATTERNS', 'Recursion and Tree Problems',
        'Walking trees, and recursive problems small enough to be asked in an hour.',
        ['Solve a basic tree problem recursively'], 55, { after: ['STACK_QUEUE_PATTERNS'] }),
      u('EXPLAINING', 'Thinking Out Loud',
        'Narrating your approach so an interviewer can follow it — and hear you correct yourself.',
        ['Explain a solution and its cost while writing it'], 45, { after: ['RECURSION_PATTERNS'] }),
      u('TIMED_PRACTICE', 'Working Against the Clock',
        'Timed sets, so the pressure of an interview is not the new thing on the day.',
        ['Solve unfamiliar problems inside a time limit'], 60, { unitType: 'PRACTICE', after: ['EXPLAINING'] }),
      u('MOCK_ROUND', 'A Full Coding Round',
        'One round, end to end: read, plan, code, test, explain.',
        ['Complete a coding round and review your own performance'], 60, { unitType: 'CHECKPOINT', after: ['TIMED_PRACTICE'] }),
    ],
  },

  /* ── B04 · Intermediate programming ─────────────────────────────────────────────────── */
  T2_PY_STRUCTURE: {
    category: 'ENRICHMENT',
    units: [
      u('MODULES', 'Splitting a Program Across Files',
        'Modules, what belongs in each, and importing without circular pain.',
        ['Split a program into modules that import cleanly'], 50),
      u('PACKAGES', 'Packages and Project Layout',
        'Folders that are packages, entry points, and where tests live.',
        ['Lay out a project somebody else could navigate'], 45, { after: ['MODULES'] }),
      u('SCOPE', 'Names, Scope and Shadowing',
        'Where a name lives, what shadows what, and why a global is usually a mistake.',
        ['Predict which value a name has at any point'], 45, { after: ['PACKAGES'] }),
      u('VIRTUAL_ENVIRONMENTS', 'A Project With Its Own Dependencies',
        'Virtual environments, pip, and a requirements file that actually reproduces.',
        ['Set up an environment another person can recreate'], 45, { after: ['SCOPE'] }),
      u('TYPE_HINTS', 'Saying What a Function Expects',
        'Type hints as documentation the editor can check.',
        ['Annotate functions so mistakes are caught before running'], 40, { after: ['VIRTUAL_ENVIRONMENTS'] }),
      ...closeOut('Project Structure', 'TYPE_HINTS', 40, 50, 100),
    ],
  },

  T2_PY_ROBUST: {
    category: 'ENRICHMENT',
    units: [
      u('EXCEPTIONS', 'When Something Goes Wrong',
        'Raising, catching what you can handle, and why a bare except hides bugs.',
        ['Handle the failures you can and let the rest surface'], 50),
      u('FILES', 'Reading and Writing Real Files',
        'Opening, closing, encodings, and the file that does not exist.',
        ['Read and write files without losing data or leaking handles'], 50, { after: ['EXCEPTIONS'] }),
      u('JSON', 'Structured Data In and Out',
        'JSON to objects and back, and validating what arrived.',
        ['Load, check and save structured data'], 45, { after: ['FILES'] }),
      u('COMPREHENSIONS', 'Building Lists Without Loops',
        'Comprehensions where they read better, and loops where they do not.',
        ['Rewrite loops as comprehensions where it helps'], 45, { after: ['JSON'] }),
      u('ITERATORS', 'Walking Through Data Lazily',
        'Iterators and generators, and processing more data than fits in memory.',
        ['Process a large file without loading all of it'], 50, { after: ['COMPREHENSIONS'] }),
      ...closeOut('Robust Programs', 'ITERATORS', 45, 55, 100),
    ],
  },

  T2_CLEAN_CODE: {
    category: 'ENRICHMENT',
    units: [
      u('NAMING', 'Names That Save a Comment',
        'What a name has to carry, and why most comments are an apology for one.',
        ['Rename code so it explains itself'], 45),
      u('SMALL_FUNCTIONS', 'One Function, One Job',
        'Separation of concerns at the smallest scale, and the tests it makes possible.',
        ['Break a long function into ones you can name'], 50, { after: ['NAMING'] }),
      u('DRY', 'Repetition Worth Removing, and Repetition Worth Keeping',
        'DRY, and the wrong abstraction that costs more than the duplication did.',
        ['Judge whether two similar pieces of code should become one'], 45, { after: ['SMALL_FUNCTIONS'] }),
      u('ERROR_HANDLING', 'Failing Usefully',
        'Error messages that say what to do, and logs somebody can search.',
        ['Make a failure legible to whoever reads it next'], 50, { after: ['DRY'] }),
      u('DOCUMENTATION', 'Writing the Bit That Is Not Obvious',
        'READMEs and docstrings: what the code cannot say for itself.',
        ['Document a project so somebody can run and change it'], 45, { after: ['ERROR_HANDLING'] }),
      u('LAYERS', 'Where Each Piece of a System Goes',
        'Interface, logic, data and services — and what belongs in which.',
        ['Place a feature into the right layer of an application'], 50, { after: ['DOCUMENTATION'] }),
      u('CODE_REVIEW', 'Reviewing, and Being Reviewed',
        'Reading a change properly, saying what matters, and taking a review well.',
        ['Review a change with comments somebody can act on'], 50, { after: ['LAYERS'] }),
      u('REFACTORING', 'Changing Code Without Changing Behaviour',
        'Small safe steps, and the technical debt you decide to keep.',
        ['Refactor working code and prove it still works'], 55, { unitType: 'PRACTICE', after: ['CODE_REVIEW'] }),
      u('MINI_PROJECT', 'Mini Project — Rescue a Messy Program',
        'A working but unpleasant program, made maintainable without breaking it.',
        ['Improve a real codebase and defend each change'], 110, { unitType: 'PROJECT', after: ['REFACTORING'] }),
    ],
  },

  /* ── B05 · Testing and debugging ────────────────────────────────────────────────────── */
  T2_DEBUGGING: {
    category: 'UNIVERSAL',
    units: [
      u('READING_ERRORS', 'Reading the Error Properly',
        'Stack traces, the line that matters, and the habit of reading the last line first.',
        ['Find the cause of a crash from its trace alone'], 45),
      u('REPRODUCING', 'Making a Bug Happen on Demand',
        'The smallest input that fails, and why that is most of the fix.',
        ['Reduce a failure to a reproducible case'], 50, { after: ['READING_ERRORS'] }),
      u('BREAKPOINTS', 'Stopping the Program to Look',
        'A debugger, stepping, and watching a value change.',
        ['Use a debugger instead of adding print statements everywhere'], 50, { after: ['REPRODUCING'] }),
      u('HYPOTHESIS', 'One Change at a Time',
        'Forming a hypothesis, testing exactly it, and not fixing three things at once.',
        ['Find a fault by elimination rather than by guessing'], 45, { after: ['BREAKPOINTS'] }),
      u('BROKEN_PROGRAMS', 'Repairing Somebody Else\'s Program',
        'Real broken programs, diagnosed and fixed — the work of most engineering days.',
        ['Diagnose and repair code you did not write'], 60, { unitType: 'PRACTICE', after: ['HYPOTHESIS'] }),
      u('MINI_PROJECT', 'Mini Project — The Bug Report',
        'A fault found, explained in writing, fixed, and proven fixed.',
        ['Write a bug report and a fix somebody could review'], 100, { unitType: 'PROJECT', after: ['BROKEN_PROGRAMS'] }),
    ],
  },

  T2_TESTING: {
    category: 'UNIVERSAL',
    units: [
      u('WHY_TESTS', 'What a Test Is Actually For',
        'Catching the mistake you will make next month, not proving today\'s code works.',
        ['Say what a test protects and what it cannot'], 45),
      u('FIRST_TEST', 'Writing Your First Real Test',
        'A test file, an assertion, and running the suite.',
        ['Write and run a test for a function you wrote'], 50, { after: ['WHY_TESTS'] }),
      u('ASSERTIONS', 'Asserting the Right Thing',
        'Testing behaviour rather than implementation, so a refactor does not break every test.',
        ['Write assertions that survive a rewrite of the code beneath'], 50, { after: ['FIRST_TEST'] }),
      u('EDGE_CASES', 'The Cases That Actually Break Software',
        'Empty, one, many, huge, negative, missing, and the wrong type.',
        ['Enumerate the boundary cases of a function before testing it'], 50, { after: ['ASSERTIONS'] }),
      u('NEGATIVE_TESTS', 'Testing What Should Fail',
        'Proving bad input is rejected, which is where most bugs live.',
        ['Test failure paths as deliberately as success paths'], 45, { after: ['EDGE_CASES'] }),
      u('TEST_FIRST', 'Writing the Test Before the Code',
        'Test-driven thinking as a design tool rather than a ritual.',
        ['Drive a small feature from its test'], 50, { after: ['NEGATIVE_TESTS'] }),
      ...closeOut('Testing', 'TEST_FIRST', 45, 55, 100),
    ],
  },

  /* ── B06 · Working with others ──────────────────────────────────────────────────────── */
  T2_GIT_TEAM: {
    category: 'UNIVERSAL',
    units: [
      u('BRANCHING', 'Working on a Branch',
        'Why a branch exists, and what it protects on the main line.',
        ['Work on a feature branch and keep main clean'], 45),
      u('MERGING', 'Bringing Work Back Together',
        'Merges, fast-forwards, and reading the history afterwards.',
        ['Merge a branch and explain the history it produced'], 45, { after: ['BRANCHING'] }),
      u('CONFLICTS', 'When Two People Changed the Same Line',
        'Resolving a conflict by understanding both sides, not by picking one.',
        ['Resolve a merge conflict without losing anybody\'s work'], 50, { after: ['MERGING'] }),
      u('PULL_REQUESTS', 'Proposing a Change',
        'A pull request that explains itself, and a description a reviewer can use.',
        ['Open a pull request somebody can review quickly'], 45, { after: ['CONFLICTS'] }),
      u('REVIEWING', 'Reviewing Somebody Else\'s Change',
        'What to look for, what to let go, and how to say it.',
        ['Leave review comments that are specific and kind'], 50, { after: ['PULL_REQUESTS'] }),
      u('COMMIT_QUALITY', 'Commits and Messages Worth Reading',
        'One change per commit, and a message that explains why.',
        ['Write a history somebody can follow six months later'], 45, { after: ['REVIEWING'] }),
      u('REPO_HYGIENE', 'What Belongs in a Repository',
        'Structure, .gitignore, and the secret that must never be committed.',
        ['Set up a repository that keeps junk and secrets out'], 45, { after: ['COMMIT_QUALITY'] }),
      u('WORKFLOW', 'How a Team Actually Works',
        'Feature-branch workflow, main that always works, and releasing from it.',
        ['Follow a team workflow through a full change'], 50, { after: ['REPO_HYGIENE'] }),
      u('MINI_PROJECT', 'Mini Project — A Change Through the Whole Workflow',
        'Branch, commit, pull request, review, conflict, merge — on a shared repository.',
        ['Complete a change through a full team workflow'], 100, { unitType: 'PROJECT', after: ['WORKFLOW'] }),
    ],
  },

  T2_LINUX: {
    category: 'ENRICHMENT',
    units: [
      u('FILESYSTEM', 'Finding Your Way Around a Server',
        'The filesystem layout, and where things actually live on a Linux machine.',
        ['Navigate and inspect an unfamiliar Linux machine'], 45),
      u('PERMISSIONS', 'Who May Read, Write and Run',
        'Users, groups and modes — and the permission that broke your deployment.',
        ['Set permissions that allow the work and nothing more'], 50, { after: ['FILESYSTEM'] }),
      u('PROCESSES', 'What Is Running, and What It Is Doing',
        'Processes, ports, memory and the one eating the CPU.',
        ['Find and stop the process causing a problem'], 50, { after: ['PERMISSIONS'] }),
      u('PIPES', 'Joining Commands Together',
        'Pipes and redirection, turning small tools into an answer.',
        ['Answer a question by composing shell commands'], 50, { after: ['PROCESSES'] }),
      u('SEARCHING', 'Finding Files and Text at Speed',
        'find, grep and the searches that save an afternoon.',
        ['Search a codebase or a log from the command line'], 45, { after: ['PIPES'] }),
      u('ENV_VARS', 'Configuration Without Editing Code',
        'Environment variables, .env files, and keeping secrets out of the repository.',
        ['Configure an application without changing its code'], 45, { after: ['SEARCHING'] }),
      u('SHELL_SCRIPTS', 'Automating What You Keep Retyping',
        'A script with arguments, checks and an exit code that means something.',
        ['Write a script that automates a repeated task safely'], 55, { after: ['ENV_VARS'] }),
      ...closeOut('the Command Line', 'SHELL_SCRIPTS', 45, 55, 100),
    ],
  },

  /* ── B07 · Databases ────────────────────────────────────────────────────────────────── */
  T2_DB_QUERY: {
    category: 'UNIVERSAL',
    units: [
      u('FILTERING', 'Asking For Exactly the Rows You Want',
        'WHERE in earnest: several conditions, ranges, nulls and the ones people get wrong.',
        ['Write a filter that returns exactly the rows you meant'], 50),
      u('SORTING_PAGING', 'Ordering and Paging Results',
        'ORDER BY, LIMIT and OFFSET, and paging that does not repeat or skip rows.',
        ['Return a page of ordered results correctly'], 45, { after: ['FILTERING'] }),
      u('AGGREGATES', 'Counting, Summing and Averaging',
        'Aggregate functions, and what NULL does to each of them.',
        ['Produce correct totals and averages from a table'], 50, { after: ['SORTING_PAGING'] }),
      u('GROUP_BY', 'Answering Questions Per Group',
        'GROUP BY and HAVING, and the difference between filtering rows and filtering groups.',
        ['Answer a per-group question with the right filter in the right place'], 55, { after: ['AGGREGATES'] }),
      u('JOINS', 'Questions That Span Tables',
        'Inner and outer joins, what each keeps, and the accidental cross join.',
        ['Join tables and explain which rows survive'], 55, { after: ['GROUP_BY'] }),
      u('SUBQUERIES', 'A Query Inside a Query',
        'Subqueries and common table expressions, for questions that need two steps.',
        ['Answer a two-step question in one query, readably'], 55, { after: ['JOINS'] }),
      u('APP_CRUD', 'Talking to a Database From Code',
        'Create, read, update and delete from an application — with parameters, never string building.',
        ['Run safe queries from code, with parameters'], 55, { after: ['SUBQUERIES'] }),
      ...closeOut('SQL', 'APP_CRUD', 50, 60, 110),
    ],
  },

  T2_DB_DESIGN: {
    category: 'UNIVERSAL',
    units: [
      u('ENTITIES', 'Finding the Things a System Is About',
        'Turning a description into entities and the facts each one holds.',
        ['Identify the entities and attributes behind a brief'], 50),
      u('KEYS_AND_RELATIONSHIPS', 'Keys, and How Tables Point at Each Other',
        'Primary keys, foreign keys, and one-to-one, one-to-many and many-to-many in practice.',
        ['Model relationships with keys that hold them together'], 55, { after: ['ENTITIES'] }),
      u('NORMALISATION', 'Storing a Fact in Exactly One Place',
        'Normal forms as a practical rule, and the redundancy that corrupts data.',
        ['Normalise a table and say what problem it prevented'], 55, { after: ['KEYS_AND_RELATIONSHIPS'] }),
      u('CONSTRAINTS', 'Rules the Database Enforces Itself',
        'NOT NULL, UNIQUE, CHECK and foreign keys as the last line of defence.',
        ['Protect data with constraints, not only with application code'], 50, { after: ['NORMALISATION'] }),
      u('INDEXES', 'Making a Query Fast',
        'What an index is, when it helps, and what it costs on every write.',
        ['Add an index for a slow query and justify it'], 50, { after: ['CONSTRAINTS'] }),
      u('TRANSACTIONS', 'All of It, or None of It',
        'Transactions, atomicity, and the half-finished transfer.',
        ['Use a transaction where partial success would be wrong'], 50, { after: ['INDEXES'] }),
      ...closeOut('Database Design', 'TRANSACTIONS', 50, 55, 110),
    ],
  },

  /* ── B08 · Web and APIs ─────────────────────────────────────────────────────────────── */
  T2_WEB_HTTP: {
    category: 'UNIVERSAL',
    units: [
      u('INTERNET', 'What Happens When You Open a Site',
        'From a name to a machine to a response, in order.',
        ['Trace a page load from the address bar to the screen'], 50),
      u('DNS_URLS', 'Names, Addresses and What a URL Contains',
        'DNS, and every part of a URL and what it decides.',
        ['Read a URL and say what each part does'], 45, { after: ['INTERNET'] }),
      u('REQUEST_RESPONSE', 'The Shape of a Request and a Response',
        'Method, path, headers, body — on the way out and on the way back.',
        ['Read a raw request and response'], 50, { after: ['DNS_URLS'] }),
      u('METHODS', 'Verbs That Mean Something',
        'GET, POST, PUT, PATCH and DELETE, and why the difference matters.',
        ['Choose the method that matches what a request does'], 45, { after: ['REQUEST_RESPONSE'] }),
      u('STATUS_CODES', 'Answers Programs Can Act On',
        'The families, the ones you will use, and why 200-with-an-error is a lie.',
        ['Pick the status code that describes what happened'], 45, { after: ['METHODS'] }),
      u('HEADERS_HTTPS', 'Headers, Cookies and What HTTPS Protects',
        'The metadata around a request, and what encryption does and does not hide.',
        ['Say what a header carries and what HTTPS protects'], 50, { after: ['STATUS_CODES'] }),
      ...closeOut('HTTP', 'HEADERS_HTTPS', 45, 50, 100),
    ],
  },

  T2_APIS: {
    category: 'UNIVERSAL',
    units: [
      u('JSON_CONTRACTS', 'JSON as an Agreement',
        'The shape a caller depends on, and what breaking it costs them.',
        ['Design a response shape that will not surprise a caller'], 45),
      u('REST', 'Resources, and the Shape of a Good API',
        'REST as a set of habits: resources, verbs, plural paths, predictable responses.',
        ['Lay out endpoints that another engineer can guess'], 50, { after: ['JSON_CONTRACTS'] }),
      u('CONSUMING', 'Calling Somebody Else\'s API',
        'Reading documentation, making the call, and handling what comes back.',
        ['Use a third-party API and handle its failures'], 55, { after: ['REST'] }),
      u('AUTH', 'Proving Who Is Calling',
        'API keys, tokens and sessions — the concepts, and where each belongs.',
        ['Say how an API knows who is calling, and what to protect'], 50, { after: ['CONSUMING'] }),
      u('ERRORS_AND_LIMITS', 'Errors, Retries and Rate Limits',
        'Reading an API\'s failures, backing off, and not hammering a service.',
        ['Handle an API failure without making it worse'], 50, { after: ['AUTH'] }),
      ...closeOut('APIs', 'ERRORS_AND_LIMITS', 45, 55, 110),
    ],
  },

  /* ── B09 · Security ─────────────────────────────────────────────────────────────────── */
  T2_SECURITY: {
    category: 'UNIVERSAL',
    units: [
      u('THREAT_THINKING', 'Thinking About Who Would Attack This',
        'Assets, threats and the easiest way in — the question before any defence.',
        ['Name what a system protects and how it would most likely be attacked'], 45),
      u('AUTHN_AUTHZ', 'Who You Are, and What You May Do',
        'Authentication against authorisation, and the bugs that come from confusing them.',
        ['Separate identity from permission in a design'], 50, { after: ['THREAT_THINKING'] }),
      u('PASSWORDS', 'Storing Passwords Without Storing Passwords',
        'Salted, slow hashes, and why encryption is the wrong tool here.',
        ['Store credentials so a stolen database is not a disaster'], 50, { after: ['AUTHN_AUTHZ'] }),
      u('INPUT_VALIDATION', 'Never Trusting What Arrives',
        'Validating on the server, and why the client\'s checks are a courtesy.',
        ['Validate input where it cannot be bypassed'], 50, { after: ['PASSWORDS'] }),
      u('INJECTION', 'When Data Becomes Code',
        'SQL injection and cross-site scripting: one mistake, two places.',
        ['Explain an injection flaw and fix it at the root'], 55, { after: ['INPUT_VALIDATION'] }),
      u('SECRETS', 'Keys, Config and What Must Never Be Committed',
        'Environment variables, secret rotation, and Git history that never forgets.',
        ['Keep secrets out of a repository, and handle one that leaked'], 45, { after: ['INJECTION'] }),
      u('DEPENDENCIES', 'The Code You Did Not Write',
        'Known vulnerabilities, dependency checks, and why patching is most of security.',
        ['Check a project\'s dependencies and act on what you find'], 45, { after: ['SECRETS'] }),
      ...closeOut('Secure Coding', 'DEPENDENCIES', 50, 55, 110),
    ],
  },

  /* ── B10 · Building with AI ─────────────────────────────────────────────────────────── */
  T2_AI_ASSISTED: {
    category: 'ENRICHMENT',
    units: [
      u('ASSISTANTS', 'What an Assistant Is Good and Bad At',
        'Where AI genuinely saves time, and where it costs more than it gives.',
        ['Judge whether a task is worth handing to an assistant'], 45),
      u('PROMPTING', 'Asking a Technical Question Well',
        'Context, constraints and examples — the difference between a useful answer and a plausible one.',
        ['Get a usable answer by stating the problem properly'], 50, { after: ['ASSISTANTS'] }),
      u('EXPLAIN_CODE', 'Understanding Code With Help',
        'Using an assistant to read unfamiliar code, and verifying what it tells you.',
        ['Understand an unfamiliar codebase faster, and check the explanation'], 45, { after: ['PROMPTING'] }),
      u('REVIEWING_AI_CODE', 'Reviewing What It Wrote',
        'Reading generated code as a reviewer, not a recipient.',
        ['Find the mistakes in generated code before running it'], 55, { after: ['EXPLAIN_CODE'] }),
      u('HALLUCINATIONS', 'Confident and Wrong',
        'Invented functions, plausible nonsense, and how to catch both quickly.',
        ['Spot and verify a claim an assistant invented'], 50, { after: ['REVIEWING_AI_CODE'] }),
      u('AI_SECURITY', 'What Not to Paste Into a Chat',
        'Secrets, customer data and licensing — the lines that get people fired.',
        ['Say what may and may not be shared with an assistant'], 45, { after: ['HALLUCINATIONS'] }),
      u('KEEPING_FUNDAMENTALS', 'Going Faster Without Getting Weaker',
        'Using AI in a way that leaves you more capable, not less.',
        ['Work with an assistant while still understanding your own code'], 45, { after: ['AI_SECURITY'] }),
      ...closeOut('AI-Assisted Work', 'KEEPING_FUNDAMENTALS', 45, 55, 100),
    ],
  },

  /* ── B11 · Direction ────────────────────────────────────────────────────────────────── */
  T2_DIRECTION: {
    category: 'EXPLORATION',
    units: [
      u('WHAT_CHANGED', 'What Your First Year Told You',
        'Reading your own evidence: what came easily, what did not, and what you enjoyed.',
        ['Describe your strengths from evidence rather than impression'], 45),
      u('ROLES_IN_DEPTH', 'What Each Role Does on a Tuesday',
        'The seven directions as actual working days, not job titles.',
        ['Say what a week looks like in each direction'], 50, { after: ['WHAT_CHANGED'] }),
      u('MARKET', 'What Is Being Hired For, and Where',
        'Openings, entry requirements and what an internship in each direction asks for.',
        ['Compare directions by what they demand of a second year'], 45, { after: ['ROLES_IN_DEPTH'] }),
      u('COMPARING', 'Comparing Two Directions Honestly',
        'Weighing interest against evidence against opportunity.',
        ['Compare your two strongest options on the same terms'], 45, { after: ['MARKET'] }),
      u('CHOOSING', 'Choosing, and What It Commits You To',
        'Making the choice, and knowing what it does and does not close off.',
        ['Choose a direction and state what it means for your year'], 45, { unitType: 'CHECKPOINT', after: ['COMPARING'] }),
    ],
  },

  T2_TRACK_BACKEND: {
    category: 'DIRECTION',
    units: [
      u('ARCHITECTURE', 'How a Backend Is Put Together',
        'Routes, handlers, services and data access — and what belongs in each.',
        ['Place a feature into the right layer of a backend'], 50),
      u('ROUTING', 'Routing in Earnest',
        'Resources, parameters, versions and a path structure that scales.',
        ['Lay out routes for a real application'], 50, { after: ['ARCHITECTURE'] }),
      u('VALIDATION', 'Refusing Bad Requests Properly',
        'Validating every field, and answering with an error a client can act on.',
        ['Reject invalid input with a useful response'], 50, { after: ['ROUTING'] }),
      u('PERSISTENCE', 'Storing Data From an Application',
        'Connecting to a database, queries with parameters, and migrations.',
        ['Read and write application data safely'], 55, { after: ['VALIDATION'] }),
      u('CRUD_API', 'A Complete CRUD API',
        'The five endpoints, done properly, with the status codes each deserves.',
        ['Build a full CRUD resource with correct responses'], 55, { after: ['PERSISTENCE'] }),
      u('AUTHENTICATION', 'Logging a User In',
        'Sessions and tokens, password storage, and staying logged in.',
        ['Implement login and protect a route with it'], 55, { after: ['CRUD_API'] }),
      u('AUTHORISATION', 'Who May Do What',
        'Roles, ownership and the check that must not live in the client.',
        ['Enforce ownership and role rules on the server'], 50, { after: ['AUTHENTICATION'] }),
      u('API_TESTING', 'Testing an API',
        'Testing endpoints, including every failure path.',
        ['Test an endpoint\'s success and failure behaviour'], 50, { after: ['AUTHORISATION'] }),
      u('LOGGING', 'Knowing What Your Server Did',
        'Logs that answer questions at 2am, without leaking secrets.',
        ['Log enough to diagnose a problem, and nothing dangerous'], 45, { after: ['API_TESTING'] }),
      u('DOCUMENTATION', 'Documenting an API',
        'The table another engineer needs, and keeping it true.',
        ['Document an API somebody can use without asking you'], 45, { after: ['LOGGING'] }),
      ...closeOut('Backend Work', 'DOCUMENTATION', 50, 60, 120),
    ],
  },

  T2_TRACK_FRONTEND: {
    category: 'DIRECTION',
    units: [
      u('SEMANTIC_STRUCTURE', 'Markup That Means Something',
        'Semantic HTML as the foundation of accessibility and of every framework above it.',
        ['Structure a page so its meaning survives without styling'], 45),
      u('LAYOUT', 'Layout That Survives Real Content',
        'Flexbox, grid and responsive rules, against long text and small screens.',
        ['Build a layout that holds at any width'], 50, { after: ['SEMANTIC_STRUCTURE'] }),
      u('JS_IN_THE_PAGE', 'JavaScript That Changes a Page',
        'Selecting, updating and reacting — the DOM as the thing you actually manipulate.',
        ['Make a page respond to what a user does'], 50, { after: ['LAYOUT'] }),
      u('EVENTS', 'Events, and What Happens in What Order',
        'Listeners, bubbling, and the click that fired twice.',
        ['Handle events without surprises'], 50, { after: ['JS_IN_THE_PAGE'] }),
      u('ARRAYS_OBJECTS', 'Working With Data in JavaScript',
        'map, filter and reduce over the data a page displays.',
        ['Transform data for display without loops that lose you'], 50, { after: ['EVENTS'] }),
      u('ASYNC', 'Code That Waits',
        'Promises, async and await, and the loading state that must exist.',
        ['Write asynchronous code that handles slowness honestly'], 55, { after: ['ARRAYS_OBJECTS'] }),
      u('FETCHING', 'Showing Data From a Server',
        'fetch, JSON, and the four states every screen has.',
        ['Display fetched data with loading, empty and error states'], 55, { after: ['ASYNC'] }),
      u('STATE', 'What the Screen Remembers',
        'State, where it lives, and why two copies drift apart.',
        ['Keep one source of truth for what a page shows'], 50, { after: ['FETCHING'] }),
      u('COMPONENTS', 'Thinking in Components',
        'Splitting an interface into pieces with their own data and behaviour.',
        ['Break an interface into components that compose'], 50, { after: ['STATE'] }),
      u('ACCESSIBILITY', 'Interfaces Everyone Can Use',
        'Keyboard, labels, contrast and focus — checked, not assumed.',
        ['Make an interface usable without a mouse'], 45, { after: ['COMPONENTS'] }),
      ...closeOut('Frontend Work', 'ACCESSIBILITY', 50, 60, 120),
    ],
  },

  T2_TRACK_DATA: {
    category: 'DIRECTION',
    units: [
      u('DATA_LITERACY', 'What One Row Means',
        'Grain, columns and types — the question that decides every later number.',
        ['State what a row represents before analysing anything'], 45),
      u('COLLECTION', 'Where Data Comes From',
        'Files, databases, APIs and surveys, and the bias each brings.',
        ['Judge what a dataset can and cannot answer'], 45, { after: ['DATA_LITERACY'] }),
      u('LOADING', 'Loading and Looking First',
        'Reading a dataset and running the checks before touching it.',
        ['Describe a dataset\'s shape, types and gaps on sight'], 50, { after: ['COLLECTION'] }),
      u('CLEANING', 'Cleaning, With a Record of What You Did',
        'Missing values, duplicates, wrong types, and the log that makes it defensible.',
        ['Clean a dataset and justify every change'], 55, { after: ['LOADING'] }),
      u('EXPLORATION', 'Finding What Is Actually There',
        'Distributions, outliers and the questions the data suggests.',
        ['Explore a dataset and report what stands out'], 50, { after: ['CLEANING'] }),
      u('DESCRIPTIVE_STATS', 'Describing Data Without Misleading',
        'Mean, median, spread, and which to use when.',
        ['Summarise data with the statistic that fits it'], 50, { after: ['EXPLORATION'] }),
      u('SQL_FOR_ANALYSIS', 'Answering Analysis Questions in SQL',
        'Aggregations and joins aimed at a question rather than an application.',
        ['Answer an analytical question directly in SQL'], 55, { after: ['DESCRIPTIVE_STATS'] }),
      u('VISUALISATION', 'Charts That Answer the Question',
        'Choosing the chart from the question, and the scales that mislead.',
        ['Draw an honest chart that answers a stated question'], 50, { after: ['SQL_FOR_ANALYSIS'] }),
      u('DATA_QUALITY', 'Trusting a Number Before Reporting It',
        'Plausibility checks, reconciliation and knowing when not to answer.',
        ['Check a result before anybody acts on it'], 45, { after: ['VISUALISATION'] }),
      ...closeOut('Data Analysis', 'DATA_QUALITY', 50, 60, 120),
    ],
  },

  T2_TRACK_AI: {
    category: 'DIRECTION',
    units: [
      u('WHAT_ML_IS', 'Learning From Data Instead of Rules',
        'What machine learning is, and the problems it is the wrong answer to.',
        ['Say whether a problem needs machine learning at all'], 45),
      u('PROBLEM_TYPES', 'Classification, Regression and the Rest',
        'The shapes a problem comes in, and what each needs.',
        ['Classify a problem and name what it would predict'], 45, { after: ['WHAT_ML_IS'] }),
      u('FEATURES_LABELS', 'Features, Labels and What They Cost to Get',
        'What a model is given and what it is asked for — and where labels come from.',
        ['Define features and labels for a real problem'], 50, { after: ['PROBLEM_TYPES'] }),
      u('DATA_PREPARATION', 'Preparing Data a Model Can Use',
        'Cleaning, encoding and scaling, and the leakage that flatters a model.',
        ['Prepare a dataset without leaking the answer into it'], 55, { after: ['FEATURES_LABELS'] }),
      u('TRAIN_TEST', 'Training, Validation and Honest Testing',
        'Splitting data properly, and why the test set is sacred.',
        ['Split data so the result means something'], 50, { after: ['DATA_PREPARATION'] }),
      u('REGRESSION', 'Predicting a Number',
        'A first regression model, fitted and read.',
        ['Train and interpret a simple regression'], 55, { after: ['TRAIN_TEST'] }),
      u('CLASSIFICATION', 'Predicting a Category',
        'A first classifier, and what its confidence means.',
        ['Train and interpret a simple classifier'], 55, { after: ['REGRESSION'] }),
      u('EVALUATION', 'Judging a Model Properly',
        'Accuracy and why it lies, precision, recall, and the confusion matrix.',
        ['Choose the right measure for a model\'s job'], 55, { after: ['CLASSIFICATION'] }),
      u('OVERFITTING', 'When a Model Memorises',
        'Overfitting and underfitting, seen in numbers rather than described.',
        ['Recognise overfitting and do something about it'], 50, { after: ['EVALUATION'] }),
      u('RESPONSIBLE_AI', 'Models That Affect People',
        'Bias, fairness and what a model should not be used to decide.',
        ['Say where a model would be unfair, and what to do'], 45, { after: ['OVERFITTING'] }),
      ...closeOut('Machine Learning', 'RESPONSIBLE_AI', 50, 60, 120),
    ],
  },

  T2_TRACK_MOBILE: {
    category: 'DIRECTION',
    units: [
      u('APP_STRUCTURE', 'How an App Is Put Together',
        'Screens, navigation and the tree a user moves through.',
        ['Lay out an app as screens and routes'], 50),
      u('LAYOUT', 'Layout for a Hand',
        'Small screens, thumbs, long text and large system fonts.',
        ['Build a screen that works on the smallest phone'], 50, { after: ['APP_STRUCTURE'] }),
      u('STATE', 'State on a Screen',
        'What a screen remembers, and telling the framework it changed.',
        ['Make a screen update when its data does'], 50, { after: ['LAYOUT'] }),
      u('NAVIGATION', 'Moving Between Screens',
        'Passing data forward, coming back, and the back button.',
        ['Navigate between screens without losing state'], 50, { after: ['STATE'] }),
      u('NETWORKING', 'Talking to a Server From a Phone',
        'Fetching JSON, and the four states on a bad connection.',
        ['Show server data with loading, empty and error states'], 55, { after: ['NAVIGATION'] }),
      u('LOCAL_STORAGE', 'Remembering Between Launches',
        'Local storage, and what must survive the app being killed.',
        ['Keep what the user would hate to lose'], 50, { after: ['NETWORKING'] }),
      u('LIFECYCLE', 'When the System Takes Over',
        'Background, resume and termination — and restoring where somebody was.',
        ['Handle an interruption without losing the user\'s place'], 50, { after: ['LOCAL_STORAGE'] }),
      u('PERMISSIONS', 'Asking for the Camera, Politely',
        'Permissions in context, and behaving when they are refused.',
        ['Request a permission properly and handle a refusal'], 45, { after: ['LIFECYCLE'] }),
      ...closeOut('Mobile Work', 'PERMISSIONS', 50, 60, 120),
    ],
  },

  T2_TRACK_CLOUD: {
    category: 'DIRECTION',
    units: [
      u('WHAT_CLOUD_IS', 'What You Are Actually Renting',
        'Compute, storage and networking as services, and what each costs.',
        ['Say what a cloud provider gives you and what it charges for'], 45),
      u('SERVERS', 'A Machine You Do Not Own',
        'Provisioning an instance, reaching it, and keeping it secure.',
        ['Create and connect to a cloud machine safely'], 50, { after: ['WHAT_CLOUD_IS'] }),
      u('DEPLOYING', 'Putting an Application Online',
        'Getting code onto a server and serving it to the internet.',
        ['Deploy an application somebody else can reach'], 55, { after: ['SERVERS'] }),
      u('CONFIG_SECRETS', 'Configuration and Secrets in Production',
        'Environment variables, secret stores, and never committing either.',
        ['Configure a deployed application without shipping secrets'], 45, { after: ['DEPLOYING'] }),
      u('CONTAINERS', 'Shipping the Environment With the Code',
        'Containers, images, and "it works on my machine" solved.',
        ['Package an application so it runs the same anywhere'], 55, { after: ['CONFIG_SECRETS'] }),
      u('CI_CD', 'Automating the Path to Production',
        'A pipeline that tests and deploys, and what it must refuse to ship.',
        ['Automate the steps between a commit and a deployment'], 55, { after: ['CONTAINERS'] }),
      u('MONITORING', 'Knowing It Broke Before Users Do',
        'Logs, metrics and alerts that mean something.',
        ['Find out what a running system is doing'], 50, { after: ['CI_CD'] }),
      u('RELIABILITY', 'When It Breaks at Three in the Morning',
        'Backups, rollbacks and the runbook you will be glad of.',
        ['Recover a broken deployment calmly'], 50, { after: ['MONITORING'] }),
      ...closeOut('Cloud Work', 'RELIABILITY', 50, 60, 120),
    ],
  },

  T2_TRACK_SECURITY: {
    category: 'DIRECTION',
    units: [
      u('ATTACKER_VIEW', 'Mapping What Could Be Attacked',
        'Attack surface, entry points and the value behind each.',
        ['Map a system\'s attack surface'], 50),
      u('NETWORK_SECURITY', 'Attacks That Come Over the Network',
        'Ports, traffic, interception, and what encryption really prevents.',
        ['Explain how traffic is intercepted and what stops it'], 55, { after: ['ATTACKER_VIEW'] }),
      u('WEB_VULNERABILITIES', 'The Web Vulnerabilities That Keep Happening',
        'Injection, broken access control and the rest of the common list.',
        ['Find and explain a common web vulnerability'], 55, { after: ['NETWORK_SECURITY'] }),
      u('AUTH_ATTACKS', 'Attacking the Front Door',
        'Credential stuffing, weak resets and sessions that never expire.',
        ['Assess whether a login is actually safe'], 50, { after: ['WEB_VULNERABILITIES'] }),
      u('TOOLING', 'The Tools, and What They Do Not Tell You',
        'Scanners and proxies on systems you own, and reading their output critically.',
        ['Use a scanner on your own system and verify its findings'], 55, { after: ['AUTH_ATTACKS'] }),
      u('HARDENING', 'Closing What You Found',
        'Fixes, configuration and defence in depth.',
        ['Fix a vulnerability at its root rather than hiding it'], 50, { after: ['TOOLING'] }),
      u('INCIDENTS', 'When Something Has Already Happened',
        'Detection, containment and what to preserve for whoever investigates.',
        ['Respond to an incident without destroying the evidence'], 50, { after: ['HARDENING'] }),
      u('LAW_AND_ETHICS', 'Authorisation, in Writing',
        'The law, scope, disclosure, and the line that separates testing from crime.',
        ['State what makes a test legal, and report a finding properly'], 45, { after: ['INCIDENTS'] }),
      ...closeOut('Security Work', 'LAW_AND_ETHICS', 50, 60, 120),
    ],
  },

  /* ── B12 · Projects ─────────────────────────────────────────────────────────────────── */
  T2_PROJECTS: {
    category: 'UNIVERSAL',
    units: [
      u('SCOPING', 'Deciding What to Build',
        'Turning an idea into something finishable, with what is deliberately left out.',
        ['Scope a project you can actually finish'], 50),
      u('PLANNING', 'Planning Work You Can Track',
        'Breaking a build into pieces, ordering them, and knowing when one is done.',
        ['Break a project into tasks with a definition of done'], 50, { after: ['SCOPING'] }),
      u('GUIDED_BUILD', 'Building It, Step by Step',
        'A guided build through the parts most projects share.',
        ['Build a working application from a plan'], 120, { unitType: 'PROJECT', after: ['PLANNING'] }),
      u('EXTENDING', 'Adding a Feature to Existing Code',
        'Working inside somebody else\'s codebase without breaking it.',
        ['Add a feature to an unfamiliar codebase'], 110, { unitType: 'PROJECT', after: ['GUIDED_BUILD'] }),
      u('INTEGRATION', 'Joining Two Systems Together',
        'An application that consumes an API and stores what it learns.',
        ['Integrate an external service into your own application'], 120, { unitType: 'PROJECT', after: ['EXTENDING'] }),
      u('INDEPENDENT', 'Building Something of Your Own',
        'Your own idea, scoped, built and explained.',
        ['Deliver a project you chose and scoped yourself'], 120, { unitType: 'PROJECT', after: ['INTEGRATION'] }),
      u('TEAM_PROJECT', 'Building With Somebody Else',
        'Shared repository, split work, review and integration.',
        ['Deliver a project as part of a team'], 120, { unitType: 'PROJECT', after: ['INDEPENDENT'] }),
    ],
  },

  /* ── B13 · Being hireable ───────────────────────────────────────────────────────────── */
  T2_COMMUNICATION: {
    category: 'ENRICHMENT',
    units: [
      u('EXPLAINING', 'Explaining Something Technical Simply',
        'Pitching an explanation at the person in front of you.',
        ['Explain a technical idea to a non-technical listener'], 45),
      u('ASKING', 'Asking a Question That Gets Answered',
        'What you tried, what happened, what you expected — and why that gets help fast.',
        ['Ask for help in a way that respects everybody\'s time'], 45, { after: ['EXPLAINING'] }),
      u('WRITING', 'Writing That Gets Read',
        'Messages, issues and updates that are short and complete.',
        ['Write a technical message somebody can act on'], 45, { after: ['ASKING'] }),
      u('DESIGN_DECISIONS', 'Explaining Why You Built It That Way',
        'Stating a decision, its alternatives and its trade-off.',
        ['Defend a design decision with its trade-offs'], 50, { after: ['WRITING'] }),
      u('PRESENTING', 'Showing Your Work',
        'Demonstrating a project so the audience sees what matters.',
        ['Present a project in five minutes convincingly'], 50, { after: ['DESIGN_DECISIONS'] }),
      u('PRACTICE', 'Communication Practice',
        'Explaining, writing and presenting repeatedly, with feedback.',
        ['Explain unfamiliar work clearly, on demand'], 55, { unitType: 'PRACTICE', after: ['PRESENTING'] }),
    ],
  },

  T2_PORTFOLIO: {
    category: 'ENRICHMENT',
    units: [
      u('WHAT_COUNTS', 'What Counts as Evidence',
        'Why a repository beats a claim, and what a reviewer actually opens.',
        ['Judge your own work as a reviewer would'], 45),
      u('GITHUB_PROFILE', 'A GitHub Profile Worth Visiting',
        'Pinned work, a profile readme, and a history that shows consistency.',
        ['Set up a profile that shows what you can do'], 50, { after: ['WHAT_COUNTS'] }),
      u('REPOSITORY_QUALITY', 'A Repository Somebody Can Run',
        'Structure, setup instructions, no secrets, and code that runs from a clone.',
        ['Prepare a repository a stranger can clone and run'], 50, { after: ['GITHUB_PROFILE'] }),
      u('README', 'The README That Does the Work',
        'What it does, how to run it, what you decided — in that order.',
        ['Write a README that answers a reviewer\'s questions'], 50, { after: ['REPOSITORY_QUALITY'] }),
      u('WRITE_UPS', 'Writing Up What You Built',
        'A short piece per project: the problem, the approach and what you learned.',
        ['Write up a project so its thinking is visible'], 50, { after: ['README'] }),
      u('DEMOS', 'Showing It Working',
        'A short demo or screenshots, for the reviewer who will not run it.',
        ['Demonstrate a project in under two minutes'], 45, { after: ['WRITE_UPS'] }),
      u('PORTFOLIO_BUILD', 'Assembling the Portfolio',
        'Three pieces of work, presented as a body of evidence.',
        ['Assemble a portfolio that stands on its own'], 110, { unitType: 'PROJECT', after: ['DEMOS'] }),
    ],
  },

  T2_INTERNSHIP: {
    category: 'ENRICHMENT',
    units: [
      u('WHAT_INTERNSHIPS_ARE', 'What an Internship Actually Is',
        'What companies expect from a second-year intern, and what they do not.',
        ['Say what an internship expects of you'], 45),
      u('JOB_DESCRIPTIONS', 'Reading a Job Description Properly',
        'Requirements against nice-to-haves, and what is negotiable.',
        ['Read a posting and judge whether to apply'], 45, { after: ['WHAT_INTERNSHIPS_ARE'] }),
      u('MATCHING', 'Matching Yourself Honestly',
        'Mapping evidence to requirements, and naming the gaps.',
        ['Map your evidence against a real posting'], 45, { after: ['JOB_DESCRIPTIONS'] }),
      u('CLOSING_GAPS', 'Closing the Gap Between You and the Role',
        'Turning a missing requirement into a plan with a date on it.',
        ['Plan to close a specific gap before applying'], 45, { after: ['MATCHING'] }),
      u('RESUME', 'A Resume That Survives Ten Seconds',
        'One page, evidence first, tailored to the posting.',
        ['Write a resume aimed at a specific role'], 55, { after: ['CLOSING_GAPS'] }),
      u('APPLYING', 'Applying Without Disappearing',
        'Where to apply, what to send, and keeping track of it.',
        ['Apply with a tracked, tailored application'], 45, { after: ['RESUME'] }),
      u('BEHAVIOURAL', 'Answering Questions About Yourself',
        'Structured answers about real work you did.',
        ['Answer behavioural questions with concrete examples'], 50, { after: ['APPLYING'] }),
      u('PROJECT_INTERVIEW', 'Being Asked About Your Project',
        'The questions that follow "tell me about this project".',
        ['Defend your own project under questioning'], 50, { after: ['BEHAVIOURAL'] }),
      u('MOCK_INTERVIEW', 'A Full Interview, Start to Finish',
        'Introduction, technical questions, project discussion and your questions.',
        ['Complete a full mock interview and act on the feedback'], 60, { unitType: 'CHECKPOINT', after: ['PROJECT_INTERVIEW'] }),
    ],
  },

  /* ── B14 · Verification ─────────────────────────────────────────────────────────────── */
  T2_VERIFICATION: {
    category: 'UNIVERSAL',
    units: [
      u('CORE_VERIFICATION', 'Proving the Core of the Year',
        'OOP, data structures, algorithms and testing, measured rather than assumed.',
        ['Demonstrate the year\'s core skills under assessment'], 60, { unitType: 'CHECKPOINT' }),
      u('SYSTEMS_VERIFICATION', 'Proving the Systems Side',
        'Databases, HTTP, APIs, Git and security, measured together.',
        ['Demonstrate the year\'s systems skills under assessment'], 60, { unitType: 'CHECKPOINT', after: ['CORE_VERIFICATION'] }),
      u('DIRECTION_VERIFICATION', 'Proving Your Direction',
        'The track you chose, assessed on its own terms.',
        ['Demonstrate the skills of your chosen direction'], 60, { unitType: 'CHECKPOINT', after: ['SYSTEMS_VERIFICATION'] }),
      u('PORTFOLIO_REVIEW', 'Your Evidence, Reviewed',
        'A review of the work the year produced, against what employers look for.',
        ['Present your portfolio and act on the review'], 55, { after: ['DIRECTION_VERIFICATION'] }),
      u('CAPSTONE', 'The Year-2 Capstone',
        'One substantial piece of work that uses the year: built, tested, documented and defended.',
        ['Deliver and defend a capstone that uses the whole year'], 150, { unitType: 'PROJECT', after: ['PORTFOLIO_REVIEW'] }),
    ],
  },
};
