import { TopicSeed } from './year1MegaCurriculum';
import { u, interviewUnit } from './year4UnitKit';

/**
 * Year 4, stages 7 to 10 — interviews, portfolio, the mock series, the simulation and the
 * capstone. Modules P18 to P24.
 *
 * ── THIS IS THE PART THAT MAKES YEAR 4 A DIFFERENT YEAR ───────────────────────────────────
 *
 * Everything before this teaches capability. These eighty-eight units are about whether the
 * capability can be SEEN — which is a separate thing, is measured by somebody else in an hour,
 * and is where strong students lose offers.
 *
 * The spec's closing promise names six outcomes, and four of them live here: communication,
 * interview performance, portfolio evidence and remaining-gap awareness. None of them is
 * assessed by a quiz, which is why almost every unit below is PRACTICE — a rehearsal the student
 * is meant to be bad at the first time and meet again.
 *
 * ── THE TEN MOCKS, AND WHERE THE TENTH ONE WENT ───────────────────────────────────────────
 *
 * The spec's §10 lists ten. Nine of them are units in P22. The tenth is "Placement Simulation —
 * Aptitude → MCQ → Coding → Technical → Project → HR", which is not a mock interview at all but
 * the whole six-round day, and it is P23. Filing it as a tenth mock would have hidden a full
 * day's assessment inside a topic about rehearsal.
 *
 * ── WHY THE SIMULATION ENDS IN A DEBRIEF TOPIC AND NOT A SCORE ────────────────────────────
 *
 * The spec is unusually firm about this: "the simulation produces capability-specific evidence
 * and targeted remediation rather than a single opaque placement score." So T4_SIM_DEBRIEF is a
 * topic rather than a paragraph at the end of the simulation, and P24 exists to act on it. A
 * simulation that produced a number and stopped would be the exact thing the spec warns against.
 */

export const YEAR4_CONVERSION: Record<string, TopicSeed> = {
  /* ── P18 · Technical and coding interviews ───────────────────────────────────────────── */
  T4_IV_METHOD: {
    category: 'UNIVERSAL',
    units: [
      u('THE_LOOP', 'Understand, Approach, Implement, Test, Explain',
        'The five steps a technical interview actually runs on, and what skipping each one looks like from the other chair.',
        ['Work a problem through all five steps in order rather than jumping to code'], 60),
      u('THINKING_ALOUD', 'Thinking Aloud Without Rambling',
        'Saying enough that the interviewer can follow you, and stopping before it becomes noise.',
        ['Narrate your own reasoning at a level somebody could actually follow'],
        55, { after: ['THE_LOOP'] }),
      u('WHEN_YOU_ARE_STUCK', 'What To Do In the Silence',
        'The three moves that recover a stuck interview, and the one that ends it.',
        ['Recover from being stuck without going quiet or guessing'],
        55, { after: ['THINKING_ALOUD'] }),
      u('PRACTICE', 'Working a Problem Out Loud',
        'A problem, a clock and somebody listening. The method rather than the answer.',
        ['Work a problem out loud from understanding to complexity without going silent'],
        65, { unitType: 'PRACTICE', after: ['WHEN_YOU_ARE_STUCK'] }),
      interviewUnit('Interview Method', 'PRACTICE'),
    ],
  },
  T4_IV_FUNDAMENTALS: {
    category: 'UNIVERSAL',
    units: [
      u('PROGRAMMING_QUESTIONS', 'Programming Questions at Interview Depth',
        'Not "what is a list" but "why did you use one" — and the follow-up about what it costs.',
        ['Answer a programming question at the depth the follow-up will probe'], 55),
      u('SQL_QUESTIONS', 'SQL Questions at Interview Depth',
        'Writing the query on a whiteboard, and explaining what the database will do with it.',
        ['Write and justify a non-trivial query without an editor'],
        60, { after: ['PROGRAMMING_QUESTIONS'] }),
      u('GIT_QUESTIONS', 'Git Questions at Interview Depth',
        'What you did when two branches conflicted, and what you would do differently.',
        ['Describe a real Git situation you handled, including what went wrong'],
        50, { after: ['SQL_QUESTIONS'] }),
      u('PRACTICE', 'A Fundamentals Round',
        'Programming, SQL and Git in one sitting, at the pace a first round runs.',
        ['Sit a fundamentals round and answer across all three areas'],
        65, { unitType: 'PRACTICE', after: ['GIT_QUESTIONS'] }),
      interviewUnit('Fundamentals', 'PRACTICE'),
    ],
  },
  T4_IV_DSA: {
    category: 'UNIVERSAL',
    units: [
      u('THE_CODING_ROUND', 'What the Coding Round Is Actually Scoring',
        'Correctness, yes — and also the tests you wrote, the complexity you volunteered, and how you took the hint.',
        ['Name what a coding round scores beyond whether the code runs'], 60),
      u('IMPROVING_ON_DEMAND', 'When They Ask For Better Than That',
        'The follow-up is not a rejection. The three standard directions an improvement comes from.',
        ['Improve a working solution when asked, rather than defending the first one'],
        65, { after: ['THE_CODING_ROUND'] }),
      u('PRACTICE', 'A Timed Coding Interview',
        'One problem, forty-five minutes, out loud, with a follow-up at the end.',
        ['Reach a correct solution and improve it inside the time a round allows'],
        70, { unitType: 'PRACTICE', after: ['IMPROVING_ON_DEMAND'] }),
      interviewUnit('DSA Under Pressure', 'PRACTICE'),
      u('CHECKPOINT', 'Coding Interview Checkpoint',
        'Whether a coding round is survivable yet, measured rather than felt.',
        ['Show coding-interview performance at the standard a technical round expects'],
        50, { unitType: 'CHECKPOINT', after: ['INTERVIEW_QUESTION'] }),
    ],
  },
  T4_IV_CORE_CS: {
    category: 'UNIVERSAL',
    units: [
      u('EXPLAINING_A_PROCESS', 'Explaining What a Process Is, Properly',
        'Processes, threads and scheduling, explained to somebody probing for where the understanding stops.',
        ['Explain processes and threads well enough to survive three follow-ups'], 60),
      u('EXPLAINING_A_PACKET', 'Explaining What Happens When You Type a URL',
        'The question every core-CS round contains, and how far down the interviewer will go.',
        ['Walk through a request from keystroke to rendered page, at increasing depth'],
        60, { after: ['EXPLAINING_A_PROCESS'] }),
      u('EXPLAINING_A_TRANSACTION', 'Explaining What a Transaction Guarantees',
        'ACID as behaviour rather than as an acronym, and what a database actually does to provide it.',
        ['Explain transaction guarantees in terms of what can and cannot be observed'],
        60, { after: ['EXPLAINING_A_PACKET'] }),
      u('PRACTICE', 'A Core CS Round',
        'Operating systems, networking and databases, asked the way a round asks them.',
        ['Sit a core-CS round and answer from understanding rather than from recall'],
        65, { unitType: 'PRACTICE', after: ['EXPLAINING_A_TRANSACTION'] }),
      interviewUnit('Core CS', 'PRACTICE'),
    ],
  },

  /* ── P19 · Project and system-design interviews ──────────────────────────────────────── */
  T4_IV_PROJECT: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_THEY_ARE_CHECKING', 'What a Project Interview Is Actually Checking',
        'Whether you built it, whether you understood it, and whether you made any decisions at all.',
        ['Name what a project round is testing, beyond whether the project exists'], 55),
      u('THE_HARDEST_BUG', 'The Hardest Bug, and How You Found It',
        'The question that separates somebody who built it from somebody who watched it being built.',
        ['Describe a real bug in your own work: symptom, investigation, cause and fix'],
        60, { after: ['WHAT_THEY_ARE_CHECKING'] }),
      u('TRADE_OFFS_YOU_MADE', 'The Alternatives You Rejected',
        'Every decision had another option. Knowing what it was is most of what "senior" means at this stage.',
        ['State a technology or design choice you made and the alternative you did not take'],
        60, { after: ['THE_HARDEST_BUG'] }),
      u('PRACTICE', 'Being Interviewed On Your Own Project',
        'Architecture, data flow, the hardest bug, security, testing and scaling — without notes.',
        ['Account for your own project across every area an interviewer will open'],
        75, { unitType: 'PRACTICE', after: ['TRADE_OFFS_YOU_MADE'] }),
      interviewUnit('Your Own Project', 'PRACTICE'),
    ],
  },
  T4_SD_FUNDAMENTALS: {
    category: 'UNIVERSAL',
    units: [
      u('COMPONENTS_AND_APIS', 'Drawing the Components and the Calls Between Them',
        'Boxes and arrows that mean something: what each box owns and what each arrow carries.',
        ['Draw a system as components with defined responsibilities and interfaces'], 65),
      u('DATA_AND_STORAGE', 'Where the Data Lives',
        'What is stored, in what shape, and the access pattern that decides the answer.',
        ['Choose storage from the access pattern rather than from familiarity'],
        65, { after: ['COMPONENTS_AND_APIS'] }),
      u('SCALING_AND_FAILURE', 'Where It Breaks First',
        'The bottleneck, the single point of failure, and the honest answer about what you would do at ten times the load.',
        ['Identify the first thing that breaks as a system grows, and say what you would do'],
        70, { after: ['DATA_AND_STORAGE'] }),
      u('PRACTICE', 'Designing a Small System',
        'A one-line brief taken to components, data, APIs and a stated failure point.',
        ['Take a brief to a defensible design inside forty-five minutes'],
        75, { unitType: 'PRACTICE', after: ['SCALING_AND_FAILURE'] }),
      interviewUnit('System Design Fundamentals', 'PRACTICE'),
    ],
  },
  T4_SD_INTERVIEW: {
    category: 'UNIVERSAL',
    units: [
      u('FROM_ONE_LINE_TO_A_DESIGN', 'Starting From Almost Nothing',
        'Clarifying questions first, scope second, design third — and why starting at the database loses the round.',
        ['Open a system-design round with the questions that make the problem answerable'], 65),
      u('SAYING_THE_TRADE_OFFS', 'Saying the Trade-off Out Loud',
        'There is no right answer, and pretending there is one is the failure. Naming what you gave up.',
        ['State what your design sacrifices, before the interviewer points it out'],
        65, { after: ['FROM_ONE_LINE_TO_A_DESIGN'] }),
      u('PRACTICE', 'A Full System-Design Round',
        'Forty-five minutes, a vague brief and somebody changing the requirements halfway through.',
        ['Hold a design together when the requirements move'],
        75, { unitType: 'PRACTICE', after: ['SAYING_THE_TRADE_OFFS'] }),
      interviewUnit('System Design', 'PRACTICE'),
      u('CHECKPOINT', 'System Design Checkpoint',
        'Whether a design round is survivable yet, measured rather than felt.',
        ['Show system-design reasoning at the standard the round expects'],
        50, { unitType: 'CHECKPOINT', after: ['INTERVIEW_QUESTION'] }),
    ],
  },

  /* ── P20 · HR, behavioural and communication ─────────────────────────────────────────── */
  T4_HR_STAR: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_STAR_IS_FOR', 'Why an Answer Needs a Structure',
        'Not a formula to recite: a way of making sure an answer contains an actual event and an actual outcome.',
        ['Tell the difference between an answer with a situation in it and one with only a sentiment'], 50),
      u('BUILDING_YOUR_STORIES', 'Six Stories That Cover Most Questions',
        'Building a small set of real events from your own three years, each usable for several questions.',
        ['Prepare a set of real stories from your own work that most behavioural questions can draw on'],
        60, { after: ['WHAT_STAR_IS_FOR'] }),
      u('PRACTICE', 'Answering With a Structure',
        'Questions you have not seen, answered from stories you have.',
        ['Give a structured answer containing a real situation and a real result'],
        60, { unitType: 'PRACTICE', after: ['BUILDING_YOUR_STORIES'] }),
      interviewUnit('Behavioural Answers', 'PRACTICE'),
    ],
  },
  T4_HR_QUESTIONS: {
    category: 'UNIVERSAL',
    units: [
      u('TELL_ME_ABOUT_YOURSELF', 'The First Ninety Seconds',
        'The question that is always first and is almost always answered badly.',
        ['Give a ninety-second introduction that is about your work rather than your biography'], 50),
      u('FAILURE_AND_CONFLICT', 'The Failure and the Disagreement',
        'Two questions with a wrong kind of answer: the humble brag, and the colleague who was simply wrong.',
        ['Answer a failure or conflict question without evasion and without blaming somebody'],
        60, { after: ['TELL_ME_ABOUT_YOURSELF'] }),
      u('WHY_THIS_ROLE', 'Why This Role, and Why You',
        'Motivation questions, answered from something specific rather than from the company website.',
        ['Answer a motivation question with something only you could have said'],
        50, { after: ['FAILURE_AND_CONFLICT'] }),
      u('PRACTICE', 'The Questions That Always Come',
        'The standard set, asked in the order an HR round asks them.',
        ['Answer the standard behavioural set without rehearsing sounding rehearsed'],
        60, { unitType: 'PRACTICE', after: ['WHY_THIS_ROLE'] }),
      interviewUnit('The HR Round', 'PRACTICE'),
    ],
  },
  T4_COMM_PRESENT: {
    category: 'UNIVERSAL',
    units: [
      u('STRUCTURING_A_TALK', 'Five Minutes, Structured',
        'What goes in the first thirty seconds, what can be cut, and the ending that is not "so yeah".',
        ['Structure a short technical talk so the point arrives early'], 55),
      u('TAKING_QUESTIONS', 'Taking a Question You Cannot Answer',
        'The three honest responses, and why "I do not know, but here is how I would find out" is one of them.',
        ['Handle a question you cannot answer without bluffing or freezing'],
        50, { after: ['STRUCTURING_A_TALK'] }),
      u('PRACTICE', 'Presenting to a Room',
        'Five minutes on your own work, and the questions afterwards.',
        ['Present your own work and take the questions'],
        65, { unitType: 'PRACTICE', after: ['TAKING_QUESTIONS'] }),
      interviewUnit('Presenting Technical Work', 'PRACTICE'),
    ],
  },
  T4_COMM_WRITTEN: {
    category: 'UNIVERSAL',
    units: [
      u('PROFESSIONAL_EMAIL', 'An Email That Gets a Reply',
        'Subject, ask, context, in that order — and the length beyond which nobody reads it.',
        ['Write an email whose ask is visible in the first line'], 50),
      u('STATUS_AND_FOLLOWUP', 'Status Updates and Following Up',
        'Saying where something is without hiding that it is late, and chasing without irritating.',
        ['Write a status update that is honest about a delay, and a follow-up that is not a nag'],
        50, { after: ['PROFESSIONAL_EMAIL'] }),
      u('PRACTICE', 'Writing What a Workplace Expects',
        'The three messages you will write in your first fortnight, written now.',
        ['Write professional messages at the standard a workplace assumes rather than teaches'],
        55, { unitType: 'PRACTICE', after: ['STATUS_AND_FOLLOWUP'] }),
      u('CHECKPOINT', 'Communication Checkpoint',
        'Whether the spoken and written standard is there, measured rather than felt.',
        ['Show spoken and written communication at the standard an employer assumes'],
        45, { unitType: 'CHECKPOINT', after: ['PRACTICE'] }),
    ],
  },

  /* ── P21 · Portfolio, resume and applications ────────────────────────────────────────── */
  T4_PORTFOLIO: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_A_REVIEWER_LOOKS_AT', 'Ninety Seconds On Your GitHub',
        'What somebody actually opens, in what order, and what they conclude from each.',
        ['Predict what a reviewer will conclude from your profile in ninety seconds'], 50),
      u('README_AND_DEMO', 'The README and the Demo',
        'The two things that decide whether a repository is assessed at all.',
        ['Write a README and provide a demo that let somebody assess the work without running it'],
        60, { after: ['WHAT_A_REVIEWER_LOOKS_AT'] }),
      u('CLEANING_THE_REPOSITORY', 'Cleaning Up What Is Already There',
        'Commit history, dead branches, committed secrets and the four repositories that should be private.',
        ['Get an existing repository into a state you would be happy to be judged on'],
        60, { after: ['README_AND_DEMO'] }),
      u('PRACTICE', 'Getting Your Own Portfolio Assessed',
        'Your actual profile, reviewed against what a reviewer looks for.',
        ['Take your own portfolio to the state where the ability is visible without explanation'],
        70, { unitType: 'PRACTICE', after: ['CLEANING_THE_REPOSITORY'] }),
    ],
  },
  T4_RESUME: {
    category: 'UNIVERSAL',
    units: [
      u('ONE_PAGE', 'One Page, and What Earns Its Space',
        'What goes on a graduate resume, in what order, and the sections that are costing you room.',
        ['Decide what belongs on one page and what is taking space from something better'], 55),
      u('CLAIMS_THAT_CHECK_OUT', 'Every Claim Has to Survive a Question',
        'A resume is a list of things you will be asked to prove. Writing it that way from the start.',
        ['Write bullet points you could be questioned on for ten minutes without difficulty'],
        60, { after: ['ONE_PAGE'] }),
      u('MATCHING_A_JOB_DESCRIPTION', 'Matching Yourself to a Specific Description',
        'Reading what a posting is actually asking for, and tailoring honestly rather than keyword-stuffing.',
        ['Tailor a resume to a specific job description without claiming anything untrue'],
        60, { after: ['CLAIMS_THAT_CHECK_OUT'] }),
      u('PRACTICE', 'Your Resume, Against a Real Posting',
        'Your own document, a real description, and the gap between them.',
        ['Produce a tailored one-page resume whose every claim is checkable'],
        65, { unitType: 'PRACTICE', after: ['MATCHING_A_JOB_DESCRIPTION'] }),
    ],
  },
  T4_APPLICATIONS: {
    category: 'UNIVERSAL',
    units: [
      u('WHERE_TO_APPLY', 'Where the Roles Actually Are',
        'Campus drives, off-campus, referrals and the postings that are not real. Eligibility read properly.',
        ['Find roles you are eligible for and rule out the ones you are not'], 55),
      u('TRACKING_IT', 'Running Several Applications At Once',
        'Deadlines, rounds, follow-ups — and the spreadsheet that stops one from quietly lapsing.',
        ['Track several applications through their rounds without losing one'],
        50, { after: ['WHERE_TO_APPLY'] }),
      u('PRACTICE', 'Applying, Properly',
        'A real application, start to finish, including the follow-up.',
        ['Complete a real application and record what happens next'],
        60, { unitType: 'PRACTICE', after: ['TRACKING_IT'] }),
      u('CHECKPOINT', 'Evidence and Applications Checkpoint',
        'Whether the portfolio, the resume and the applications are actually in place.',
        ['Show a portfolio, a resume and live applications that stand up to review'],
        45, { unitType: 'CHECKPOINT', after: ['PRACTICE'] }),
    ],
  },

  /* ── P22 · The mock series: nine of the spec's ten ───────────────────────────────────── */
  T4_MOCK_TECHNICAL: {
    category: 'UNIVERSAL',
    units: [
      u('MOCK_1_FOUNDATION', 'Mock 1 — Foundation',
        'Programming, SQL and Git, at first-round pace. The one that establishes the baseline.',
        ['Sit a foundation technical interview and act on the debrief'],
        70, { unitType: 'PRACTICE' }),
      u('MOCK_2_DSA', 'Mock 2 — DSA',
        'One coding problem, the complexity, and the follow-up asking for better.',
        ['Sit a DSA interview and improve the solution when asked'],
        70, { unitType: 'PRACTICE', after: ['MOCK_1_FOUNDATION'] }),
      u('MOCK_3_CORE_CS', 'Mock 3 — Core CS',
        'Operating systems, databases, networking and OOP, probed until the understanding runs out.',
        ['Sit a core-CS interview and hold up under the follow-ups'],
        70, { unitType: 'PRACTICE', after: ['MOCK_2_DSA'] }),
      u('MOCK_7_FULL_TECHNICAL', 'Mock 7 — Full Technical',
        'Mixed technical, unannounced: whatever the interviewer decides to open with.',
        ['Sit a mixed technical interview without knowing what is coming'],
        80, { unitType: 'PRACTICE', after: ['MOCK_3_CORE_CS'] }),
      u('MOCK_8_FINAL_TECHNICAL', 'Mock 8 — Final Technical',
        'A full timed technical simulation, run as the real thing rather than as practice.',
        ['Sit a full timed technical round at the standard the real one will apply'],
        90, { unitType: 'PRACTICE', after: ['MOCK_7_FULL_TECHNICAL'] }),
    ],
  },
  T4_MOCK_SPECIALIZATION: {
    category: 'UNIVERSAL',
    units: [
      u('MOCK_4_PROJECT', 'Mock 4 — Project',
        'Your own project: architecture, implementation, debugging and the decisions you made.',
        ['Be interviewed on your own project and account for all of it'],
        75, { unitType: 'PRACTICE' }),
      u('MOCK_5_SPECIALIZATION', 'Mock 5 — Specialization',
        'Your direction alone, at the depth somebody hiring for it would probe.',
        ['Be interviewed on your specialization and find where its edge is'],
        75, { unitType: 'PRACTICE', after: ['MOCK_4_PROJECT'] }),
      u('MOCK_6_SYSTEM_DESIGN', 'Mock 6 — System Design',
        'A brief, a whiteboard, and somebody changing the requirements once you have committed.',
        ['Sit a system-design round and defend the trade-offs you chose'],
        80, { unitType: 'PRACTICE', after: ['MOCK_5_SPECIALIZATION'] }),
    ],
  },
  T4_MOCK_HR: {
    category: 'UNIVERSAL',
    units: [
      u('MOCK_9_HR', 'Mock 9 — HR and Behavioural',
        'The round treated as a round: communication, structure and professional scenarios.',
        ['Sit an HR round and hear how the answers actually landed'],
        65, { unitType: 'PRACTICE' }),
      u('READING_THE_DEBRIEF', 'Reading a Debrief Without Defending Yourself',
        'The hardest part of a mock is the twenty minutes afterwards. Hearing it rather than explaining it away.',
        ['Take feedback on your own performance and turn it into one specific change'],
        50, { after: ['MOCK_9_HR'] }),
      u('CHECKPOINT', 'Mock Series Checkpoint',
        'What the nine mocks together say about where the performance is, rather than the capability.',
        ['Show interview performance across technical, project and behavioural rounds'],
        50, { unitType: 'CHECKPOINT', after: ['READING_THE_DEBRIEF'] }),
    ],
  },

  /* ── P23 · The final placement simulation: the spec's tenth mock, and a whole day ────── */
  T4_SIM_ROUNDS: {
    category: 'UNIVERSAL',
    units: [
      u('PREPARING_FOR_THE_DAY', 'The Day Itself',
        'Six rounds in order, what each one screens for, and what happens between them.',
        ['Know the shape of the day well enough that none of it is a surprise'], 50),
      u('ROUNDS_ONE_TO_THREE', 'Rounds 1 to 3 — Aptitude, Technical MCQ, Coding',
        'The written half of a drive, run back to back at the real pace.',
        ['Complete the written and coding rounds under drive conditions'],
        150, { unitType: 'PRACTICE', after: ['PREPARING_FOR_THE_DAY'] }),
      u('ROUNDS_FOUR_TO_SIX', 'Rounds 4 to 6 — Technical, Project, HR',
        'The interview half, on the same day, when you are already tired. Which is the point.',
        ['Complete the interview rounds under drive conditions, after the written ones'],
        150, { unitType: 'PRACTICE', after: ['ROUNDS_ONE_TO_THREE'] }),
    ],
  },
  T4_SIM_DEBRIEF: {
    category: 'UNIVERSAL',
    units: [
      u('READING_THE_RESULT', 'Six Results, Not One Score',
        'What each round said about a different capability, and why an average would hide all of it.',
        ['Read a round-by-round result as six separate pieces of evidence'], 50),
      u('THE_TWO_THINGS_TO_FIX', 'The Two or Three Things Worth Fixing',
        'Choosing what to work on from the result rather than working on everything and moving nothing.',
        ['Choose the few specific things to close before the real drive, and say why those'],
        50, { after: ['READING_THE_RESULT'] }),
      u('CHECKPOINT', 'Simulation Checkpoint',
        'Where the six capabilities actually stand, recorded so the remediation has a target.',
        ['Have capability-specific evidence from a full simulation, and a remediation list from it'],
        45, { unitType: 'CHECKPOINT', after: ['THE_TWO_THINGS_TO_FIX'] }),
    ],
  },

  /* ── P24 · Verification and the capstone ─────────────────────────────────────────────── */
  T4_VERIFY_GAPS: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_IS_STILL_OPEN', 'What Is Still Open, Honestly',
        'The spec asks for remaining-gap awareness as an outcome. Knowing what you cannot yet do is part of being ready.',
        ['State what you still cannot do, specifically, without either panic or dismissal'], 50),
      u('CLOSING_THEM', 'Closing the Ones That Matter',
        'Targeted work on the two or three things the simulation exposed, rather than starting again.',
        ['Close a specific gap and show evidence that it closed'],
        70, { unitType: 'PRACTICE', after: ['WHAT_IS_STILL_OPEN'] }),
      u('PRACTICE', 'Re-verifying',
        'Being measured again on the thing you just worked on, rather than assuming it moved.',
        ['Show that a gap you worked on has actually closed'],
        60, { unitType: 'PRACTICE', after: ['CLOSING_THEM'] }),
    ],
  },
  T4_CAPSTONE: {
    category: 'UNIVERSAL',
    units: [
      u('SCOPING_IT', 'Scoping Something You Can Actually Finish',
        'The capstone fails on scope more often than on difficulty. Choosing something that ships.',
        ['Scope a capstone you can finish and defend, rather than one you can describe'], 60),
      u('BUILDING_IT', 'The Capstone',
        'One substantial piece of work, built properly, that the whole year is judged by.',
        ['Deliver a substantial system built to the Year-4 engineering standard'],
        200, { unitType: 'PROJECT', after: ['SCOPING_IT'] }),
      u('DEFENDING_IT', 'Defending the Capstone',
        'Architecture, decisions, failures and trade-offs, to somebody who will push on all four.',
        ['Defend the capstone against questions on every decision in it'],
        80, { unitType: 'PRACTICE', after: ['BUILDING_IT'] }),
      u('CHECKPOINT', 'Career Verification',
        'The final one: technical capability, project capability, communication, interview performance, portfolio and known gaps.',
        ['Show evidence across all six of the outcomes Year 4 promises'],
        55, { unitType: 'CHECKPOINT', after: ['DEFENDING_IT'] }),
    ],
  },
};
