import { TopicSeed } from './year1MegaCurriculum';
import { u, closeOut } from './year3UnitKit';

/**
 * Year 3, Stage 1 — engineering depth and readiness. Modules S01 to S10.
 *
 * ── WHAT THIS STAGE IS ────────────────────────────────────────────────────────────────────
 *
 * Everything a third-year needs before a specialization means anything. Year 2 taught objects,
 * data structures, databases and the web; this takes each of them to the depth an interviewer
 * probes and a production system demands, and adds the layers Year 2 never reached — architecture,
 * infrastructure, security engineering.
 *
 * ── ONE UNIT IS ONE SITTING ───────────────────────────────────────────────────────────────
 *
 * The same rule Years 1 and 2 hold. "Advanced Data Structures" is a module; "Keeping the
 * next-most-important item cheap to reach" is a unit. Nothing is called "basics" or
 * "fundamentals": the validator refuses a dataset that hides four lessons behind one title.
 *
 * ── A BANK, NOT A SCHEDULE ────────────────────────────────────────────────────────────────
 *
 * No day numbers. There are more units here than any programme length can hold, which is the
 * point — the backbone reaches every student and the rest is selected by evidence, direction and
 * the room the admin's length leaves.
 */

export const YEAR3_CORE: Record<string, TopicSeed> = {
  /* ── S01 · Year-3 readiness ──────────────────────────────────────────────────────────── */
  T3_READINESS: {
    category: 'UNIVERSAL',
    units: [
      u('PROGRAMMING_CHECK', 'Where Your Programming Actually Stands',
        'A short practical check across functions, objects and collections — not a lesson, a measurement.',
        ['Show what is in place across programming and object-oriented work, or find where it is not'],
        50, { unitType: 'PRACTICE' }),
      u('DSA_CHECK', 'Data Structures and Complexity, Checked',
        'Small problems over arrays, maps and recursion, timed, to see what is fluent.',
        ['Solve small structural problems and state what each one costs'],
        55, { unitType: 'PRACTICE', after: ['PROGRAMMING_CHECK'] }),
      u('DATA_WEB_CHECK', 'Databases and the Web, Checked',
        'A query, a request and a response — the three things every direction in Year 3 sits on.',
        ['Write a join and read an HTTP exchange without help'],
        50, { unitType: 'PRACTICE', after: ['DSA_CHECK'] }),
      u('TOOLING_CHECK', 'Git, the Shell and Your Environment',
        'Branching, a terminal and a project that runs on your machine, confirmed rather than assumed.',
        ['Run, branch and commit a real project from the command line'],
        45, { unitType: 'PRACTICE', after: ['DATA_WEB_CHECK'] }),
      u('CHECKPOINT', 'Year-3 Readiness Checkpoint',
        'Where the year starts for you, and what is being taught first because of it.',
        ['Have an accurate picture of what Year 3 will open with'],
        40, { unitType: 'CHECKPOINT', after: ['TOOLING_CHECK'] }),
    ],
  },
  T3_GAP_PLAN: {
    category: 'UNIVERSAL',
    units: [
      u('READING_YOUR_EVIDENCE', 'Reading Your Own Diagnostic',
        'What the numbers mean, what they do not, and why a low score on one skill is not a verdict.',
        ['Read your own skill profile without either dismissing it or over-reading it'], 40),
      u('THE_PLAN', 'What Is Being Taught First, and Why',
        'How the plan was built from your evidence, and what would change it.',
        ['Explain why your plan opens where it does'], 40, { after: ['READING_YOUR_EVIDENCE'] }),
    ],
  },

  /* ── S02 · Advanced programming and software design ──────────────────────────────────── */
  T3_ADV_OOP: {
    category: 'UNIVERSAL',
    units: [
      u('COMPOSITION_OVER_INHERITANCE', 'Composition, and When Inheritance Is Wrong',
        'Inheritance ties two things together forever. Composition lets them change apart. Where each belongs.',
        ['Choose composition over inheritance where it fits, and defend the choice'], 70),
      u('INTERFACES', 'Programming to an Interface',
        'Depending on what a thing DOES rather than what it IS, and what that buys when it changes.',
        ['Use an interface to decouple two things that would otherwise change together'],
        70, { after: ['COMPOSITION_OVER_INHERITANCE'] }),
      u('ABSTRACTION_COST', 'Abstraction Has a Price',
        'Every layer you add is a layer the next reader has to hold. When it earns its keep and when it does not.',
        ['Say what an abstraction costs as well as what it saves'], 60, { after: ['INTERFACES'] }),
      u('SOLID_IN_PRACTICE', 'Design Principles, Applied to Real Code',
        'Single responsibility and dependency inversion on code that already exists, not on a toy example.',
        ['Apply a design principle to a real class and show what improved'],
        70, { after: ['ABSTRACTION_COST'] }),
      ...closeOut('Advanced OOP', 'SOLID_IN_PRACTICE'),
    ],
  },
  T3_PATTERNS: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_A_PATTERN_IS', 'What a Pattern Actually Is',
        'A name for a shape that keeps appearing — not a rule, and not something to go looking for.',
        ['Explain why patterns have names, and what having a name buys a team'], 55),
      u('STRATEGY_AND_FACTORY', 'Strategy and Factory',
        'Swapping behaviour at runtime, and putting the decision about which thing to make in one place.',
        ['Recognise and apply strategy and factory in code you did not write'],
        70, { after: ['WHAT_A_PATTERN_IS'] }),
      u('OBSERVER_AND_ADAPTER', 'Observer and Adapter',
        'Telling interested parties something happened, and making two incompatible things fit.',
        ['Recognise and apply observer and adapter'], 70, { after: ['STRATEGY_AND_FACTORY'] }),
      u('OVERENGINEERING', 'When a Pattern Is More Machinery Than the Problem Deserves',
        'The commonest mistake with patterns is using one. What over-application looks like.',
        ['Say when a pattern is not worth its own weight'], 60, { after: ['OBSERVER_AND_ADAPTER'] }),
      ...closeOut('Design Patterns', 'OVERENGINEERING'),
    ],
  },
  T3_ERROR_DESIGN: {
    category: 'UNIVERSAL',
    units: [
      u('FAIL_LOUD_OR_DEGRADE', 'What Should Fail Loudly, and What Should Not',
        'A failed payment and a failed thumbnail are not the same event. Deciding which is which.',
        ['Decide, per failure, whether it stops the work or is absorbed'], 65),
      u('RETRIES_AND_TIMEOUTS', 'Retries, Timeouts and Making It Worse',
        'A retry on a slow system is a way of attacking yourself. Backoff, limits and idempotency.',
        ['Retry safely, and say when a retry is the wrong answer'], 70, { after: ['FAIL_LOUD_OR_DEGRADE'] }),
      u('WHAT_THE_CALLER_IS_TOLD', 'What the Caller Is Told',
        'An error a caller can act on, without leaking what they should not see.',
        ['Return an error that is useful to a caller and safe to show'],
        60, { after: ['RETRIES_AND_TIMEOUTS'] }),
      u('LOGGING_THE_FAILURE', 'Leaving Enough Behind',
        'Enough in the log that a 3am failure is explainable without reproducing it.',
        ['Log a failure so somebody else can diagnose it'], 60, { after: ['WHAT_THE_CALLER_IS_TOLD'] }),
      ...closeOut('Error Handling', 'LOGGING_THE_FAILURE'),
    ],
  },
  T3_DEPENDENCIES: {
    category: 'UNIVERSAL',
    units: [
      u('CONFIG_OUT_OF_CODE', 'Configuration Does Not Belong in Code',
        'The same build in three environments, without editing it — and secrets in none of them.',
        ['Move configuration out of code and keep secrets out of the repository'], 60),
      u('VERSIONS_AND_LOCKFILES', 'Versions, Ranges and Lockfiles',
        'Why a build that worked yesterday fails today, and what a lockfile is actually for.',
        ['Explain what a lockfile guarantees and what it does not'], 60, { after: ['CONFIG_OUT_OF_CODE'] }),
      u('TAKING_ON_A_DEPENDENCY', 'What a Library Commits You To',
        'Transitive dependencies, abandonment, licences and the security surface you just adopted.',
        ['Judge whether a dependency is worth taking on'], 60, { after: ['VERSIONS_AND_LOCKFILES'] }),
    ],
  },
  T3_COMPLEX_DEBUG: {
    category: 'UNIVERSAL',
    units: [
      u('EVIDENCE_NOT_GUESSING', 'From Evidence to Cause',
        'A system too large to hold in your head. Bisection, hypotheses and disproving your first idea.',
        ['Work from a symptom to a cause without changing things at random'], 75),
      u('READING_A_STACK_TRACE', 'Reading What the System Already Told You',
        'Stack traces, logs and metrics as a record of what happened, read properly.',
        ['Find the first thing that went wrong rather than the last thing that broke'],
        65, { after: ['EVIDENCE_NOT_GUESSING'] }),
      u('CANNOT_REPRODUCE', 'When It Only Happens in Production',
        'Timing, data, concurrency and environment — the four reasons it works on your machine.',
        ['Investigate a failure you cannot reproduce locally'], 75, { after: ['READING_A_STACK_TRACE'] }),
      ...closeOut('Complex Debugging', 'CANNOT_REPRODUCE'),
    ],
  },

  /* ── S03 · Advanced data structures ──────────────────────────────────────────────────── */
  T3_TREES_BST: {
    category: 'UNIVERSAL',
    units: [
      u('TREES', 'Trees, and Why They Keep Appearing',
        'Hierarchies, traversals, and the recursion that makes them natural to walk.',
        ['Implement and traverse a tree three ways'], 75),
      u('BST', 'Binary Search Trees',
        'Ordered data with cheap lookup — and what happens to that promise when it degenerates.',
        ['Say what a BST buys, and what it costs when unbalanced'], 75, { after: ['TREES'] }),
      u('BALANCING_IDEA', 'Why Balancing Exists',
        'The idea behind self-balancing trees, without implementing a red-black tree from memory.',
        ['Explain why balance matters and what a library is doing for you'], 60, { after: ['BST'] }),
      ...closeOut('Trees', 'BALANCING_IDEA'),
    ],
  },
  T3_HEAPS: {
    category: 'UNIVERSAL',
    units: [
      u('HEAP_SHAPE', 'Keeping the Next Item Cheap',
        'A heap is not sorted. It only promises the top, and that is exactly enough.',
        ['Explain the heap property and what it does and does not guarantee'], 70),
      u('PRIORITY_QUEUES', 'Priority Queues in Practice',
        'Schedulers, merges and top-k — the problems whose shape is a priority queue.',
        ['Recognise a problem a priority queue solves and use one'], 70, { after: ['HEAP_SHAPE'] }),
      ...closeOut('Heaps', 'PRIORITY_QUEUES'),
    ],
  },
  T3_GRAPHS: {
    category: 'UNIVERSAL',
    units: [
      u('REPRESENTING_GRAPHS', 'Two Ways to Hold a Graph',
        'Adjacency list against adjacency matrix, and letting the question decide.',
        ['Represent a graph two ways and say which fits the question'], 70),
      u('BFS', 'Breadth-First Search',
        'Level by level, and why that gives the shortest path when every edge costs the same.',
        ['Walk a graph breadth-first and say what question it answers'], 75, { after: ['REPRESENTING_GRAPHS'] }),
      u('DFS', 'Depth-First Search',
        'All the way down first — cycles, components and the recursion behind it.',
        ['Walk a graph depth-first and detect a cycle'], 75, { after: ['BFS'] }),
      u('MODELLING_AS_A_GRAPH', 'Seeing a Graph in a Problem That Is Not One',
        'Most graph problems do not mention graphs. Recognising the shape is the skill.',
        ['Model a worded problem as a graph'], 70, { after: ['DFS'] }),
      ...closeOut('Graphs', 'MODELLING_AS_A_GRAPH'),
    ],
  },
  T3_CHOOSING_STRUCTURES: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_THE_PROBLEM_DOES_MOST', 'Choosing by What the Problem Does Most',
        'Insert, look up, or iterate in order — the operation you do most decides the structure.',
        ['Argue a structure choice from the operations the problem performs'], 70),
      u('TRADE_OFFS', 'Memory Against Time, Honestly',
        'Hash maps, arrays and trees compared on the axes that actually differ.',
        ['State the trade-off a structure makes rather than naming it as best'], 65,
        { after: ['WHAT_THE_PROBLEM_DOES_MOST'] }),
      ...closeOut('Choosing a Structure', 'TRADE_OFFS'),
    ],
  },

  /* ── S04 · Advanced algorithms ───────────────────────────────────────────────────────── */
  T3_ALGO_DESIGN: {
    category: 'UNIVERSAL',
    units: [
      u('CONSTRAINTS_FIRST', 'Read the Constraints Before the Problem',
        'n up to a thousand and n up to a billion are different questions. The bound narrows the approach.',
        ['Let the constraints rule approaches out before writing any code'], 70),
      u('ARGUING_CORRECTNESS', 'Arguing That It Works',
        'Why the approach is right, said out loud, before the keyboard.',
        ['State why an approach is correct, not only that it passes'], 65, { after: ['CONSTRAINTS_FIRST'] }),
      ...closeOut('Algorithm Design', 'ARGUING_CORRECTNESS'),
    ],
  },
  T3_DIVIDE_CONQUER: {
    category: 'UNIVERSAL',
    units: [
      u('SPLIT_UNTIL_TRIVIAL', 'Split Until It Is Trivial',
        'The shape shared by merge sort, quick sort and binary search.',
        ['Recognise and apply the divide-and-conquer shape'], 75),
      u('THE_RECURRENCE', 'What It Cost',
        'Writing the recurrence, and reading the answer out of it without the master theorem by rote.',
        ['State and solve the recurrence for a divide-and-conquer algorithm'],
        70, { after: ['SPLIT_UNTIL_TRIVIAL'] }),
      ...closeOut('Divide and Conquer', 'THE_RECURRENCE'),
    ],
  },
  T3_GREEDY_DP: {
    category: 'UNIVERSAL',
    units: [
      u('WHEN_GREEDY_IS_SAFE', 'When a Greedy Choice Is Provably Safe',
        'Greedy is right surprisingly often and wrong silently. The exchange argument.',
        ['Tell when a greedy choice is safe and when it quietly is not'], 75),
      u('OVERLAPPING_SUBPROBLEMS', 'Seeing the Same Subproblem Twice',
        'The signal that says dynamic programming before you have written a table.',
        ['Recognise overlapping subproblems in a recursive solution'], 75,
        { after: ['WHEN_GREEDY_IS_SAFE'] }),
      u('RECURRENCE_THEN_TABLE', 'The Recurrence Comes First',
        'Memoisation, then the table. Writing the table first is why DP feels impossible.',
        ['Write the recurrence before the table and derive one from the other'], 80,
        { after: ['OVERLAPPING_SUBPROBLEMS'] }),
      ...closeOut('Greedy and DP', 'RECURRENCE_THEN_TABLE'),
    ],
  },
  T3_GRAPH_ALGORITHMS: {
    category: 'ENRICHMENT',
    units: [
      u('SHORTEST_PATH', 'Shortest Path With Weights',
        'Dijkstra, and why it needs non-negative edges to keep its promise.',
        ['Apply a shortest-path algorithm and state its precondition'], 80),
      u('TOPOLOGICAL_ORDER', 'Ordering Things With Dependencies',
        'Build systems, course prerequisites and task graphs — and detecting the cycle that breaks them.',
        ['Produce a topological order and detect when none exists'], 75, { after: ['SHORTEST_PATH'] }),
    ],
  },
  T3_TIMED_PRACTICE: {
    category: 'UNIVERSAL',
    units: [
      u('THINKING_ALOUD', 'Solving Out Loud',
        'The interviewer is assessing the reasoning. Narrating it while you work.',
        ['Work a problem while explaining the approach as you go'], 65),
      u('UNDER_THE_CLOCK', 'Working Under Time',
        'Timed problems, and what to do in the last five minutes when it is not finished.',
        ['Reach a correct answer under a clock, or a partial one you can defend'],
        75, { unitType: 'PRACTICE', after: ['THINKING_ALOUD'] }),
      u('CHECKPOINT', 'Algorithms Checkpoint',
        'The algorithmic core of the year, measured.',
        ['Show the algorithm work is in place'], 50, { unitType: 'CHECKPOINT', after: ['UNDER_THE_CLOCK'] }),
    ],
  },

  /* ── S05 · Software engineering ──────────────────────────────────────────────────────── */
  T3_ARCHITECTURE: {
    category: 'UNIVERSAL',
    units: [
      u('LAYERS', 'Layers, and What Each May Know',
        'Presentation, application, domain, data — and the dependency rule that keeps them apart.',
        ['Draw the layers of an application and say what each may know about'], 75),
      u('BOUNDARIES', 'Where to Put a Boundary',
        'A boundary is a promise about what can change independently. Choosing them.',
        ['Place a boundary and justify it against what is likely to change'], 70, { after: ['LAYERS'] }),
      u('SEPARATION_OF_CONCERNS', 'Separation of Concerns, Concretely',
        'What it means in a file rather than on a slide.',
        ['Split a file that is doing three jobs into three that do one each'], 70, { after: ['BOUNDARIES'] }),
      u('EXPENSIVE_TO_REVERSE', 'The Decisions That Are Expensive to Reverse',
        'Which architectural choices to labour over and which to make quickly and move on.',
        ['Tell a reversible decision from an expensive one'], 65, { after: ['SEPARATION_OF_CONCERNS'] }),
      ...closeOut('Architecture', 'EXPENSIVE_TO_REVERSE'),
    ],
  },
  T3_REFACTORING: {
    category: 'UNIVERSAL',
    units: [
      u('SMALL_STEPS_STAY_GREEN', 'Small Steps That Stay Green',
        'Refactoring is a sequence of changes that each keep the tests passing. Not a rewrite.',
        ['Change the shape of working code in steps that each stay green'], 75),
      u('COMMON_REFACTORINGS', 'The Refactorings Worth Knowing by Name',
        'Extract function, rename, introduce parameter object, replace conditional with polymorphism.',
        ['Apply the common refactorings deliberately'], 70, { after: ['SMALL_STEPS_STAY_GREEN'] }),
      u('TECHNICAL_DEBT', 'Naming the Cost of a Shortcut',
        'Debt taken deliberately and debt taken by accident. Saying which, and when to repay.',
        ['Name a shortcut as debt and decide when to pay it back'], 65, { after: ['COMMON_REFACTORINGS'] }),
      u('WHEN_NOT_TO', 'Code That Should Be Left Alone',
        'Working code nobody touches is not a problem. Refactoring is for code you are about to change.',
        ['Say when refactoring is not worth doing'], 55, { after: ['TECHNICAL_DEBT'] }),
      ...closeOut('Refactoring', 'WHEN_NOT_TO'),
    ],
  },
  T3_CODE_REVIEW_DEPTH: {
    category: 'UNIVERSAL',
    units: [
      u('UNDERSTAND_FIRST', 'Understand the Change Before Judging It',
        'A review that starts by hunting for something to say finds style and misses the business rule.',
        ['Read a change for what it is doing before commenting on how'], 60),
      u('WHAT_TO_LOOK_AT_FIRST', 'Correctness, Then Design, Then Names',
        'The order matters: a well-formatted wrong answer is still wrong.',
        ['Review in an order that catches the expensive problems first'], 60, { after: ['UNDERSTAND_FIRST'] }),
      u('WORDING_A_COMMENT', 'Wording It So It Gets Fixed',
        'Questions, weight, and the difference between blocking and suggesting.',
        ['Write a comment that gets acted on and keeps the author willing to send the next change'],
        65, { after: ['WHAT_TO_LOOK_AT_FIRST'] }),
      u('RECEIVING_REVIEW', 'Taking a Review Well',
        'Disagreeing usefully, and why silently complying is its own failure.',
        ['Answer a review comment you disagree with, without either caving or arguing'],
        55, { after: ['WORDING_A_COMMENT'] }),
    ],
  },
  T3_DOCUMENTATION: {
    category: 'UNIVERSAL',
    units: [
      u('WHY_NOT_WHAT', 'Write Down Why, Not What',
        'The code says what it does. Only a person can say why it was done that way.',
        ['Document a decision so the next engineer does not undo it by accident'], 60),
      u('DECISION_RECORDS', 'A Decision Record',
        'Context, the options, the choice and the consequences — short, and worth its length.',
        ['Write a decision record somebody could act on a year later'], 60, { after: ['WHY_NOT_WHAT'] }),
      u('README_THAT_WORKS', 'A README Somebody Can Follow',
        'What it is, how to run it, and how to run the tests. In that order.',
        ['Write a README a new engineer can start from'], 55, { after: ['DECISION_RECORDS'] }),
    ],
  },

  /* ── S06 · Testing, quality and reliability ──────────────────────────────────────────── */
  T3_TEST_DESIGN: {
    category: 'UNIVERSAL',
    units: [
      u('CHOOSING_THE_LEVEL', 'Unit, Integration or End to End',
        'Each catches a different failure and costs a different amount. Choosing deliberately.',
        ['Choose the level of test that fits what could go wrong'], 70),
      u('BOUNDARIES_AND_NEGATIVES', 'Boundaries and the Cases That Fail',
        'Empty, one, many, and wrong. Where the bugs are.',
        ['Write a negative test that would actually have caught the bug'], 70,
        { after: ['CHOOSING_THE_LEVEL'] }),
      u('ONE_REASON_TO_FAIL', 'A Test That Fails for One Reason',
        'A test asserting five things tells you almost nothing when it goes red.',
        ['Write tests that each fail for a single, nameable reason'], 65,
        { after: ['BOUNDARIES_AND_NEGATIVES'] }),
      ...closeOut('Test Design', 'ONE_REASON_TO_FAIL'),
    ],
  },
  T3_TEST_ISOLATION: {
    category: 'UNIVERSAL',
    units: [
      u('MOCKING_ENOUGH', 'Mocking Enough, and Not More',
        'Mock the boundary, not the logic. A test of mocks proves the mocks work.',
        ['Isolate the thing under test without mocking away what is being tested'], 70),
      u('FLAKY_TESTS', 'Flaky Tests Are a Bug',
        'Time, order, shared state and the network. Why a test that sometimes fails is worse than none.',
        ['Diagnose and fix a flaky test rather than rerunning it'], 70, { after: ['MOCKING_ENOUGH'] }),
    ],
  },
  T3_RELIABILITY: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_TO_LOG', 'What Is Worth Logging',
        'Enough to explain a failure, not so much that nobody can find it. Levels and structure.',
        ['Log what a diagnosis needs and leave out what it does not'], 65),
      u('KNOWING_IT_IS_UNWELL', 'Knowing Before a User Tells You',
        'The handful of signals that say a system is unhealthy, and what to do with them.',
        ['Say which signal would have caught a given failure first'], 70, { after: ['WHAT_TO_LOG'] }),
      u('CHECKPOINT', 'Testing and Reliability Checkpoint',
        'The quality layer of the year, measured.',
        ['Show the testing and reliability work is in place'], 50,
        { unitType: 'CHECKPOINT', after: ['KNOWING_IT_IS_UNWELL'] }),
    ],
  },

  /* ── S07 · Database engineering ──────────────────────────────────────────────────────── */
  T3_QUERY_PERF: {
    category: 'UNIVERSAL',
    units: [
      u('READING_A_PLAN', 'Reading a Query Plan',
        'What the database says it is about to do, and finding the scan that is costing you.',
        ['Read a query plan and identify the expensive step'], 75),
      u('INDEXES_FOR_A_REASON', 'Adding an Index for a Reason',
        'Which column, in which order, and what it costs on every write.',
        ['Add an index that helps a specific query, and state its cost'], 75,
        { after: ['READING_A_PLAN'] }),
      u('MEASURING_THE_FIX', 'Proving the Change Helped',
        'Before and after on real data, because the plan changing is not the same as being faster.',
        ['Prove a query optimisation with a measurement'], 65, { after: ['INDEXES_FOR_A_REASON'] }),
      ...closeOut('Query Performance', 'MEASURING_THE_FIX'),
    ],
  },
  T3_TRANSACTIONS_INTEGRITY: {
    category: 'UNIVERSAL',
    units: [
      u('TWO_THINGS_AT_ONCE', 'When Two Things Happen at Once',
        'Lost updates, dirty reads, and the isolation levels that decide which you tolerate.',
        ['Keep data correct when two requests arrive together'], 80),
      u('LET_THE_DATABASE_ENFORCE', 'Let the Database Enforce What It Can',
        'Constraints are cheaper and more reliable than checks in application code.',
        ['Move a rule into a constraint where it belongs'], 65, { after: ['TWO_THINGS_AT_ONCE'] }),
      u('DEADLOCKS', 'Deadlocks and Long Transactions',
        'Why a transaction held open is a problem for everybody else.',
        ['Diagnose a deadlock and say what ordering would prevent it'], 70,
        { after: ['LET_THE_DATABASE_ENFORCE'] }),
      ...closeOut('Transactions', 'DEADLOCKS'),
    ],
  },
  T3_CACHING_NOSQL: {
    category: 'ENRICHMENT',
    units: [
      u('WHAT_IS_SAFE_TO_CACHE', 'What Is Safe to Cache',
        'Read-heavy, slow to compute, and tolerant of being slightly stale. Not everything qualifies.',
        ['Decide what to cache and for how long'], 70),
      u('INVALIDATION', 'Invalidation Is the Hard Half',
        'How a cache goes wrong, and the strategies that keep it honest.',
        ['Say how a cached value becomes wrong and how you would prevent it'], 70,
        { after: ['WHAT_IS_SAFE_TO_CACHE'] }),
      u('NOSQL_TRADEOFFS', 'What a Document Store Gives Up',
        'Schema flexibility bought with joins and consistency. When relational is still right.',
        ['Say what a NoSQL store trades away, and when that trade is worth it'], 70,
        { after: ['INVALIDATION'] }),
    ],
  },

  /* ── S08 · Web and API engineering ───────────────────────────────────────────────────── */
  T3_API_DESIGN: {
    category: 'UNIVERSAL',
    units: [
      u('RESOURCES_AND_SHAPES', 'Resources, and the Shapes They Return',
        'Naming things, nesting, and the response a caller actually wants.',
        ['Design a resource and its representation for a real use case'], 70),
      u('VERSIONING', 'Changing an API Without Breaking Callers',
        'Additive change, versioning, and deprecation that gives people time.',
        ['Make a breaking change safely'], 70, { after: ['RESOURCES_AND_SHAPES'] }),
      u('PAGINATION_AND_FILTERING', 'Pagination, Filtering and Sorting',
        'The three things every list endpoint needs, and the offset trap at scale.',
        ['Implement pagination that still works at a million rows'], 70, { after: ['VERSIONING'] }),
      u('ERRORS_A_CALLER_CAN_ACT_ON', 'Errors a Caller Can Act On',
        'Status codes used properly, and a body that says what to do about it.',
        ['Return an error a caller can handle without guessing'], 60,
        { after: ['PAGINATION_AND_FILTERING'] }),
      ...closeOut('API Design', 'ERRORS_A_CALLER_CAN_ACT_ON'),
    ],
  },
  T3_AUTH: {
    category: 'UNIVERSAL',
    units: [
      u('SESSIONS_AND_TOKENS', 'Sessions and Tokens',
        'Two ways to remember who is calling, what each costs, and where each is kept.',
        ['Choose between a session and a token, and say why'], 75),
      u('EXPIRY_AND_REFRESH', 'Expiry, Refresh and Revocation',
        'A credential that never expires is a credential you can never take back.',
        ['Expire and refresh a credential, and revoke one that leaked'], 70,
        { after: ['SESSIONS_AND_TOKENS'] }),
      u('AUTHORIZATION', 'What a Proven Caller May Do',
        'The check that is missed most often, and where it has to live to be reliable.',
        ['Check authorization on every request, not only at the door'], 75,
        { after: ['EXPIRY_AND_REFRESH'] }),
      u('BROKEN_ACCESS_CONTROL', 'Changing the Id in the URL',
        'The simplest real attack there is, and the check that stops it.',
        ['Find and fix a broken access check'], 70, { after: ['AUTHORIZATION'] }),
      ...closeOut('Authentication and Authorization', 'BROKEN_ACCESS_CONTROL'),
    ],
  },
  T3_API_HARDENING: {
    category: 'UNIVERSAL',
    units: [
      u('VALIDATE_AT_THE_BOUNDARY', 'Validate Everything at the Boundary',
        'Never trust a request. Where validation belongs and what it must reject.',
        ['Validate a request at the boundary and reject what does not belong'], 65),
      u('RATE_LIMITING', 'Rate Limiting and Abuse',
        'Protecting a service from one caller, deliberate or not.',
        ['Apply a rate limit and say what it protects'], 60, { after: ['VALIDATE_AT_THE_BOUNDARY'] }),
      u('DOCUMENTING_AN_API', 'Documentation Somebody Can Call From',
        'Endpoints, shapes, errors and an example that works.',
        ['Document an API so another engineer can use it without asking'], 60, { after: ['RATE_LIMITING'] }),
    ],
  },

  /* ── S09 · Linux, cloud and infrastructure ───────────────────────────────────────────── */
  T3_LINUX: {
    category: 'UNIVERSAL',
    units: [
      u('PROCESSES_AND_SERVICES', 'Processes, Services and Ports',
        'What is running, what is listening, and how to ask.',
        ['Find what is running and what is listening on a remote machine'], 70),
      u('SSH_AND_PERMISSIONS', 'SSH, Users and Permissions',
        'Getting on a machine safely, and why the application does not run as root.',
        ['Connect to a machine and reason about what its user may do'], 65,
        { after: ['PROCESSES_AND_SERVICES'] }),
      u('LOGS_ON_A_SERVER', 'Finding the Log',
        'Where logs live, how to follow one, and how to search a large one.',
        ['Find and read the log for a failing service'], 60, { after: ['SSH_AND_PERMISSIONS'] }),
      ...closeOut('Linux for Engineers', 'LOGS_ON_A_SERVER'),
    ],
  },
  T3_CONTAINERS: {
    category: 'UNIVERSAL',
    units: [
      u('WHY_CONTAINERS', 'Why It Works on Your Machine',
        'The problem containers solve, stated before the commands.',
        ['Explain what a container packages and what it does not'], 60),
      u('BUILDING_AN_IMAGE', 'Building an Image',
        'A Dockerfile that is small, cached well, and does not ship your secrets.',
        ['Build an image for a real application'], 80, { after: ['WHY_CONTAINERS'] }),
      u('RUNNING_AND_DEBUGGING', 'Running It, and When It Will Not Start',
        'Ports, volumes, environment, and reading the logs of something that exited immediately.',
        ['Run a container and debug one that fails to start'], 75, { after: ['BUILDING_AN_IMAGE'] }),
      ...closeOut('Containers', 'RUNNING_AND_DEBUGGING'),
    ],
  },
  T3_DEPLOYMENT: {
    category: 'UNIVERSAL',
    units: [
      u('A_PIPELINE_NOT_A_PERSON', 'A Pipeline, Not a Person Remembering',
        'Build, test, deploy — the same way every time, triggered by a merge.',
        ['Describe a pipeline that builds, tests and deploys without manual steps'], 75),
      u('ENVIRONMENTS', 'Three Environments, One Build',
        'Development, staging and production differing only in configuration.',
        ['Run the same build in three environments without editing it'], 65,
        { after: ['A_PIPELINE_NOT_A_PERSON'] }),
      u('ROLLING_BACK', 'Getting It Back Off Again',
        'The half of deployment nobody practises until they need it, including the data.',
        ['Roll back a bad deployment without losing data'], 70, { after: ['ENVIRONMENTS'] }),
      ...closeOut('Deployment', 'ROLLING_BACK'),
    ],
  },

  /* ── S10 · Security engineering ──────────────────────────────────────────────────────── */
  T3_THREAT_MODELING: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_AN_ATTACKER_WANTS', 'What an Attacker Actually Wants',
        'Data, money, access or disruption. Naming it changes what you defend.',
        ['State what an attacker would want from a given system'], 65),
      u('WHERE_IT_WOULD_LET_THEM', 'Where the System Would Let Them',
        'Entry points, trust boundaries and the assumptions each one makes.',
        ['Map the entry points of a system and the trust each assumes'], 75,
        { after: ['WHAT_AN_ATTACKER_WANTS'] }),
      u('RANKING_RISK', 'What to Fix First',
        'Likelihood against impact, so limited time goes where it matters.',
        ['Rank findings so the first fix is the right one'], 60, { after: ['WHERE_IT_WOULD_LET_THEM'] }),
      ...closeOut('Threat Modelling', 'RANKING_RISK'),
    ],
  },
  T3_WEB_SECURITY: {
    category: 'UNIVERSAL',
    units: [
      u('INJECTION', 'Injection',
        'Data treated as instructions. SQL and otherwise, and the one habit that prevents it.',
        ['Find and fix an injection, and explain why parameterisation works'], 75),
      u('XSS', 'Cross-Site Scripting',
        'Somebody else’s script in your page, and output encoding as the real defence.',
        ['Find and fix an XSS, and say where encoding belongs'], 75, { after: ['INJECTION'] }),
      u('CSRF', 'Cross-Site Request Forgery',
        'A request the user did not mean to make, and why being logged in is the problem.',
        ['Explain and prevent a CSRF'], 65, { after: ['XSS'] }),
      ...closeOut('Web Security', 'CSRF'),
    ],
  },
  T3_SECURE_CODING: {
    category: 'UNIVERSAL',
    units: [
      u('SECRETS', 'Secrets Do Not Go in the Repository',
        'Where they go instead, and what to do the day one is committed by accident.',
        ['Keep secrets out of a repository, and rotate one that leaked'], 65),
      u('DEPENDENCY_SECURITY', 'What an Outdated Dependency Exposes',
        'Known vulnerabilities, transitive risk, and keeping up without breaking everything.',
        ['Audit dependencies and judge which update is urgent'], 65, { after: ['SECRETS'] }),
      u('CHECKPOINT', 'Security Engineering Checkpoint',
        'The security layer of the year, measured.',
        ['Show the security work is in place'], 50,
        { unitType: 'CHECKPOINT', after: ['DEPENDENCY_SECURITY'] }),
    ],
  },
};
