import { LearningUnitType, LearningUnitCategory } from '../../models/CurriculumLearningUnit';

/**
 * The Year-1 mega curriculum, as a dataset.
 *
 * ── WHAT THIS IS ──────────────────────────────────────────────────────────────────────────
 *
 * Thirty-nine broad curriculum topics decomposed into the units they actually teach. It is DATA,
 * not a migration: nothing here runs, and importing it is a separate deliberate act that can be
 * validated first and re-run safely.
 *
 * ── WHY DECOMPOSITION IS THE WHOLE JOB ────────────────────────────────────────────────────
 *
 * "Object-Oriented Programming" is a good topic and a hopeless day. While the topic was the
 * smallest node, thirty-nine topics could only produce thirty-nine sessions, and a student who
 * bought ninety days opened a twenty-eight-day plan. The fix is not a longer calendar, it is a
 * finer unit.
 *
 * SO NO UNIT IS NAMED "BASICS". A unit called "Python Basics" is the same failure one level down:
 * it hides four lessons behind one title and nothing can schedule it sensibly. Every unit here is
 * one sitting's worth of one idea, and the validator refuses the dataset if a placeholder name
 * creeps back in.
 *
 * ── WHAT IT DELIBERATELY DOES NOT CONTAIN ─────────────────────────────────────────────────
 *
 * No day numbers. A unit belongs to the master curriculum; which day a student meets it is
 * decided per student, later, by the composer. There are more units here than any ninety-day plan
 * can hold, and that is the point: a pool larger than the plan is what makes selection possible.
 *
 * ── SOURCE MATERIAL ───────────────────────────────────────────────────────────────────────
 *
 * Module codes, topic codes, skill keys, prerequisite skills, directions and default depth come
 * from the Year-1 curriculum itself and are INHERITED rather than restated — a unit that retyped
 * its topic's skills would drift the moment the curriculum was edited. Only what is genuinely
 * per-unit lives here: the sequence, the titles, the outcomes and the shape of the work.
 */

export interface UnitSeed {
  /** Appended to the topic code to make the unit code. Stable; renaming the title never moves it. */
  slug: string;
  title: string;
  description: string;
  learningOutcomes: string[];
  estimatedMinutes: number;
  unitType?: LearningUnitType;
  /** Sibling slugs that must be taught first. Resolved to full unit codes on import. */
  after?: string[];
  /** Narrows the topic's skills. Omitted means the unit teaches all of them. */
  skillKeys?: string[];
}

export interface TopicSeed {
  category: LearningUnitCategory;
  units: UnitSeed[];
}

/** Compact constructor, so the dataset below reads as a syllabus rather than as JSON. */
const u = (
  slug: string, title: string, description: string,
  learningOutcomes: string[], estimatedMinutes: number,
  extra: Partial<UnitSeed> = {},
): UnitSeed => ({ slug, title, description, learningOutcomes, estimatedMinutes, ...extra });

/** A topic's last three units, in the shape every topic ends with. */
const debugPractiseBuild = (
  what: string, debugMin = 45, practiceMin = 60, projectMin = 120,
): UnitSeed[] => [
  u('DEBUGGING', `Debugging ${what}`,
    `Reading the errors ${what.toLowerCase()} produces, and finding the cause rather than guessing.`,
    [`Diagnose a broken ${what.toLowerCase()} example without changing it at random`],
    debugMin, { unitType: 'DEBUG', after: [] }),
  u('PRACTICE', `${what} Practice`,
    `Enough repetition that ${what.toLowerCase()} stops needing thought.`,
    [`Work ${what.toLowerCase()} problems without looking things up`],
    practiceMin, { unitType: 'PRACTICE', after: ['DEBUGGING'] }),
  u('MINI_PROJECT', `Mini Project — ${what}`,
    'One small thing built end to end, and explained afterwards.',
    ['Build and describe something that uses what this topic taught'],
    projectMin, { unitType: 'PROJECT', after: ['PRACTICE'] }),
];

export const YEAR1: Record<string, TopicSeed> = {

  /* ── M01 · Computer Science Fundamentals ──────────────────────────────────────────── */

  T_HARDWARE: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_IS_A_COMPUTER', 'What a Computer Actually Is',
        'Input, processing, output and storage — the four things every machine does, from a phone to a server.',
        ['Name the four stages and place a real device against each'], 30),
      u('CPU', 'The CPU and the Fetch-Execute Cycle',
        'What a processor does, one instruction at a time, and why clock speed is not the whole story.',
        ['Describe the fetch-execute cycle in your own words'], 40, { after: ['WHAT_IS_A_COMPUTER'] }),
      u('MEMORY_HIERARCHY', 'Memory, and Why There Are Several Kinds',
        'Registers, cache, RAM and disk — each slower, larger and cheaper than the last.',
        ['Explain why a program runs faster the second time'], 40, { after: ['CPU'] }),
      u('STORAGE', 'Storage and Persistence',
        'What survives a power cut and what does not, and why that distinction shapes every program.',
        ['Say which data is lost when a machine is switched off'], 35, { after: ['MEMORY_HIERARCHY'] }),
      u('OS_ROLE', 'What the Operating System Is For',
        'The layer between your program and the hardware, and why nothing talks to the disk directly.',
        ['Describe one thing the OS does on your behalf every second'], 35, { after: ['STORAGE'] }),
      u('BINARY_REPRESENTATION', 'How a Machine Stores Anything At All',
        'Text, numbers, colour and sound, all as the same two symbols.',
        ['Explain how a letter becomes a number becomes a voltage'], 40, { after: ['WHAT_IS_A_COMPUTER'] }),
      u('COMPILE_VS_RUN', 'From Source Code to a Running Program',
        'What happens between saving a file and seeing output — compiling, interpreting, and the difference.',
        ['Say what a compiler produces and what an interpreter does instead'], 45, { after: ['OS_ROLE'] }),
      u('PRACTICE', 'Hardware Practice',
        'Trace what happens inside a machine for a handful of everyday actions.',
        ['Walk through opening a file, end to end'], 45, { unitType: 'PRACTICE', after: ['COMPILE_VS_RUN', 'BINARY_REPRESENTATION'] }),
    ],
  },

  T_FILES: {
    category: 'UNIVERSAL',
    units: [
      u('FILESYSTEM_SHAPE', 'How Files Are Organised',
        'Directories as a tree, and what a path actually names.',
        ['Draw the tree from root to a file you own'], 35),
      u('PATHS', 'Absolute and Relative Paths',
        'Where you are, where a thing is, and how to say the second from the first.',
        ['Reach any file two ways: absolutely and relatively'], 40, { after: ['FILESYSTEM_SHAPE'] }),
      u('NAVIGATION', 'Moving Around from the Command Line',
        'pwd, ls, cd — orienting yourself without a window to look at.',
        ['Navigate to any directory without a file manager'], 40, { after: ['PATHS'] }),
      u('FILE_OPERATIONS', 'Creating, Copying, Moving, Deleting',
        'The four operations, and which of them cannot be undone.',
        ['Perform each safely, and say which one has no undo'], 45, { after: ['NAVIGATION'] }),
      u('VIEWING_FILES', 'Reading a File Without Opening It',
        'cat, head, tail and less — and when each is the right one.',
        ['Read the last twenty lines of a large log'], 35, { after: ['FILE_OPERATIONS'] }),
      u('PERMISSIONS', 'Permissions and Ownership',
        'Read, write, execute — for the owner, the group and everyone else.',
        ['Read a permission string and say who can do what'], 50, { after: ['FILE_OPERATIONS'] }),
      u('HIDDEN_AND_CONFIG', 'Hidden Files and Configuration',
        'Why some files start with a dot, and what usually lives in them.',
        ['Find and read a configuration file in your home directory'], 30, { after: ['VIEWING_FILES'] }),
      u('PRACTICE', 'Command Line Practice',
        'Real tasks done only from the shell, until the window stops being missed.',
        ['Complete a file-organising task without a graphical tool'], 60,
        { unitType: 'PRACTICE', after: ['PERMISSIONS', 'HIDDEN_AND_CONFIG'] }),
    ],
  },

  /* ── M02 · Computational Thinking ─────────────────────────────────────────────────── */

  T_DECOMPOSITION: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_IS_A_PROBLEM', 'Understanding the Problem First',
        'Restating a problem in your own words before touching anything.',
        ['Restate a problem so somebody else agrees you have it right'], 35),
      u('BREAKING_DOWN', 'Breaking a Problem Into Parts',
        'Splitting one hard thing into several easy ones, and knowing when to stop.',
        ['Decompose a task into steps small enough to start'], 45, { after: ['WHAT_IS_A_PROBLEM'] }),
      u('PATTERNS', 'Noticing What Repeats',
        'Recognising that you have solved this shape of problem before.',
        ['Spot the repeated structure in three similar problems'], 40, { after: ['BREAKING_DOWN'] }),
      u('ABSTRACTION', 'Ignoring What Does Not Matter',
        'Deciding which details are essential and which are noise.',
        ['Strip a problem statement down to what actually matters'], 40, { after: ['PATTERNS'] }),
      u('ALGORITHM_IDEA', 'What an Algorithm Is',
        'A sequence of unambiguous steps that finishes — and why each of those words is load-bearing.',
        ['Write a set of steps somebody else can follow exactly'], 45, { after: ['ABSTRACTION'] }),
      u('EDGE_CASES', 'Thinking About What Could Go Wrong',
        'Empty input, one item, enormous input, and the case nobody thought of.',
        ['List the edge cases of a simple problem before coding it'], 45, { after: ['ALGORITHM_IDEA'] }),
      u('PRACTICE', 'Problem Solving Practice',
        'Unfamiliar problems, decomposed on paper before any code is written.',
        ['Decompose a problem you have never seen'], 60, { unitType: 'PRACTICE', after: ['EDGE_CASES'] }),
    ],
  },

  T_PSEUDOCODE: {
    category: 'UNIVERSAL',
    units: [
      u('WHY_PSEUDOCODE', 'Planning Before Coding',
        'Why writing the plan in plain language catches mistakes that code hides.',
        ['Explain what pseudocode is for'], 30),
      u('WRITING_PSEUDOCODE', 'Writing Pseudocode',
        'Sequence, decision and repetition, written so any language could implement it.',
        ['Write pseudocode for a task with a decision and a loop'], 45, { after: ['WHY_PSEUDOCODE'] }),
      u('FLOWCHARTS', 'Flowcharts',
        'The same logic as a picture, and when a diagram beats a list.',
        ['Draw a flowchart with a branch and a loop'], 40, { after: ['WRITING_PSEUDOCODE'] }),
      u('DRY_RUNNING', 'Dry Running by Hand',
        'Walking through your own logic with a table of values, before a machine does.',
        ['Trace a piece of logic by hand and predict its output'], 50, { after: ['FLOWCHARTS'] }),
      u('FINDING_LOGIC_ERRORS', 'Finding Errors Before They Are Code',
        'Most bugs are in the plan. Dry running is how they are caught cheaply.',
        ['Find the fault in a plan by tracing it'], 45, { unitType: 'DEBUG', after: ['DRY_RUNNING'] }),
      u('PRACTICE', 'Pseudocode Practice',
        'Plan and trace several problems, without writing any code at all.',
        ['Plan and verify a solution on paper'], 60, { unitType: 'PRACTICE', after: ['FINDING_LOGIC_ERRORS'] }),
    ],
  },

  /* ── M03 · Programming Fundamentals ───────────────────────────────────────────────── */

  T_VARIABLES: {
    category: 'UNIVERSAL',
    units: [
      u('FIRST_PROGRAM', 'Your First Program',
        'Writing, saving and running something that prints — and understanding every part of it.',
        ['Run a program you wrote from a file'], 35),
      u('VARIABLES', 'Variables and Assignment',
        'Naming a value so you can use it later, and what the equals sign really does.',
        ['Store, change and read back a value'], 40, { after: ['FIRST_PROGRAM'] }),
      u('NUMBERS', 'Numbers and Arithmetic',
        'Integers and decimals, the operators, and the surprises of integer division.',
        ['Predict the result of mixed-type arithmetic'], 40, { after: ['VARIABLES'] }),
      u('STRINGS', 'Strings',
        'Text as data: creating, joining and reading characters out of it.',
        ['Build a message from several pieces'], 45, { after: ['VARIABLES'] }),
      u('STRING_METHODS', 'Working With Text',
        'Slicing, searching, splitting, changing case — the operations you will use daily.',
        ['Extract a part of a string by position and by search'], 50, { after: ['STRINGS'] }),
      u('BOOLEANS', 'True, False, and Comparison',
        'Booleans as first-class values, and the comparison operators that produce them.',
        ['Predict the truth value of a comparison'], 35, { after: ['NUMBERS'] }),
      u('TYPES', 'Types, and Why They Matter',
        'What a type is, how to check one, and what goes wrong when they are mixed.',
        ['Explain a type error in your own words'], 45, { after: ['BOOLEANS', 'STRING_METHODS'] }),
      u('INPUT_OUTPUT', 'Input and Output',
        'Reading from the person using your program, and why all input arrives as text.',
        ['Read a number from input and use it as a number'], 40, { after: ['TYPES'] }),
      u('NAMING', 'Naming Things Well',
        'Why a good name is the cheapest documentation you will ever write.',
        ['Rename a badly named program so it explains itself'], 30, { after: ['VARIABLES'] }),
      ...debugPractiseBuild('Variables', 45, 60, 90),
    ],
  },

  T_CONDITIONS: {
    category: 'UNIVERSAL',
    units: [
      u('IF', 'if',
        'Doing something only when a condition holds.',
        ['Write a program that behaves differently for different input'], 40),
      u('ELSE', 'else and elif',
        'Choosing between alternatives, and why order matters in a chain.',
        ['Write a chain of conditions that cannot all be true'], 40, { after: ['IF'] }),
      u('BOOLEAN_OPERATORS', 'and, or, not',
        'Combining conditions, and the traps of combining them carelessly.',
        ['Combine two conditions correctly'], 45, { after: ['ELSE'] }),
      u('NESTING', 'Conditions Inside Conditions',
        'Nesting, and when a nested condition should have been a combined one.',
        ['Flatten a needlessly nested condition'], 40, { after: ['BOOLEAN_OPERATORS'] }),
      u('TRUTHINESS', 'What Counts as True',
        'Empty strings, zero, and empty collections — the values that are false without being False.',
        ['Predict whether a non-boolean value passes a condition'], 35, { after: ['BOOLEAN_OPERATORS'] }),
      ...debugPractiseBuild('Conditions', 45, 60, 90),
    ],
  },

  T_LOOPS: {
    category: 'UNIVERSAL',
    units: [
      u('WHY_LOOPS', 'Why Repetition Needs a Structure',
        'The same work, many times, without writing it many times.',
        ['Identify repetition in a problem'], 30),
      u('FOR_LOOPS', 'for Loops',
        'Repeating once per item, over a range and over a collection.',
        ['Loop over a collection and over a count'], 45, { after: ['WHY_LOOPS'] }),
      u('WHILE_LOOPS', 'while Loops',
        'Repeating until something changes, and taking responsibility for making it change.',
        ['Write a loop that ends'], 45, { after: ['FOR_LOOPS'] }),
      u('LOOP_CONTROL', 'break and continue',
        'Leaving early, skipping an iteration, and why both should be rare.',
        ['Exit a loop early for a good reason'], 40, { after: ['WHILE_LOOPS'] }),
      u('ACCUMULATORS', 'Building a Result as You Go',
        'Counting, totalling and collecting — the pattern behind most loops you will write.',
        ['Total and count in one pass'], 45, { after: ['FOR_LOOPS'] }),
      u('NESTED_LOOPS', 'Loops Inside Loops',
        'Grids, pairs and tables — and the cost of doing it twice over.',
        ['Produce a grid with nested loops'], 50, { after: ['ACCUMULATORS'] }),
      u('INFINITE_LOOPS', 'Loops That Never End',
        'The three ways a loop fails to terminate, and how to spot each.',
        ['Fix a loop that never ends'], 40, { unitType: 'DEBUG', after: ['LOOP_CONTROL'] }),
      u('PRACTICE', 'Loops Practice',
        'Enough loop problems that the pattern stops needing thought.',
        ['Solve loop problems without a template'], 60, { unitType: 'PRACTICE', after: ['NESTED_LOOPS', 'INFINITE_LOOPS'] }),
      u('MINI_PROJECT', 'Mini Project — something that repeats',
        'A small program whose whole job is repetition done well.',
        ['Build and explain a program driven by a loop'], 90, { unitType: 'PROJECT', after: ['PRACTICE'] }),
    ],
  },

  T_FUNCTIONS: {
    category: 'UNIVERSAL',
    units: [
      u('WHY_FUNCTIONS', 'Why Functions Exist',
        'Naming a piece of work so it can be reused, tested and understood separately.',
        ['Say what a function buys you beyond saving typing'], 35),
      u('DEFINING', 'Defining and Calling',
        'Writing a function, calling it, and the difference between the two.',
        ['Write and call a function of your own'], 40, { after: ['WHY_FUNCTIONS'] }),
      u('PARAMETERS', 'Parameters and Arguments',
        'Passing values in, and the difference between the name and the thing.',
        ['Write a function that behaves differently per argument'], 45, { after: ['DEFINING'] }),
      u('RETURN', 'Returning a Value',
        'Sending an answer back, and why printing is not returning.',
        ['Explain the difference between print and return'], 45, { after: ['PARAMETERS'] }),
      u('DEFAULTS', 'Default and Named Arguments',
        'Sensible defaults, and calling by name when the order stops being obvious.',
        ['Give a parameter a default and override it'], 40, { after: ['RETURN'] }),
      u('SCOPE', 'Scope — Where a Name Lives',
        'Local and global, and why a variable inside a function is invisible outside it.',
        ['Predict which variable a name refers to'], 50, { after: ['RETURN'] }),
      u('COMPOSITION', 'Functions Calling Functions',
        'Building larger behaviour from smaller pieces that each do one thing.',
        ['Solve a problem with three small functions rather than one large one'], 50, { after: ['SCOPE'] }),
      u('DOCSTRINGS', 'Saying What a Function Does',
        'A sentence at the top that saves the next reader from reading the body.',
        ['Document a function so its body need not be read'], 30, { after: ['COMPOSITION'] }),
      ...debugPractiseBuild('Functions', 45, 60, 120),
    ],
  },

  /* ── M04 · Developer Tools ────────────────────────────────────────────────────────── */

  T_GIT: {
    category: 'UNIVERSAL',
    units: [
      u('WHY_VERSION_CONTROL', 'Why Version Control Exists',
        'The problem that folders named final-v2-REAL do not solve.',
        ['Say what version control gives you that copies do not'], 30),
      u('REPO_AND_COMMIT', 'Repositories and Commits',
        'Starting a repository, staging, and making your first commit.',
        ['Initialise a repository and commit a change'], 45, { after: ['WHY_VERSION_CONTROL'] }),
      u('STATUS_AND_DIFF', 'Seeing What Changed',
        'status, diff and log — knowing the state of things before you act.',
        ['Describe your working tree without guessing'], 40, { after: ['REPO_AND_COMMIT'] }),
      u('COMMIT_MESSAGES', 'Writing a Commit Message',
        'Saying why, not what — because the diff already says what.',
        ['Write a message that helps somebody six months later'], 30, { after: ['REPO_AND_COMMIT'] }),
      u('UNDOING', 'Undoing Things',
        'Unstaging, discarding and amending, and which of them destroys work.',
        ['Recover from a mistaken change safely'], 50, { after: ['STATUS_AND_DIFF'] }),
      u('BRANCHES', 'Branches',
        'Working on something without disturbing what already works.',
        ['Create a branch, work on it, and switch back'], 50, { after: ['UNDOING'] }),
      u('MERGING', 'Merging',
        'Bringing work back together, and what a merge actually does.',
        ['Merge a branch and explain the result'], 50, { after: ['BRANCHES'] }),
      u('CONFLICTS', 'Merge Conflicts',
        'Why they happen, what the markers mean, and resolving one without panic.',
        ['Resolve a conflict deliberately'], 50, { unitType: 'DEBUG', after: ['MERGING'] }),
      u('REMOTES', 'GitHub and Remotes',
        'Pushing, pulling, and the difference between your copy and the shared one.',
        ['Publish a repository and pull a change back'], 50, { after: ['MERGING'] }),
      u('PRACTICE', 'Git Practice',
        'A full cycle, several times, including the parts that go wrong.',
        ['Take a change from branch to merged, unaided'], 60, { unitType: 'PRACTICE', after: ['CONFLICTS', 'REMOTES'] }),
    ],
  },

  T_EDITOR: {
    category: 'UNIVERSAL',
    units: [
      u('CHOOSING_EDITOR', 'Setting Up an Editor',
        'Installing one, and the handful of settings worth changing on day one.',
        ['Have a working editor you did not have before'], 30),
      u('NAVIGATION', 'Moving Around a Codebase',
        'Jumping to a file, a symbol, a line — without scrolling.',
        ['Find any definition in under five seconds'], 40, { after: ['CHOOSING_EDITOR'] }),
      u('SEARCH', 'Finding Things',
        'Searching a project properly, including what a regular search misses.',
        ['Find every use of a name across a project'], 35, { after: ['NAVIGATION'] }),
      u('RUNNING_AND_DEBUGGING', 'Running and Stepping Through Code',
        'Breakpoints, stepping and watching values — instead of scattering print statements.',
        ['Find a bug with a debugger rather than by printing'], 55,
        { unitType: 'DEBUG', after: ['SEARCH'] }),
      u('EXTENSIONS', 'Extensions Worth Having',
        'Formatting, linting and language support, and the cost of installing forty of them.',
        ['Set up formatting that runs on save'], 35, { after: ['CHOOSING_EDITOR'] }),
      u('SHORTCUTS', 'Keyboard Over Mouse',
        'The ten shortcuts that pay for themselves in a week.',
        ['Complete an edit without touching the mouse'], 30, { after: ['NAVIGATION'] }),
    ],
  },

  /* ── M05 · Web Fundamentals (direction: WEB_DEVELOPMENT) ──────────────────────────── */

  T_HTML: {
    category: 'DIRECTION',
    units: [
      u('INTRO', 'Introduction to HTML',
        'What HTML is, what a browser does with it, and why it is not a programming language.',
        ['Say what HTML describes', 'Open a page you wrote in a browser'], 35),
      u('DOCUMENT_STRUCTURE', 'Document Structure',
        'doctype, html, head and body — the skeleton every page shares.',
        ['Write a valid empty page from memory'], 40, { after: ['INTRO'] }),
      u('TEXT_AND_HEADINGS', 'Text and Headings',
        'Headings, paragraphs and emphasis, and why heading level is meaning rather than size.',
        ['Mark up an article with a correct heading hierarchy'], 45, { after: ['DOCUMENT_STRUCTURE'] }),
      u('LINKS', 'Links',
        'Anchors, relative and absolute paths, and linking within a page.',
        ['Link between your own pages'], 40, { after: ['TEXT_AND_HEADINGS'] }),
      u('IMAGES', 'Images',
        'Embedding images, sizing them, and writing alt text worth reading.',
        ['Embed an image with meaningful alt text'], 40, { after: ['LINKS'] }),
      u('LISTS', 'Lists',
        'Ordered, unordered and description lists, and nesting without losing the thread.',
        ['Choose the right list type for a set of items'], 35, { after: ['TEXT_AND_HEADINGS'] }),
      u('TABLES', 'Tables',
        'Rows, cells and headers — for data, and not for layout.',
        ['Mark up a data table with proper headers'], 45, { after: ['LISTS'] }),
      u('FORMS', 'Forms',
        'Inputs, labels, and what actually happens when a form is submitted.',
        ['Build a form where every input has a label'], 60, { after: ['LINKS'] }),
      u('SEMANTIC_HTML', 'Semantic HTML',
        'header, nav, main, article, footer — describing what a thing is rather than how it looks.',
        ['Replace a page of divs with semantic elements'], 50, { after: ['FORMS', 'TABLES'] }),
      u('ACCESSIBILITY', 'Accessibility',
        'Reading a page the way a screen reader does, and the habits that make it work.',
        ['Navigate your own page by keyboard alone'], 50, { after: ['SEMANTIC_HTML'] }),
      u('PRACTICE', 'HTML Practice',
        'Mark up real pages from a description, until structure is automatic.',
        ['Produce correct markup without looking things up'], 60, { unitType: 'PRACTICE', after: ['ACCESSIBILITY'] }),
      u('MINI_PROJECT', 'Mini Project — a page of your own',
        'One complete page, built from a brief and explained afterwards.',
        ['Build and describe a complete semantic page'], 120, { unitType: 'PROJECT', after: ['PRACTICE'] }),
    ],
  },

  T_CSS: {
    category: 'DIRECTION',
    units: [
      u('WHAT_CSS_DOES', 'What CSS Is For',
        'Separating how a page looks from what it says, and why that separation matters.',
        ['Apply a stylesheet to an existing page'], 35),
      u('SELECTORS', 'Selectors',
        'Element, class and id — naming the things you want to style.',
        ['Style exactly the elements you intend to'], 45, { after: ['WHAT_CSS_DOES'] }),
      u('CASCADE', 'The Cascade and Specificity',
        'Why one rule wins over another, and why the answer is rarely "the last one".',
        ['Predict which rule applies when two conflict'], 50, { after: ['SELECTORS'] }),
      u('BOX_MODEL', 'The Box Model',
        'Content, padding, border, margin — and why the width is not the width.',
        ['Explain why an element is wider than you set it'], 50, { after: ['CASCADE'] }),
      u('COLOUR_AND_TEXT', 'Colour and Typography',
        'Readable text: size, line height, contrast and a type scale.',
        ['Set text that is comfortable to read at length'], 45, { after: ['BOX_MODEL'] }),
      u('FLEXBOX', 'Flexbox',
        'Laying things out in one direction, with alignment that actually behaves.',
        ['Build a header and a card row with flex'], 55, { after: ['BOX_MODEL'] }),
      u('GRID', 'CSS Grid',
        'Two-dimensional layout, and when it beats flex.',
        ['Build a page layout with grid'], 55, { after: ['FLEXBOX'] }),
      u('POSITIONING', 'Positioning',
        'static, relative, absolute, fixed, sticky — and why most layouts need none of them.',
        ['Place an element deliberately without breaking the flow'], 45, { after: ['FLEXBOX'] }),
      u('RESPONSIVE', 'Responsive Design',
        'Media queries and relative units, so one page works on a phone and a monitor.',
        ['Make a layout work at three widths'], 55, { after: ['GRID'] }),
      u('DEBUGGING', 'Debugging CSS',
        'Using developer tools to find out why the thing is not where you put it.',
        ['Diagnose a layout fault with dev tools'], 50, { unitType: 'DEBUG', after: ['POSITIONING', 'RESPONSIVE'] }),
      u('PRACTICE', 'CSS Practice',
        'Rebuild real layouts from a screenshot.',
        ['Reproduce a given layout accurately'], 60, { unitType: 'PRACTICE', after: ['DEBUGGING'] }),
      u('MINI_PROJECT', 'Mini Project — style a page end to end',
        'Take your HTML page and make it something you would show somebody.',
        ['Produce a styled, responsive page'], 120, { unitType: 'PROJECT', after: ['PRACTICE'] }),
    ],
  },

  T_JS_DOM: {
    category: 'DIRECTION',
    units: [
      u('JS_IN_A_PAGE', 'JavaScript in a Page',
        'Where scripts go, when they run, and why placement changes behaviour.',
        ['Run a script against a loaded page'], 40),
      u('VALUES_AND_VARIABLES', 'Values, let and const',
        'The types JavaScript has, and which declaration to reach for.',
        ['Choose between let and const correctly'], 45, { after: ['JS_IN_A_PAGE'] }),
      u('FUNCTIONS', 'Functions in JavaScript',
        'Declarations, expressions and arrow functions — three spellings of one idea.',
        ['Write the same function three ways'], 50, { after: ['VALUES_AND_VARIABLES'] }),
      u('ARRAYS_AND_OBJECTS', 'Arrays and Objects',
        'The two structures almost all JavaScript data is made of.',
        ['Build and read nested data'], 55, { after: ['FUNCTIONS'] }),
      u('SELECTING_ELEMENTS', 'Finding Elements in the Page',
        'querySelector and friends — reaching the part of the page you mean.',
        ['Select any element on a page reliably'], 45, { after: ['JS_IN_A_PAGE'] }),
      u('CHANGING_THE_DOM', 'Changing What Is on Screen',
        'Text, attributes, classes and structure — changed from code.',
        ['Change a page in response to data'], 50, { after: ['SELECTING_ELEMENTS'] }),
      u('EVENTS', 'Events',
        'Responding to clicks, typing and submission, and what the event object carries.',
        ['Respond to a click and to a form submission'], 55, { after: ['CHANGING_THE_DOM'] }),
      u('FORM_HANDLING', 'Reading and Validating Form Input',
        'Getting values out, checking them, and telling the person what is wrong.',
        ['Validate a form and report faults clearly'], 55, { after: ['EVENTS'] }),
      u('ASYNC_BASICS', 'Things That Take Time',
        'Why fetching data does not return immediately, and what a promise is for.',
        ['Explain why an alert fires before the data arrives'], 55, { after: ['EVENTS'] }),
      u('DEBUGGING', 'Debugging JavaScript',
        'The console, breakpoints, and reading an error instead of skimming it.',
        ['Find a runtime fault using the console'], 50, { unitType: 'DEBUG', after: ['FORM_HANDLING'] }),
      u('PRACTICE', 'JavaScript Practice',
        'Small interactive pieces, built from a description.',
        ['Build interactive behaviour without a tutorial'], 60, { unitType: 'PRACTICE', after: ['DEBUGGING', 'ASYNC_BASICS'] }),
      u('MINI_PROJECT', 'Mini Project — an interactive page',
        'One page that reacts to what somebody does.',
        ['Build and explain an interactive page'], 120, { unitType: 'PROJECT', after: ['PRACTICE'] }),
    ],
  },

  T_FORMS: {
    category: 'DIRECTION',
    units: [
      u('FORM_ELEMENTS', 'The Form Elements',
        'Text, number, select, checkbox, radio, textarea — and picking the right one.',
        ['Choose the correct input for a kind of data'], 45),
      u('LABELS', 'Labels and Why Every Input Needs One',
        'Associating a label with its input, and what breaks when you do not.',
        ['Label every input so clicking the text focuses the field'], 35, { after: ['FORM_ELEMENTS'] }),
      u('VALIDATION', 'Built-in Validation',
        'required, type, pattern, min and max — what the browser checks for free.',
        ['Prevent invalid submission without any script'], 45, { after: ['LABELS'] }),
      u('SUBMISSION', 'What Happens on Submit',
        'GET versus POST, action, and where the data actually goes.',
        ['Say what the browser sends and where'], 45, { after: ['VALIDATION'] }),
      u('ERRORS', 'Telling Somebody What Went Wrong',
        'Error messages that say what to do rather than what failed.',
        ['Write an error message somebody can act on'], 40, { after: ['SUBMISSION'] }),
      u('PRACTICE', 'Forms Practice',
        'Build several real forms, including the awkward ones.',
        ['Build a multi-field form that validates'], 60, { unitType: 'PRACTICE', after: ['ERRORS'] }),
      u('MINI_PROJECT', 'Mini Project — a working form',
        'A form that collects something real and handles every case.',
        ['Build a complete, accessible, validating form'], 90, { unitType: 'PROJECT', after: ['PRACTICE'] }),
    ],
  },

  T_ACCESSIBILITY: {
    category: 'DIRECTION',
    units: [
      u('WHO_IT_IS_FOR', 'Who Accessibility Is For',
        'Permanent, temporary and situational — and why it is most people, sometimes.',
        ['Name three situations that change how somebody uses a page'], 30),
      u('SEMANTICS_FIRST', 'Semantics Do Most of the Work',
        'Correct elements before any ARIA — the cheapest accessibility there is.',
        ['Fix an inaccessible page by changing elements alone'], 45, { after: ['WHO_IT_IS_FOR'] }),
      u('KEYBOARD', 'Keyboard Navigation',
        'Tab order, focus visibility, and reaching everything without a mouse.',
        ['Operate your page entirely by keyboard'], 45, { after: ['SEMANTICS_FIRST'] }),
      u('SCREEN_READERS', 'How a Screen Reader Reads a Page',
        'Hearing your own page, and noticing what makes no sense out loud.',
        ['Listen to a page and identify two problems'], 50, { after: ['KEYBOARD'] }),
      u('CONTRAST_AND_TEXT', 'Contrast, Size and Zoom',
        'Text people can actually read, at the sizes they actually use.',
        ['Check and fix contrast on a real page'], 40, { after: ['SEMANTICS_FIRST'] }),
      u('TESTING', 'Checking Your Own Work',
        'Automated checks catch a third of it. Here is how to find the rest.',
        ['Run a check and interpret what it reports'], 45, { after: ['SCREEN_READERS', 'CONTRAST_AND_TEXT'] }),
      u('PRACTICE', 'Accessibility Practice',
        'Take broken pages and make them usable.',
        ['Repair three inaccessible pages'], 60, { unitType: 'PRACTICE', after: ['TESTING'] }),
    ],
  },

  T_HTTP: {
    category: 'UNIVERSAL',
    units: [
      u('CLIENT_SERVER', 'Clients and Servers',
        'Who asks, who answers, and what sits between them.',
        ['Describe what happens when you type an address'], 40),
      u('REQUEST_RESPONSE', 'Requests and Responses',
        'The shape of both, and what a header is for.',
        ['Read a raw request and response'], 45, { after: ['CLIENT_SERVER'] }),
      u('METHODS', 'GET, POST and the Others',
        'What each method means, and why the meaning matters more than the mechanism.',
        ['Choose the right method for an action'], 40, { after: ['REQUEST_RESPONSE'] }),
      u('STATUS_CODES', 'Status Codes',
        'The families, the ones you will meet daily, and what 404 versus 500 tells you.',
        ['Diagnose a failure from its status code'], 40, { after: ['METHODS'] }),
      u('URLS', 'What a URL Is Made Of',
        'Scheme, host, path, query, fragment — each part doing a different job.',
        ['Take a URL apart and say what each piece does'], 35, { after: ['CLIENT_SERVER'] }),
      u('BROWSER_TOOLS', 'Watching Traffic in the Browser',
        'The network tab: seeing exactly what your page asked for and got back.',
        ['Find a failing request in dev tools'], 45, { unitType: 'DEBUG', after: ['STATUS_CODES'] }),
      u('PRACTICE', 'Web Protocol Practice',
        'Inspect real traffic and explain what you find.',
        ['Explain a page load request by request'], 50, { unitType: 'PRACTICE', after: ['BROWSER_TOOLS', 'URLS'] }),
    ],
  },

  /* ── M06 · C Programming (academic support) ───────────────────────────────────────── */

  T_C_BASICS: {
    category: 'ACADEMIC',
    units: [
      u('WHY_C', 'Why C Is Still Taught',
        'What C makes visible that higher-level languages hide.',
        ['Say what C shows you that Python does not'], 30),
      u('COMPILE_AND_RUN', 'Compiling and Running',
        'Source to executable, and reading the compiler when it refuses.',
        ['Compile and run a program from the command line'], 45, { after: ['WHY_C'] }),
      u('TYPES_AND_VARIABLES', 'Types and Declarations',
        'Declaring before using, fixed sizes, and what that buys and costs.',
        ['Declare and use the basic types correctly'], 45, { after: ['COMPILE_AND_RUN'] }),
      u('IO', 'printf and scanf',
        'Formatted output and input, and the format strings that go wrong.',
        ['Read and print values of several types'], 45, { after: ['TYPES_AND_VARIABLES'] }),
      u('CONTROL_FLOW', 'Conditions and Loops in C',
        'The same ideas in a stricter language, and the semicolon that ruins an afternoon.',
        ['Write branching and looping code that compiles'], 50, { after: ['IO'] }),
      u('FUNCTIONS', 'Functions and Prototypes',
        'Declaring before calling, and why the compiler insists.',
        ['Write a program split across functions'], 50, { after: ['CONTROL_FLOW'] }),
      u('ARRAYS', 'Arrays in C',
        'Fixed size, no bounds checking, and the consequences of both.',
        ['Explain what happens past the end of an array'], 50, { after: ['FUNCTIONS'] }),
      u('POINTERS', 'Pointers',
        'Addresses as values — the idea C is really about.',
        ['Explain what a pointer holds and what it points at'], 60, { after: ['ARRAYS'] }),
      u('DEBUGGING', 'Debugging C',
        'Segmentation faults, uninitialised values, and reading a compiler error properly.',
        ['Diagnose a crash rather than guessing at it'], 55, { unitType: 'DEBUG', after: ['POINTERS'] }),
      u('PRACTICE', 'C Practice',
        'Exam-shaped problems, written and compiled.',
        ['Solve C problems under exam conditions'], 60, { unitType: 'PRACTICE', after: ['DEBUGGING'] }),
    ],
  },

  /* ── M07 · DSA Foundation ─────────────────────────────────────────────────────────── */

  T_ARRAYS: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_IS_AN_ARRAY', 'What an Array Is',
        'Contiguous storage, indexing from zero, and why access is instant.',
        ['Explain why arr[5] is as fast as arr[0]'], 40),
      u('TRAVERSAL', 'Traversing an Array',
        'Visiting every element, forwards, backwards and in steps.',
        ['Traverse an array three ways'], 40, { after: ['WHAT_IS_AN_ARRAY'] }),
      u('SEARCHING', 'Searching',
        'Linear search, and why sorted data allows something much better.',
        ['Implement linear search and say what it costs'], 50, { after: ['TRAVERSAL'] }),
      u('BINARY_SEARCH', 'Binary Search',
        'Halving the problem each step, and the off-by-one that everybody writes once.',
        ['Implement binary search correctly'], 60, { after: ['SEARCHING'] }),
      u('INSERT_DELETE', 'Inserting and Removing',
        'Why the middle is expensive and the end is cheap.',
        ['Say what inserting at the front costs'], 45, { after: ['TRAVERSAL'] }),
      u('TWO_POINTERS', 'The Two-Pointer Pattern',
        'One pass, two positions — the pattern behind a surprising number of problems.',
        ['Solve a pair-sum problem in one pass'], 55, { after: ['BINARY_SEARCH'] }),
      u('STRING_BASICS', 'Strings as Arrays of Characters',
        'What a string really is, and why some operations are more expensive than they look.',
        ['Explain the cost of building a string in a loop'], 45, { after: ['WHAT_IS_AN_ARRAY'] }),
      u('STRING_PROBLEMS', 'Common String Problems',
        'Reversal, palindromes, counting and searching — the recurring shapes.',
        ['Solve three classic string problems'], 55, { after: ['STRING_BASICS', 'TWO_POINTERS'] }),
      u('COMPLEXITY', 'Talking About Cost',
        'Big-O as a way of comparing approaches rather than as an exam topic.',
        ['Compare two solutions by cost, not by feel'], 50, { after: ['BINARY_SEARCH'] }),
      u('DEBUGGING', 'Debugging Index Errors',
        'Off-by-one, out of bounds, and the loop that runs once too often.',
        ['Fix three index faults'], 45, { unitType: 'DEBUG', after: ['INSERT_DELETE'] }),
      u('PRACTICE', 'Array and String Practice',
        'A set of problems that covers each pattern at least twice.',
        ['Solve unfamiliar array problems unaided'], 60, { unitType: 'PRACTICE', after: ['COMPLEXITY', 'STRING_PROBLEMS', 'DEBUGGING'] }),
    ],
  },

  /* ── M08 · Database Foundations ───────────────────────────────────────────────────── */

  T_SQL: {
    category: 'UNIVERSAL',
    units: [
      u('WHY_DATABASES', 'Why a Database and Not a File',
        'What a database gives you that a spreadsheet or a file cannot.',
        ['Say when a file stops being enough'], 35),
      u('TABLES_ROWS_COLUMNS', 'Tables, Rows and Columns',
        'The shape of relational data, and what a row represents.',
        ['Model a simple thing as a table'], 40, { after: ['WHY_DATABASES'] }),
      u('KEYS', 'Primary and Foreign Keys',
        'Identifying a row, and pointing at one from somewhere else.',
        ['Design two related tables with correct keys'], 50, { after: ['TABLES_ROWS_COLUMNS'] }),
      u('SELECT', 'SELECT',
        'Asking for columns, and getting exactly what you asked for.',
        ['Retrieve specific columns from a table'], 40, { after: ['TABLES_ROWS_COLUMNS'] }),
      u('WHERE', 'Filtering with WHERE',
        'Conditions, comparison, AND and OR, and the trap of NULL.',
        ['Filter rows including the null case'], 50, { after: ['SELECT'] }),
      u('ORDER_AND_LIMIT', 'Sorting and Limiting',
        'ORDER BY and LIMIT — and why a query without an order has none.',
        ['Return the top five of something'], 40, { after: ['WHERE'] }),
      u('AGGREGATES', 'COUNT, SUM, AVG',
        'Summarising many rows into one number.',
        ['Answer a question with an aggregate'], 45, { after: ['ORDER_AND_LIMIT'] }),
      u('GROUP_BY', 'GROUP BY',
        'Summarising per category, and why HAVING is not WHERE.',
        ['Produce a per-group summary'], 55, { after: ['AGGREGATES'] }),
      u('JOINS', 'Joins',
        'Combining tables, and what inner and left actually do to the rows.',
        ['Join two tables and predict the row count'], 60, { after: ['KEYS', 'GROUP_BY'] }),
      u('INSERT_UPDATE_DELETE', 'Changing Data',
        'Writing rows, and the WHERE clause you must never forget on an UPDATE.',
        ['Modify data safely'], 50, { after: ['WHERE'] }),
      u('DEBUGGING', 'Why a Query Returns Nothing',
        'The handful of reasons, in the order worth checking them.',
        ['Diagnose an empty result set'], 45, { unitType: 'DEBUG', after: ['JOINS'] }),
      u('PRACTICE', 'SQL Practice',
        'Real questions against a real dataset.',
        ['Answer questions with queries you wrote'], 60, { unitType: 'PRACTICE', after: ['DEBUGGING', 'INSERT_UPDATE_DELETE'] }),
    ],
  },

  /* ── M09 · Linux and Operating Systems ────────────────────────────────────────────── */

  T_LINUX: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_AN_OS_DOES', 'What an Operating System Does',
        'Managing processes, memory, files and devices so your program does not have to.',
        ['Name four things the OS does for every program'], 40),
      u('KERNEL_AND_USERSPACE', 'Kernel and User Space',
        'The line between your code and the machine, and why crossing it costs something.',
        ['Explain what a system call is'], 45, { after: ['WHAT_AN_OS_DOES'] }),
      u('USERS_AND_GROUPS', 'Users, Groups and root',
        'Who you are on a machine, and why you are usually not root.',
        ['Say why sudo exists'], 40, { after: ['WHAT_AN_OS_DOES'] }),
      u('PACKAGES', 'Installing Software',
        'Package managers, and what installing actually puts where.',
        ['Install and remove a package cleanly'], 40, { after: ['USERS_AND_GROUPS'] }),
      u('ENVIRONMENT', 'Environment Variables and PATH',
        'How the shell finds a command, and why "command not found" is usually PATH.',
        ['Fix a command not found by inspecting PATH'], 45, { after: ['PACKAGES'] }),
      u('LOGS', 'Where a Machine Writes Down What Happened',
        'Finding logs and reading them when something has already gone wrong.',
        ['Find the log for a failing service'], 45, { unitType: 'DEBUG', after: ['ENVIRONMENT'] }),
      u('PRACTICE', 'Operating System Practice',
        'Tasks that can only be done by understanding the system underneath.',
        ['Complete admin tasks on a real machine'], 60, { unitType: 'PRACTICE', after: ['LOGS'] }),
    ],
  },

  T_PROCESSES: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_IS_A_PROCESS', 'Program, Process, Thread',
        'The difference between a file on disk and a thing that is running.',
        ['Distinguish a program from a process'], 40),
      u('LISTING', 'Seeing What Is Running',
        'ps and top — finding out what the machine is actually doing.',
        ['Identify what is consuming the CPU'], 40, { after: ['WHAT_IS_A_PROCESS'] }),
      u('LIFECYCLE', 'How a Process Starts and Ends',
        'Creation, exit codes, and what a zombie process is.',
        ['Read an exit code and say what it means'], 45, { after: ['LISTING'] }),
      u('SIGNALS', 'Stopping Things',
        'Interrupt, terminate, kill — three different requests, increasingly rude.',
        ['Stop a process the polite way first'], 45, { after: ['LIFECYCLE'] }),
      u('BACKGROUND', 'Foreground and Background Jobs',
        'Running something without giving up your terminal.',
        ['Move a job between foreground and background'], 40, { after: ['SIGNALS'] }),
      u('PRACTICE', 'Process Practice',
        'Find, inspect and control running work on a live machine.',
        ['Diagnose and stop a runaway process'], 50, { unitType: 'PRACTICE', after: ['BACKGROUND'] }),
    ],
  },

  T_OS_MEMORY: {
    category: 'UNIVERSAL',
    units: [
      u('MEMORY_LAYOUT', 'How a Program Uses Memory',
        'Stack, heap, and what lives in each.',
        ['Say where a local variable lives and where a large object does'], 45),
      u('VIRTUAL_MEMORY', 'Virtual Memory',
        'Why every program believes it has the whole machine to itself.',
        ['Explain why two programs can use the same address'], 50, { after: ['MEMORY_LAYOUT'] }),
      u('ALLOCATION', 'Allocating and Releasing',
        'Asking for memory, giving it back, and what happens when you forget.',
        ['Describe what a memory leak actually is'], 45, { after: ['VIRTUAL_MEMORY'] }),
      u('SWAPPING', 'When Memory Runs Out',
        'Swap, thrashing, and why a machine can be busy doing nothing.',
        ['Explain why a machine slows to a crawl rather than stopping'], 45, { after: ['ALLOCATION'] }),
      u('MEASURING', 'Measuring Memory Use',
        'Reading the numbers, and why "free" memory is not what it sounds like.',
        ['Interpret a memory report correctly'], 45, { unitType: 'DEBUG', after: ['SWAPPING'] }),
      u('PRACTICE', 'Memory Practice',
        'Watch real programs use and release memory.',
        ['Observe and explain a program’s memory behaviour'], 50, { unitType: 'PRACTICE', after: ['MEASURING'] }),
    ],
  },

  T_SHELL_PIPELINES: {
    category: 'UNIVERSAL',
    units: [
      u('STREAMS', 'Input, Output and Errors',
        'The three streams every command has, and why errors are separate on purpose.',
        ['Separate a command’s output from its errors'], 45),
      u('REDIRECTION', 'Redirection',
        'Sending output to a file, and appending rather than overwriting.',
        ['Capture output without losing what was there'], 40, { after: ['STREAMS'] }),
      u('PIPES', 'Pipes',
        'The output of one command as the input of the next — the whole idea of the shell.',
        ['Chain three commands to answer a question'], 50, { after: ['REDIRECTION'] }),
      u('GREP', 'Finding Lines That Match',
        'grep, and the patterns that make it powerful.',
        ['Find matching lines across many files'], 50, { after: ['PIPES'] }),
      u('TRANSFORMING', 'Cutting, Sorting, Counting',
        'cut, sort, uniq, wc — the small tools a pipeline is built from.',
        ['Produce a frequency count from raw text'], 55, { after: ['GREP'] }),
      u('SCRIPTS', 'Saving a Pipeline as a Script',
        'Turning something you typed twice into something you keep.',
        ['Write and run a shell script'], 50, { after: ['TRANSFORMING'] }),
      u('PRACTICE', 'Pipeline Practice',
        'Answer real questions about real files, using only the shell.',
        ['Answer data questions with a one-line pipeline'], 60, { unitType: 'PRACTICE', after: ['SCRIPTS'] }),
    ],
  },

  T_NETWORKING: {
    category: 'DIRECTION',
    units: [
      u('WHAT_IS_A_NETWORK', 'What a Network Is',
        'Machines talking, and the layers that make it possible to ignore the details.',
        ['Describe the path a message takes between two machines'], 40),
      u('IP_ADDRESSES', 'IP Addresses',
        'How a machine is identified, and the difference between local and public.',
        ['Find your own address and say which kind it is'], 45, { after: ['WHAT_IS_A_NETWORK'] }),
      u('DNS', 'DNS',
        'Turning a name into an address, and why a site can be up while the name is broken.',
        ['Resolve a name by hand and explain the result'], 45, { after: ['IP_ADDRESSES'] }),
      u('PORTS', 'Ports',
        'One machine, many services, and how the right one receives your request.',
        ['Say which port a service listens on and why'], 40, { after: ['IP_ADDRESSES'] }),
      u('TCP_UDP', 'TCP and UDP',
        'Reliable and ordered, or fast and lossy — and when each is right.',
        ['Choose the right protocol for a use case'], 50, { after: ['PORTS'] }),
      u('TOOLS', 'Diagnosing a Network',
        'ping, traceroute, curl — finding where in the chain it breaks.',
        ['Locate a failure between you and a server'], 50, { unitType: 'DEBUG', after: ['DNS', 'TCP_UDP'] }),
      u('SECURITY_BASICS', 'Why HTTPS Exists',
        'What plain traffic exposes, and what a certificate actually proves.',
        ['Explain what HTTPS protects and what it does not'], 45, { after: ['TCP_UDP'] }),
      u('PRACTICE', 'Networking Practice',
        'Trace and diagnose real connections.',
        ['Diagnose a connectivity problem end to end'], 55, { unitType: 'PRACTICE', after: ['TOOLS', 'SECURITY_BASICS'] }),
    ],
  },

  /* ── M10 · Mathematics for Computer Science ───────────────────────────────────────── */

  T_NUMBER_SYSTEMS: {
    category: 'UNIVERSAL',
    units: [
      u('WHY_BINARY', 'Why Machines Count in Twos',
        'Two states, and everything else built on top of them.',
        ['Explain why binary rather than decimal'], 35),
      u('BINARY_DECIMAL', 'Converting Binary and Decimal',
        'Both directions, by hand, until it is quick.',
        ['Convert either way without a calculator'], 45, { after: ['WHY_BINARY'] }),
      u('HEX', 'Hexadecimal',
        'Why colours and addresses are written in base sixteen.',
        ['Convert between hex and binary at sight'], 45, { after: ['BINARY_DECIMAL'] }),
      u('BITS_AND_BYTES', 'Bits, Bytes and Sizes',
        'What a byte holds, and why file sizes are the numbers they are.',
        ['Say how many values a byte can represent'], 40, { after: ['BINARY_DECIMAL'] }),
      u('NEGATIVE_AND_OVERFLOW', 'Negative Numbers and Overflow',
        'Two’s complement, and what happens when a number runs out of room.',
        ['Explain why a counter can go negative'], 50, { after: ['BITS_AND_BYTES'] }),
      u('PRACTICE', 'Number Systems Practice',
        'Conversion and reasoning drills until they are automatic.',
        ['Convert and reason about bases quickly'], 50, { unitType: 'PRACTICE', after: ['HEX', 'NEGATIVE_AND_OVERFLOW'] }),
    ],
  },

  T_LOGIC_MATH: {
    category: 'UNIVERSAL',
    units: [
      u('PROPOSITIONS', 'Propositions',
        'Statements that are true or false, and nothing in between.',
        ['Tell a proposition from a sentence that is not one'], 35),
      u('CONNECTIVES', 'Logical Connectives: AND, OR, NOT',
        'Combining propositions, with truth tables to settle arguments.',
        ['Build a truth table for a compound statement'], 45, { after: ['PROPOSITIONS'] }),
      u('IMPLICATION', 'If-Then',
        'Implication, and why it is true when the premise is false.',
        ['Explain why a false premise makes an implication true'], 50, { after: ['CONNECTIVES'] }),
      u('EQUIVALENCE', 'Equivalence and De Morgan',
        'Rewriting a condition into a simpler one that means the same thing.',
        ['Simplify a compound condition correctly'], 50, { after: ['IMPLICATION'] }),
      u('SETS', 'Sets',
        'Collections without duplicates or order, and the notation for them.',
        ['Write a set and say what belongs to it'], 40, { after: ['PROPOSITIONS'] }),
      u('SET_OPERATIONS', 'Union, Intersection, Difference',
        'Combining sets, and the Venn diagram that makes it obvious.',
        ['Compute set operations and draw them'], 45, { after: ['SETS'] }),
      u('SETS_IN_CODE', 'Sets in a Program',
        'Where these operations show up in real code, and why they are fast.',
        ['Use a set to remove duplicates and test membership'], 45, { after: ['SET_OPERATIONS'] }),
      u('PRACTICE', 'Logic and Sets Practice',
        'Mixed problems, including the ones that look like trick questions.',
        ['Solve logic and set problems reliably'], 55, { unitType: 'PRACTICE', after: ['EQUIVALENCE', 'SETS_IN_CODE'] }),
    ],
  },

  T_RELATIONS: {
    category: 'UNIVERSAL',
    units: [
      u('ORDERED_PAIRS', 'Ordered Pairs and Products',
        'Pairing things up, and why order changes what it means.',
        ['Form the product of two small sets'], 40),
      u('RELATIONS', 'Relations',
        'A set of pairs, and what that captures about how things relate.',
        ['Represent a real relationship as a relation'], 45, { after: ['ORDERED_PAIRS'] }),
      u('PROPERTIES', 'Reflexive, Symmetric, Transitive',
        'The three properties worth naming, with examples that fail each.',
        ['Classify a relation by its properties'], 50, { after: ['RELATIONS'] }),
      u('FUNCTIONS', 'Functions as Relations',
        'The restriction that makes a relation a function, and why it matters in code.',
        ['Say why a function may not map one input to two outputs'], 50, { after: ['PROPERTIES'] }),
      u('MAPPINGS', 'One-to-One, Onto',
        'Injective and surjective, in language a first-year can use.',
        ['Classify a mapping and give a counterexample'], 45, { after: ['FUNCTIONS'] }),
      u('PRACTICE', 'Relations Practice',
        'Classification and construction problems.',
        ['Solve relation problems under exam conditions'], 50, { unitType: 'PRACTICE', after: ['MAPPINGS'] }),
    ],
  },

  T_BOOLEAN: {
    category: 'UNIVERSAL',
    units: [
      u('BOOLEAN_VALUES', 'Boolean Algebra',
        'Algebra with two values, and the laws that hold in it.',
        ['State the basic identities'], 40),
      u('GATES', 'Logic Gates',
        'AND, OR, NOT, XOR as physical things, and their symbols.',
        ['Read a small gate diagram'], 45, { after: ['BOOLEAN_VALUES'] }),
      u('TRUTH_TABLES', 'Truth Tables for Circuits',
        'Working out what a circuit does, exhaustively.',
        ['Produce the truth table of a two-gate circuit'], 45, { after: ['GATES'] }),
      u('SIMPLIFICATION', 'Simplifying Expressions',
        'Fewer gates for the same behaviour, and why that used to cost money.',
        ['Simplify a boolean expression and prove it equivalent'], 55, { after: ['TRUTH_TABLES'] }),
      u('ADDER', 'Building an Adder',
        'How gates become arithmetic — the moment logic becomes a computer.',
        ['Explain how a half adder adds'], 55, { after: ['SIMPLIFICATION'] }),
      u('PRACTICE', 'Boolean Practice',
        'Simplification and circuit-reading drills.',
        ['Simplify and analyse circuits quickly'], 50, { unitType: 'PRACTICE', after: ['ADDER'] }),
    ],
  },

  T_MATRICES: {
    category: 'DIRECTION',
    units: [
      u('WHAT_IS_A_MATRIX', 'What a Matrix Is',
        'A grid of numbers, and the things it can represent.',
        ['Give two real things a matrix can model'], 40),
      u('ADDITION', 'Adding and Scaling',
        'The easy operations, and the shape rules that govern them.',
        ['Add and scale matrices correctly'], 40, { after: ['WHAT_IS_A_MATRIX'] }),
      u('MULTIPLICATION', 'Matrix Multiplication',
        'Why it is not element-wise, and what the result means.',
        ['Multiply two matrices by hand and check the shape'], 60, { after: ['ADDITION'] }),
      u('TRANSPOSE_IDENTITY', 'Transpose and Identity',
        'Flipping a matrix, and the one that changes nothing.',
        ['Use transpose and identity correctly'], 40, { after: ['MULTIPLICATION'] }),
      u('IN_CODE', 'Matrices as Nested Arrays',
        'Representing and traversing a grid in code.',
        ['Traverse a 2D array by row and by column'], 50, { after: ['TRANSPOSE_IDENTITY'] }),
      u('PRACTICE', 'Matrix Practice',
        'Computation by hand and in code.',
        ['Solve matrix problems both ways'], 50, { unitType: 'PRACTICE', after: ['IN_CODE'] }),
    ],
  },

  T_STATS: {
    category: 'DIRECTION',
    units: [
      u('WHY_STATS', 'Why Statistics Matters in Computing',
        'Where these numbers show up once data is involved.',
        ['Name three places statistics appears in software'], 35),
      u('CENTRE', 'Mean, Median, Mode',
        'Three kinds of average, and when each misleads.',
        ['Choose the right average for a skewed dataset'], 45, { after: ['WHY_STATS'] }),
      u('SPREAD', 'Range, Variance, Standard Deviation',
        'How spread out data is, and why that matters more than the average.',
        ['Compute and interpret spread'], 50, { after: ['CENTRE'] }),
      u('DISTRIBUTIONS', 'Distributions',
        'The shape of data, and what normal actually means.',
        ['Recognise a distribution from its shape'], 50, { after: ['SPREAD'] }),
      u('PROBABILITY', 'Probability',
        'Likelihood, independence, and the mistakes everybody makes.',
        ['Compute a compound probability correctly'], 55, { after: ['WHY_STATS'] }),
      u('CONDITIONAL', 'Conditional Probability',
        'Probability given something else, and why it is not symmetric.',
        ['Explain why P(A|B) is not P(B|A)'], 55, { after: ['PROBABILITY'] }),
      u('MISLEADING', 'How Statistics Mislead',
        'Sampling, correlation and the chart designed to deceive.',
        ['Identify what a misleading chart is hiding'], 45, { after: ['DISTRIBUTIONS', 'CONDITIONAL'] }),
      u('PRACTICE', 'Statistics Practice',
        'Compute and interpret on real datasets.',
        ['Answer questions about a dataset defensibly'], 60, { unitType: 'PRACTICE', after: ['MISLEADING'] }),
    ],
  },

  /* ── M11 · AI Literacy ────────────────────────────────────────────────────────────── */

  T_ML_INTRO: {
    category: 'DIRECTION',
    units: [
      u('AI_ML_DL', 'AI, Machine Learning, Deep Learning',
        'Three terms used interchangeably in public and meaning different things.',
        ['Distinguish the three correctly'], 40),
      u('LEARNING_FROM_DATA', 'What "Learning" Means Here',
        'Finding patterns in examples rather than being told the rule.',
        ['Explain learning from data without anthropomorphising it'], 45, { after: ['AI_ML_DL'] }),
      u('SUPERVISED', 'Supervised Learning',
        'Labelled examples, and the two things it is used for.',
        ['Give an example of classification and of regression'], 50, { after: ['LEARNING_FROM_DATA'] }),
      u('UNSUPERVISED', 'Unsupervised Learning',
        'Finding structure with no labels at all.',
        ['Describe a clustering use case'], 45, { after: ['SUPERVISED'] }),
      u('TRAINING_AND_TESTING', 'Training, Testing and Overfitting',
        'Why a model that is perfect on its own data is often worthless.',
        ['Explain overfitting to somebody non-technical'], 55, { after: ['SUPERVISED'] }),
      u('WHERE_IT_FAILS', 'Where Models Go Wrong',
        'Bias in data, distribution shift, and confident wrongness.',
        ['Identify a likely failure mode of a given model'], 50, { after: ['TRAINING_AND_TESTING'] }),
      u('PRACTICE', 'ML Concepts Practice',
        'Classify real scenarios and predict where each would fail.',
        ['Analyse scenarios without writing code'], 50, { unitType: 'PRACTICE', after: ['WHERE_IT_FAILS', 'UNSUPERVISED'] }),
    ],
  },

  T_GENAI: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_IS_GENAI', 'What Generative AI Is',
        'Producing new output rather than classifying existing input.',
        ['Say what makes a model generative'], 35),
      u('TOKENS', 'Tokens and Prediction',
        'Text as tokens, and generation as repeated prediction.',
        ['Explain generation one token at a time'], 50, { after: ['WHAT_IS_GENAI'] }),
      u('WHY_IT_VARIES', 'Why the Same Question Gives Two Answers',
        'Sampling and temperature — and why determinism is a choice.',
        ['Explain why output varies between runs'], 45, { after: ['TOKENS'] }),
      u('HALLUCINATION', 'Confident and Wrong',
        'Why a model invents, and why it sounds exactly as sure either way.',
        ['Spot a plausible fabrication in generated text'], 50, { after: ['WHY_IT_VARIES'] }),
      u('LIMITS', 'What These Models Cannot Do',
        'Knowledge cutoffs, arithmetic, and reasoning that is really pattern matching.',
        ['Predict which tasks a model will do badly'], 45, { after: ['HALLUCINATION'] }),
      u('PRACTICE', 'Generative AI Practice',
        'Probe a model deliberately and document where it breaks.',
        ['Produce evidence of a model’s limits'], 50, { unitType: 'PRACTICE', after: ['LIMITS'] }),
    ],
  },

  T_AI_LITERACY: {
    category: 'UNIVERSAL',
    units: [
      u('CLEAR_INSTRUCTIONS', 'Asking Clearly',
        'Why most bad output is a bad question, and how to tell.',
        ['Rewrite a vague prompt into a precise one'], 45),
      u('CONTEXT', 'Giving Context',
        'What the model does not know about your situation, and supplying it.',
        ['Supply the context a task actually needs'], 45, { after: ['CLEAR_INSTRUCTIONS'] }),
      u('EXAMPLES', 'Showing Examples',
        'Demonstrating the shape you want instead of describing it.',
        ['Improve an output using examples alone'], 45, { after: ['CONTEXT'] }),
      u('ITERATING', 'Refining an Answer',
        'Treating it as a conversation rather than a vending machine.',
        ['Take a mediocre answer to a good one in three turns'], 45, { after: ['EXAMPLES'] }),
      u('VERIFYING', 'Checking What You Are Told',
        'Verifying claims before repeating them, and what is cheap to check.',
        ['Verify three factual claims from generated text'], 50, { after: ['ITERATING'] }),
      u('PRIVACY', 'What Not to Paste In',
        'Personal data, credentials and other people’s work.',
        ['Identify what must never go into a prompt'], 40, { after: ['CONTEXT'] }),
      u('HONESTY', 'Using AI Honestly',
        'Disclosure, academic rules, and taking responsibility for what you submit.',
        ['State when and how you used AI on a piece of work'], 40, { after: ['VERIFYING', 'PRIVACY'] }),
      u('PRACTICE', 'AI Use Practice',
        'Complete real tasks with AI, documenting prompts and verification.',
        ['Produce work with an auditable AI trail'], 55, { unitType: 'PRACTICE', after: ['HONESTY'] }),
    ],
  },

  T_AI_CODING: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_IT_IS_GOOD_AT', 'Where Generated Code Helps',
        'Boilerplate, unfamiliar syntax, and a first draft to react to.',
        ['Name three tasks worth delegating'], 40),
      u('READING_IT', 'Reading Code You Did Not Write',
        'Understanding before running, line by line.',
        ['Explain a generated function line by line'], 55, { after: ['WHAT_IT_IS_GOOD_AT'] }),
      u('TESTING_IT', 'Testing Generated Code',
        'Checking it does what you asked, including the cases it ignored.',
        ['Find a case where generated code fails'], 55, { after: ['READING_IT'] }),
      u('COMMON_FAULTS', 'How Generated Code Goes Wrong',
        'Plausible APIs that do not exist, missing edge cases, subtle logic faults.',
        ['Identify a fabricated API call'], 50, { unitType: 'DEBUG', after: ['TESTING_IT'] }),
      u('OWNERSHIP', 'You Are Responsible For It',
        'Submitting it means claiming it, whatever produced the first draft.',
        ['Explain what accepting generated code commits you to'], 40, { after: ['COMMON_FAULTS'] }),
      u('PRACTICE', 'AI-Assisted Coding Practice',
        'Generate, read, test and fix — in that order, several times.',
        ['Ship working code you can fully explain'], 60, { unitType: 'PRACTICE', after: ['OWNERSHIP'] }),
    ],
  },

  /* ── M12 · Communication ──────────────────────────────────────────────────────────── */

  T_TECH_COMM: {
    category: 'UNIVERSAL',
    units: [
      u('KNOW_YOUR_AUDIENCE', 'Who You Are Explaining To',
        'The same work described three ways, for three different listeners.',
        ['Explain one thing to a peer and to a non-technical person'], 45),
      u('STRUCTURE', 'Structuring an Explanation',
        'What it is, why it matters, how it works — in that order.',
        ['Structure an explanation before giving it'], 45, { after: ['KNOW_YOUR_AUDIENCE'] }),
      u('ASKING_QUESTIONS', 'Asking a Good Question',
        'What you tried, what you expected, what happened — and why that gets answers.',
        ['Write a question that can be answered without follow-up'], 45, { after: ['STRUCTURE'] }),
      u('WRITING_IT_DOWN', 'Writing About Your Work',
        'A README somebody can act on, and commit messages worth reading.',
        ['Write a README for something you built'], 50, { after: ['STRUCTURE'] }),
      u('PRESENTING', 'Presenting Work',
        'Demonstrating something in five minutes without apologising for it.',
        ['Demonstrate a project to an audience'], 55, { after: ['WRITING_IT_DOWN'] }),
      u('FEEDBACK', 'Giving and Taking Feedback',
        'Reviewing somebody’s work usefully, and hearing a review without defending.',
        ['Give feedback that is specific and actionable'], 45, { after: ['PRESENTING'] }),
      u('PRACTICE', 'Communication Practice',
        'Explain, write and present real work, and be reviewed on it.',
        ['Explain your own work to two different audiences'], 60, { unitType: 'PRACTICE', after: ['FEEDBACK', 'ASKING_QUESTIONS'] }),
    ],
  },

  /* ── M13 · Career Awareness ───────────────────────────────────────────────────────── */

  T_CAREER_MAP: {
    category: 'EXPLORATION',
    units: [
      u('ROLE_LANDSCAPE', 'What the Roles Actually Are',
        'Frontend, backend, data, infrastructure, QA — what each does on a Tuesday.',
        ['Describe what four roles do day to day'], 45),
      u('SKILLS_PER_ROLE', 'What Each Role Needs',
        'The skills behind each, and how much they overlap.',
        ['Map skills you are learning to roles'], 45, { after: ['ROLE_LANDSCAPE'] }),
      u('HOW_TEAMS_WORK', 'How Software Teams Work',
        'Who does what, and where a junior fits in the first year.',
        ['Describe a change’s path from idea to production'], 45, { after: ['ROLE_LANDSCAPE'] }),
      u('EARLY_CAREER', 'What a First Job Expects',
        'What is genuinely required versus what a job advert lists.',
        ['Read a job advert critically'], 45, { after: ['SKILLS_PER_ROLE'] }),
      u('CHOOSING', 'Choosing a Direction Without Closing Doors',
        'Committing enough to make progress, loosely enough to change your mind.',
        ['Choose a direction and say what it does not rule out'], 45, { after: ['EARLY_CAREER', 'HOW_TEAMS_WORK'] }),
      u('PRACTICE', 'Career Exploration',
        'Research real roles and real people doing them.',
        ['Produce a short report on a role that interests you'], 50, { unitType: 'PRACTICE', after: ['CHOOSING'] }),
    ],
  },

  /* ── M14 · Foundation Capstone ────────────────────────────────────────────────────── */

  T_CAPSTONE: {
    category: 'UNIVERSAL',
    units: [
      u('CHOOSING_A_PROJECT', 'Choosing Something Worth Building',
        'Small enough to finish, large enough to be worth showing.',
        ['Scope a project you can finish'], 50),
      u('PLANNING', 'Planning Before Building',
        'Breaking it into pieces, and deciding what done means.',
        ['Produce a plan with a definition of done'], 55, { after: ['CHOOSING_A_PROJECT'] }),
      u('BUILDING', 'Building It',
        'Working through the plan, and handling the parts you did not foresee.',
        ['Build the thing you planned'], 180, { unitType: 'PROJECT', after: ['PLANNING'] }),
      u('DEBUGGING', 'Getting It Working',
        'The last twenty percent, which takes the other eighty.',
        ['Diagnose and fix faults in your own project'], 90, { unitType: 'DEBUG', after: ['BUILDING'] }),
      u('DOCUMENTING', 'Writing It Up',
        'A README, the decisions you made, and what you would do differently.',
        ['Document the project so somebody else could run it'], 60, { after: ['DEBUGGING'] }),
      u('PRESENTING', 'Showing It',
        'Demonstrating what you built and answering questions about it.',
        ['Present your project and defend your decisions'], 60, { after: ['DOCUMENTING'] }),
    ],
  },

  /* ── M15 · Aptitude and Placement Rounds ──────────────────────────────────────────── */

  T_APTITUDE_REASONING: {
    category: 'ACADEMIC',
    units: [
      u('NUMBER_SERIES', 'Number Series',
        'Spotting the rule, including when it is two rules alternating.',
        ['Complete unfamiliar series under time pressure'], 45),
      u('LETTER_SERIES', 'Letter and Symbol Series',
        'The same skill on a different alphabet.',
        ['Solve letter series quickly'], 40, { after: ['NUMBER_SERIES'] }),
      u('ANALOGIES', 'Analogies',
        'Finding the relationship first, then applying it.',
        ['Solve analogies by naming the relationship'], 40, { after: ['LETTER_SERIES'] }),
      u('BLOOD_RELATIONS', 'Blood Relations',
        'Drawing the family tree rather than holding it in your head.',
        ['Solve relation problems by diagram'], 45, { after: ['ANALOGIES'] }),
      u('DIRECTIONS', 'Direction Sense',
        'Sketching the path, and the mistakes made by not sketching it.',
        ['Solve direction problems by drawing'], 40, { after: ['BLOOD_RELATIONS'] }),
      u('SEATING', 'Seating and Arrangement',
        'Systematic elimination on constraint puzzles.',
        ['Solve an arrangement puzzle methodically'], 55, { after: ['DIRECTIONS'] }),
      u('SYLLOGISMS', 'Syllogisms',
        'What follows and what merely seems to, with Venn diagrams to prove it.',
        ['Decide validity using a diagram'], 50, { after: ['SEATING'] }),
      u('PRACTICE', 'Reasoning Practice',
        'Timed mixed sets, which is how they are actually asked.',
        ['Complete a timed mixed set accurately'], 60, { unitType: 'PRACTICE', after: ['SYLLOGISMS'] }),
    ],
  },

  T_APTITUDE_DATA: {
    category: 'ACADEMIC',
    units: [
      u('READING_TABLES', 'Reading a Table',
        'Finding the number asked for, and not the one next to it.',
        ['Answer questions from a dense table accurately'], 45),
      u('CHARTS', 'Bar, Line and Pie Charts',
        'Reading each correctly, including what each hides.',
        ['Extract values and trends from three chart types'], 45, { after: ['READING_TABLES'] }),
      u('PERCENTAGES', 'Percentages and Change',
        'Increase, decrease, and why a 50% fall does not undo a 50% rise.',
        ['Compute percentage change correctly'], 50, { after: ['READING_TABLES'] }),
      u('RATIOS', 'Ratios and Proportions',
        'Comparing quantities, and scaling them.',
        ['Solve ratio problems quickly'], 45, { after: ['PERCENTAGES'] }),
      u('AVERAGES', 'Averages in Data Sets',
        'Weighted averages, and why the obvious method is often wrong.',
        ['Compute a weighted average correctly'], 45, { after: ['RATIOS'] }),
      u('SPEED_TECHNIQUES', 'Answering Under Time Pressure',
        'Estimation, elimination, and knowing when to skip.',
        ['Answer accurately without full computation'], 50, { after: ['AVERAGES', 'CHARTS'] }),
      u('PRACTICE', 'Data Interpretation Practice',
        'Timed sets against realistic data.',
        ['Complete a timed set within the limit'], 60, { unitType: 'PRACTICE', after: ['SPEED_TECHNIQUES'] }),
    ],
  },
};
