import { TopicSeed } from './year1MegaCurriculum';
import { u, closeOut } from './year3UnitKit';

/**
 * Year 3, Stage 2 — the specialization. Modules S11 to S19.
 *
 * ── THE DIRECTION IS THE YEAR ─────────────────────────────────────────────────────────────
 *
 * In Year 2 a direction filtered enrichment. In Year 3 it is compulsory and it is most of what
 * the student is there for, so each track is a run of five or six topics ending in a project of
 * its own — not a sampling. A student gets ONE of these tracks in full; the others are never
 * composed for them, because `applicableDirections` on the topic keeps them out.
 *
 * ── THE PROJECT TOPICS ARE SHORT ON PURPOSE ───────────────────────────────────────────────
 *
 * A project topic is a brief, the build, and showing it — three units, not ten. The work is the
 * building, and padding it with lessons about building would take time away from the thing being
 * built.
 *
 * ── S19 IS UNIVERSAL, NOT A TRACK ─────────────────────────────────────────────────────────
 *
 * AI-assisted engineering sits in this stage because it belongs beside the specialization work,
 * but every student gets it whatever direction they chose. It is how the whole industry now
 * writes code, and reviewing what an assistant produced is a skill in its own right.
 */

export const YEAR3_TRACKS: Record<string, TopicSeed> = {
  /* ── S11 · Confirming the direction ──────────────────────────────────────────────────── */
  T3_DIRECTION_CHOICE: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_EACH_DIRECTION_IS', 'What Each Direction Actually Does All Day',
        'Backend, frontend, data, ML, cloud, security and mobile — the work, not the job title.',
        ['Describe what a week looks like in each direction'], 55),
      u('AGAINST_YOUR_EVIDENCE', 'Comparing Against Your Own Evidence',
        'Which direction your skill profile already points at, and how much that should count.',
        ['Compare the directions against your evidence rather than against what sounds impressive'],
        60, { after: ['WHAT_EACH_DIRECTION_IS'] }),
      u('CONFIRM_OR_CHANGE', 'Confirming, or Changing, Your Direction',
        'You chose one at the start. This is the last point at which changing it is free.',
        ['Confirm your direction, or change it, on evidence'],
        50, { unitType: 'CHECKPOINT', after: ['AGAINST_YOUR_EVIDENCE'] }),
    ],
  },

  /* ── S12 · Backend ───────────────────────────────────────────────────────────────────── */
  T3_BACKEND_ARCH: {
    category: 'DIRECTION',
    units: [
      u('CONTROLLERS_SERVICES_DATA', 'Controllers, Services and Data Access',
        'Three jobs that end up in one file, and what separating them buys when you test it.',
        ['Separate the three so each can be tested on its own'], 80),
      u('WHERE_THE_RULES_LIVE', 'Where the Business Rules Live',
        'Not in the controller and not in the query. Why the middle is the durable place.',
        ['Put a business rule where it survives a change of framework'], 70,
        { after: ['CONTROLLERS_SERVICES_DATA'] }),
      u('DEPENDENCY_DIRECTION', 'Which Way the Dependencies Point',
        'The rule that keeps the domain from knowing about the database.',
        ['State which layer may import which, and why'], 70, { after: ['WHERE_THE_RULES_LIVE'] }),
      ...closeOut('Backend Architecture', 'DEPENDENCY_DIRECTION'),
    ],
  },
  T3_BACKEND_DATA: {
    category: 'DIRECTION',
    units: [
      u('TRANSACTIONS_IN_A_SERVICE', 'Transactions Inside a Request',
        'Where a transaction begins and ends when a service call spans three writes.',
        ['Keep a multi-step write correct when two requests arrive at once'], 80),
      u('N_PLUS_ONE', 'The Query You Did Not Know You Ran',
        'The N+1 that turns one endpoint into four hundred queries, and how to see it.',
        ['Find and fix an N+1 in a real endpoint'], 75, { after: ['TRANSACTIONS_IN_A_SERVICE'] }),
      u('MEASURING_THE_ENDPOINT', 'Finding What Is Costing the Response',
        'Timing the parts before optimising any of them.',
        ['Prove which query is costing the endpoint its time'], 70, { after: ['N_PLUS_ONE'] }),
      ...closeOut('Backend Data', 'MEASURING_THE_ENDPOINT'),
    ],
  },
  T3_BACKEND_AUTH: {
    category: 'DIRECTION',
    units: [
      u('ISSUING_A_TOKEN', 'Issuing and Carrying a Token',
        'What goes in it, what must not, where it is kept, and how it travels.',
        ['Issue a token and carry it safely on every request'], 80),
      u('EXPIRY_IN_A_SERVICE', 'Expiry, Refresh and Logging Out Everywhere',
        'Short-lived credentials, refresh, and revoking one that leaked.',
        ['Expire, refresh and revoke a credential'], 70, { after: ['ISSUING_A_TOKEN'] }),
      u('PERMISSION_CHECKS', 'Checking Permission on Every Request',
        'Roles, ownership, and the check that has to be in the service rather than the route.',
        ['Check what this caller may do, not only who they are'], 80, { after: ['EXPIRY_IN_A_SERVICE'] }),
      ...closeOut('Backend Auth', 'PERMISSION_CHECKS'),
    ],
  },
  T3_BACKEND_SCALE: {
    category: 'DIRECTION',
    units: [
      u('OFF_THE_REQUEST', 'Moving Slow Work Off the Request',
        'Queues and background jobs, and what the caller is told meanwhile.',
        ['Move a slow operation off the request without lying to the caller'], 80),
      u('CACHING_A_RESPONSE', 'Caching a Response Safely',
        'What is safe to cache in a service, for how long, and how it is invalidated.',
        ['Cache a response and say how it becomes wrong'], 70, { after: ['OFF_THE_REQUEST'] }),
      u('MEASURE_BEFORE_AND_AFTER', 'Measure, Change, Measure',
        'Performance work without a measurement is decoration.',
        ['Prove a performance change with numbers either side of it'], 65,
        { after: ['CACHING_A_RESPONSE'] }),
    ],
  },
  T3_BACKEND_OPS: {
    category: 'DIRECTION',
    units: [
      u('LOGGING_A_SERVICE', 'Logging a Service So 3am Is Survivable',
        'Request ids, levels and the fields that make a log searchable.',
        ['Log a request so its failure can be reconstructed'], 70),
      u('TESTING_AN_API', 'Testing an API',
        'Unit, integration and contract — and which failure each one would have caught.',
        ['Test an endpoint at the right level for what could break'], 75, { after: ['LOGGING_A_SERVICE'] }),
      u('DOCUMENTING_IT', 'Documentation Somebody Can Call From',
        'Shapes, errors and an example that works when pasted.',
        ['Document an API so another engineer needs no help'], 60, { after: ['TESTING_AN_API'] }),
    ],
  },
  T3_BACKEND_PROJECT: {
    category: 'DIRECTION',
    units: [
      u('BRIEF', 'Production Backend Project — the Brief',
        'What you are building, what it must do, and what done means before you start.',
        ['Write a brief with a definition of done you can be held to'], 60),
      u('BUILD', 'Building It',
        'Auth, a database, tests, logging and a deployment. The whole thing, not a demo.',
        ['Ship a backend with auth, data, tests and a deployment behind it'],
        200, { unitType: 'PROJECT', after: ['BRIEF'] }),
      u('EXPLAIN', 'Explaining Every Decision in It',
        'The part an interview actually tests: why, not what.',
        ['Defend every significant decision in your project'], 70, { after: ['BUILD'] }),
    ],
  },

  /* ── S13 · Frontend ──────────────────────────────────────────────────────────────────── */
  T3_FRONTEND_ADV_JS: {
    category: 'DIRECTION',
    units: [
      u('ASYNC_THAT_FAILS', 'Requests That Are Slow, Fail, or Come Back Late',
        'Loading, error and stale states — the three every real screen has and every demo skips.',
        ['Handle a request that is slow, fails, or returns after the user moved on'], 80),
      u('RACE_CONDITIONS', 'Two Requests, One Screen',
        'The older response arriving last, and how a screen shows the wrong thing because of it.',
        ['Prevent a stale response from overwriting a newer one'], 75, { after: ['ASYNC_THAT_FAILS'] }),
      u('ERROR_UX', 'What the User Is Shown When It Breaks',
        'A message they can act on, and a way back.',
        ['Show a failure the user can do something about'], 60, { after: ['RACE_CONDITIONS'] }),
      ...closeOut('Async Frontend', 'ERROR_UX'),
    ],
  },
  T3_FRONTEND_COMPONENTS: {
    category: 'DIRECTION',
    units: [
      u('SPLITTING_A_SCREEN', 'Splitting a Screen Into Components',
        'What makes a good boundary, and the component that is doing four jobs.',
        ['Break a screen into components that can each be changed alone'], 75),
      u('PROPS_AND_EVENTS', 'Data Down, Events Up',
        'The one convention that keeps a component tree comprehensible.',
        ['Pass data and events in a direction that stays traceable'], 70, { after: ['SPLITTING_A_SCREEN'] }),
      u('ROUTING', 'Routing and the URL as State',
        'The URL is state. Making it one somebody can bookmark and share.',
        ['Route so the URL describes what is on screen'], 70, { after: ['PROPS_AND_EVENTS'] }),
      ...closeOut('Components', 'ROUTING'),
    ],
  },
  T3_FRONTEND_STATE: {
    category: 'DIRECTION',
    units: [
      u('WHERE_A_VALUE_LIVES', 'Where a Value Should Live',
        'Local, lifted, or shared — and the cost of choosing wrong.',
        ['Decide where a value lives and who may change it'], 80),
      u('SERVER_STATE', 'Server State Is Not Client State',
        'Data you own against a copy of somebody else’s, and why conflating them causes stale screens.',
        ['Tell server state from client state and handle each accordingly'], 75,
        { after: ['WHERE_A_VALUE_LIVES'] }),
      u('DERIVED_STATE', 'Do Not Store What You Can Compute',
        'Two sources of truth disagreeing is why the screen showed the wrong number.',
        ['Derive rather than duplicate, and say when caching a derivation is worth it'], 65,
        { after: ['SERVER_STATE'] }),
      ...closeOut('State Management', 'DERIVED_STATE'),
    ],
  },
  T3_FRONTEND_FORMS: {
    category: 'DIRECTION',
    units: [
      u('BOTH_SIDES', 'Validate on the Client for Kindness, the Server for Correctness',
        'Why both, and why the client one is never the real check.',
        ['Validate in both places and say what each is for'], 70),
      u('FORM_STATE', 'Forms That Do Not Lose Work',
        'Dirty state, partial saves and the confirmation before navigating away.',
        ['Build a form that does not lose what somebody typed'], 70, { after: ['BOTH_SIDES'] }),
      u('SHOWING_ERRORS', 'Showing a Field Error Usefully',
        'Beside the field, in words, and not all at once before they have typed anything.',
        ['Show validation errors at a moment that helps'], 55, { after: ['FORM_STATE'] }),
    ],
  },
  T3_FRONTEND_QUALITY: {
    category: 'DIRECTION',
    units: [
      u('KEYBOARD_AND_SCREEN_READER', 'Usable Without a Mouse',
        'Focus, labels and landmarks — accessibility as something that is built, not audited in.',
        ['Make a screen usable with a keyboard alone'], 75),
      u('ONE_INTERFACE_EVERY_SIZE', 'One Interface, Every Size',
        'Responsive layout without a second codebase.',
        ['Build one layout that works on a phone and a monitor'], 70,
        { after: ['KEYBOARD_AND_SCREEN_READER'] }),
      u('FRONTEND_PERFORMANCE', 'What Is Making It Slow',
        'Bundle size, renders and images, measured rather than guessed.',
        ['Find and fix the thing actually making a page slow'], 75,
        { after: ['ONE_INTERFACE_EVERY_SIZE'] }),
    ],
  },
  T3_FRONTEND_PROJECT: {
    category: 'DIRECTION',
    units: [
      u('BRIEF', 'Production Frontend Project — the Brief',
        'What you are building, for whom, and what done means.',
        ['Write a brief with a definition of done you can be held to'], 60),
      u('BUILD', 'Building It',
        'Real data, real errors, real empty states, tests and a deployment.',
        ['Ship an interface with real data, real failures and a deployment'],
        200, { unitType: 'PROJECT', after: ['BRIEF'] }),
      u('EXPLAIN', 'Explaining Every Decision in It',
        'Why this state lives there, why this component exists.',
        ['Defend every significant decision in your project'], 70, { after: ['BUILD'] }),
    ],
  },

  /* ── S14 · Data and analytics ────────────────────────────────────────────────────────── */
  T3_DATA_COLLECT: {
    category: 'DIRECTION',
    units: [
      u('GETTING_DATA_OUT', 'Getting Data Out of Files, APIs and a Database',
        'Three sources, three sets of problems, one dataframe at the end.',
        ['Load data from a file, an API and a database'], 75),
      u('WHAT_IS_WRONG_WITH_IT', 'What Is Wrong With It Before You Use It',
        'Missing values, duplicates, wrong types and the row that is a header.',
        ['Profile a dataset and say what is wrong before analysing it'], 75,
        { after: ['GETTING_DATA_OUT'] }),
      u('DATA_QUALITY_RULES', 'Writing Down What Good Looks Like',
        'Checks that run every time rather than an eyeball each morning.',
        ['Express a data quality rule as a check that runs'], 65, { after: ['WHAT_IS_WRONG_WITH_IT'] }),
      ...closeOut('Data Collection', 'DATA_QUALITY_RULES'),
    ],
  },
  T3_DATA_PIPELINE: {
    category: 'DIRECTION',
    units: [
      u('CLEANING_REPEATABLY', 'Cleaning That Can Be Rerun',
        'A notebook you ran once is not a pipeline. Making the transformation repeatable.',
        ['Turn an ad-hoc clean into something that runs the same way twice'], 80),
      u('IDEMPOTENCE', 'What Happens on a Rerun',
        'Running it twice must not double the data. The single most common pipeline bug.',
        ['Make a pipeline safe to rerun'], 75, { after: ['CLEANING_REPEATABLY'] }),
      u('WHEN_IT_FAILS_HALFWAY', 'When It Fails Halfway',
        'Partial state, retries and knowing which rows made it.',
        ['Recover a pipeline that failed in the middle'], 70, { after: ['IDEMPOTENCE'] }),
      ...closeOut('Data Pipelines', 'WHEN_IT_FAILS_HALFWAY'),
    ],
  },
  T3_DATA_SQL: {
    category: 'DIRECTION',
    units: [
      u('GROUPING_AND_JOINS', 'Grouping and Joining for an Answer',
        'Aggregation over joined tables, and the duplicate rows a join quietly creates.',
        ['Answer a real question with a grouped join'], 80),
      u('WINDOW_FUNCTIONS', 'Window Functions',
        'Running totals, rankings and comparisons to the previous row.',
        ['Use a window function to answer something GROUP BY cannot'], 80,
        { after: ['GROUPING_AND_JOINS'] }),
      u('ANALYTICAL_PERFORMANCE', 'When the Query Takes Ten Minutes',
        'Reading the plan on an analytical query, and what actually helps.',
        ['Speed up an analytical query and prove it'], 70, { after: ['WINDOW_FUNCTIONS'] }),
      ...closeOut('SQL for Analysis', 'ANALYTICAL_PERFORMANCE'),
    ],
  },
  T3_DATA_ANALYSIS: {
    category: 'DIRECTION',
    units: [
      u('THE_QUESTION_FIRST', 'Start From the Question, Not the Data',
        'What decision is waiting on this, and what answer would change it.',
        ['State the question and the decision before opening the data'], 65),
      u('EXPLORING', 'Exploratory Analysis',
        'Distributions, outliers and the relationships worth following.',
        ['Explore a dataset and report what is actually in it'], 80, { after: ['THE_QUESTION_FIRST'] }),
      u('SIGNAL_OR_NOISE', 'Is That Difference Real',
        'Variation, sample size and not acting on noise.',
        ['Say when a difference is worth acting on'], 75, { after: ['EXPLORING'] }),
      ...closeOut('Data Analysis', 'SIGNAL_OR_NOISE'),
    ],
  },
  T3_DATA_VIZ: {
    category: 'DIRECTION',
    units: [
      u('CHART_FOR_THE_QUESTION', 'A Chart That Answers the Question Asked',
        'Choosing the form from the question rather than from what looks impressive.',
        ['Choose a chart that answers the question, not one that flatters the number'], 70),
      u('MISLEADING_CHARTS', 'How a Chart Lies',
        'Truncated axes, wrong aggregation and the dual axis. Usually by accident.',
        ['Spot and avoid the common ways a chart misleads'], 60, { after: ['CHART_FOR_THE_QUESTION'] }),
      u('WRITING_THE_FINDING', 'Writing It So Somebody Can Act',
        'The finding, the confidence, and what you would do about it — without the notebook.',
        ['Write a finding somebody can act on without reading your code'], 70,
        { after: ['MISLEADING_CHARTS'] }),
    ],
  },
  T3_DATA_PROJECT: {
    category: 'DIRECTION',
    units: [
      u('BRIEF', 'Analytics Project — the Brief',
        'The question, the data you will use, and what an answer would look like.',
        ['Write a brief with a question worth answering'], 60),
      u('BUILD', 'Doing the Analysis',
        'Raw data to a defensible answer, with the cleaning and the caveats kept.',
        ['Take one question from raw data to a defensible answer'],
        190, { unitType: 'PROJECT', after: ['BRIEF'] }),
      u('PRESENT', 'Presenting the Answer',
        'To somebody who will not read the code and may disagree with the result.',
        ['Present a finding and defend the method'], 70, { after: ['BUILD'] }),
    ],
  },

  /* ── S15 · AI and machine learning ───────────────────────────────────────────────────── */
  T3_ML_WORKFLOW: {
    category: 'DIRECTION',
    units: [
      u('THE_SPLIT_COMES_FIRST', 'Split Before You Look',
        'Every decision made after seeing the test set is contaminated. Why the split is step one.',
        ['Split data correctly and say why the order matters'], 75),
      u('FROM_DATA_TO_FEATURES', 'From Rows to Features',
        'What a model can actually consume, and the encoding decisions in between.',
        ['Turn a raw table into a feature matrix'], 80, { after: ['THE_SPLIT_COMES_FIRST'] }),
      u('A_BASELINE_FIRST', 'Always Have a Baseline',
        'The dumbest model that could work, so you know whether the clever one earned anything.',
        ['Establish a baseline before training anything real'], 65, { after: ['FROM_DATA_TO_FEATURES'] }),
      ...closeOut('ML Workflow', 'A_BASELINE_FIRST'),
    ],
  },
  T3_ML_SUPERVISED: {
    category: 'DIRECTION',
    units: [
      u('REGRESSION', 'Predicting a Number',
        'Linear models, what they assume, and reading the coefficients honestly.',
        ['Fit and interpret a regression'], 80),
      u('CLASSIFICATION', 'Predicting a Class',
        'Logistic regression and trees, and the threshold nobody mentions.',
        ['Fit a classifier and choose its threshold deliberately'], 80, { after: ['REGRESSION'] }),
      u('WHICH_QUESTION', 'Which Question Each One Answers',
        'Choosing the model family from the question rather than from familiarity.',
        ['Say which model family a problem calls for'], 60, { after: ['CLASSIFICATION'] }),
      ...closeOut('Supervised Learning', 'WHICH_QUESTION'),
    ],
  },
  T3_ML_FEATURES: {
    category: 'DIRECTION',
    units: [
      u('ENCODING_AND_SCALING', 'Encoding and Scaling',
        'Categories, magnitudes and the transformations a model needs.',
        ['Encode and scale features appropriately for a chosen model'], 75),
      u('LEAKAGE', 'Leaking the Answer Into the Features',
        'The bug that makes a model look brilliant in training and useless in production.',
        ['Find and remove leakage from a feature set'], 80, { after: ['ENCODING_AND_SCALING'] }),
      u('FEATURES_FROM_DOMAIN', 'Features That Come From Understanding the Problem',
        'The ones that actually move a score are usually domain knowledge, not transformation.',
        ['Build a feature from domain understanding and show its effect'], 70, { after: ['LEAKAGE'] }),
      ...closeOut('Feature Engineering', 'FEATURES_FROM_DOMAIN'),
    ],
  },
  T3_ML_EVALUATION: {
    category: 'DIRECTION',
    units: [
      u('WHICH_METRIC', 'Which Metric to Believe',
        'Accuracy on imbalanced data is a lie. Precision, recall and choosing from the cost of being wrong.',
        ['Choose a metric from the cost of each kind of error'], 80),
      u('OVERFITTING', 'What Overfitting Looks Like',
        'The gap between training and validation, and what to do about it.',
        ['Recognise overfitting and reduce it'], 75, { after: ['WHICH_METRIC'] }),
      u('RESPONSIBLE_USE', 'Who It Is Wrong About',
        'Bias in the data becomes bias in the model. Checking before it is deployed.',
        ['Check whose predictions are worse, and say what you would do'], 70, { after: ['OVERFITTING'] }),
      ...closeOut('ML Evaluation', 'RESPONSIBLE_USE'),
    ],
  },
  T3_ML_PIPELINES: {
    category: 'DIRECTION',
    units: [
      u('REPRODUCIBLE', 'Getting the Same Result Twice',
        'Seeds, versions and the pipeline that makes a result reproducible.',
        ['Make a result reproducible by somebody else'], 75),
      u('TRACKING_EXPERIMENTS', 'Knowing Which Change Moved the Score',
        'Recording what you tried, so improvement is attributable rather than remembered.',
        ['Track experiments so a score change can be explained'], 65, { after: ['REPRODUCIBLE'] }),
    ],
  },
  T3_ML_PROJECT: {
    category: 'DIRECTION',
    units: [
      u('BRIEF', 'Applied ML Project — the Brief',
        'The prediction, the data, the metric, and what would make it useful.',
        ['Write a brief with a metric chosen before training'], 60),
      u('BUILD', 'Building the Model',
        'Data to features to a model you can defend the evaluation of.',
        ['Take one problem from data to an evaluated model'],
        190, { unitType: 'PROJECT', after: ['BRIEF'] }),
      u('EXPLAIN', 'Defending the Evaluation',
        'Why this metric, why this baseline, and where the model is weakest.',
        ['Defend your evaluation, including where the model fails'], 70, { after: ['BUILD'] }),
    ],
  },

  /* ── S16 · Cloud and DevOps ──────────────────────────────────────────────────────────── */
  T3_CLOUD_INFRA: {
    category: 'DIRECTION',
    units: [
      u('COMPUTE_AND_STORAGE', 'Compute and Storage, Chosen',
        'The handful of primitives most applications need, and the ones they do not.',
        ['Choose the compute and storage a given application needs'], 80),
      u('CLOUD_NETWORKING', 'Networking in a Cloud',
        'Private networks, subnets and what is reachable from where.',
        ['Reason about what can reach what, and close what should not'], 80,
        { after: ['COMPUTE_AND_STORAGE'] }),
      u('WHAT_IT_COSTS', 'What It Costs',
        'The bill as an engineering constraint, and the choices that quietly drive it.',
        ['Estimate what an architecture will cost to run'], 60, { after: ['CLOUD_NETWORKING'] }),
      ...closeOut('Cloud Infrastructure', 'WHAT_IT_COSTS'),
    ],
  },
  T3_CLOUD_CONTAINERS: {
    category: 'DIRECTION',
    units: [
      u('IMAGE_FOR_PRODUCTION', 'An Image Fit for Production',
        'Small, cached well, non-root, and without your secrets baked in.',
        ['Build a production-quality image'], 80),
      u('RUNNING_IT_SOMEWHERE_REAL', 'Running It Somewhere Real',
        'Health checks, restarts and what the platform does when it dies.',
        ['Run a container on a real platform with health checks'], 80,
        { after: ['IMAGE_FOR_PRODUCTION'] }),
      u('WHEN_IT_WILL_NOT_START', 'When It Will Not Start',
        'Reading the logs of something that exited in two seconds.',
        ['Debug a container that fails immediately'], 70, { after: ['RUNNING_IT_SOMEWHERE_REAL'] }),
      ...closeOut('Containers in Production', 'WHEN_IT_WILL_NOT_START'),
    ],
  },
  T3_CICD_MONITORING: {
    category: 'DIRECTION',
    units: [
      u('BUILDING_A_PIPELINE', 'Building the Pipeline',
        'Build, test, deploy — triggered by a merge, with nobody remembering a step.',
        ['Build a pipeline that ships without manual steps'], 90),
      u('WHAT_BLOCKS_A_DEPLOY', 'What Should Stop a Deploy',
        'Which failures block and which warn, decided before it is 5pm on a Friday.',
        ['Decide what blocks a deploy and defend it'], 60, { after: ['BUILDING_A_PIPELINE'] }),
      u('MONITORING_WHAT_MATTERS', 'Monitoring the Few Things That Matter',
        'Errors, latency, saturation — and alerting that does not train people to ignore it.',
        ['Choose signals that catch real problems without crying wolf'], 75,
        { after: ['WHAT_BLOCKS_A_DEPLOY'] }),
      ...closeOut('CI/CD and Monitoring', 'MONITORING_WHAT_MATTERS'),
    ],
  },
  T3_CLOUD_CONFIG: {
    category: 'DIRECTION',
    units: [
      u('ONE_BUILD_THREE_ENVIRONMENTS', 'One Build, Three Environments',
        'The same artefact everywhere, differing only in configuration.',
        ['Run one build in three environments without rebuilding it'], 70),
      u('SECRETS_IN_INFRASTRUCTURE', 'Secrets, Properly',
        'A secret store, rotation, and never in an image or a repository.',
        ['Supply secrets to a running service safely'], 70,
        { after: ['ONE_BUILD_THREE_ENVIRONMENTS'] }),
    ],
  },
  T3_CLOUD_SECURITY: {
    category: 'DIRECTION',
    units: [
      u('LEAST_ACCESS', 'The Least Access It Can Work With',
        'Roles and policies, and why the default is almost always too much.',
        ['Give a component the least access it needs'], 75),
      u('WHAT_IS_EXPOSED', 'What Is Exposed to the Internet',
        'Auditing what is reachable, and closing what does not need to be.',
        ['Audit and reduce what is publicly reachable'], 70, { after: ['LEAST_ACCESS'] }),
    ],
  },
  T3_CLOUD_PROJECT: {
    category: 'DIRECTION',
    units: [
      u('BRIEF', 'Deployment Project — the Brief',
        'What you are deploying, where, and what "running properly" means.',
        ['Write a brief with a definition of running properly'], 60),
      u('BUILD', 'Taking It From Repository to Running Service',
        'Containerised, pipelined, monitored and redeployable.',
        ['Take one application from a repository to a monitored service'],
        190, { unitType: 'PROJECT', after: ['BRIEF'] }),
      u('EXPLAIN', 'Explaining the Infrastructure',
        'Why this shape, what it costs, and how you would roll it back.',
        ['Defend the infrastructure decisions, including the cost'], 70, { after: ['BUILD'] }),
    ],
  },

  /* ── S17 · Cybersecurity ─────────────────────────────────────────────────────────────── */
  T3_SEC_THREATS: {
    category: 'DIRECTION',
    units: [
      u('MODELLING_A_REAL_SYSTEM', 'Modelling a Real System',
        'Assets, entry points and trust boundaries on an application that exists.',
        ['Produce a threat model for a real application'], 85),
      u('COMMON_VULNERABILITY_CLASSES', 'The Classes That Account for Most Breaches',
        'A small number of categories cause most real incidents. Knowing them by shape.',
        ['Recognise the common vulnerability classes in unfamiliar code'], 80,
        { after: ['MODELLING_A_REAL_SYSTEM'] }),
      u('RANKING_WHAT_TO_FIX', 'What to Fix First',
        'Likelihood against impact, with limited time.',
        ['Rank findings so the first fix is the right one'], 60,
        { after: ['COMMON_VULNERABILITY_CLASSES'] }),
      ...closeOut('Threat Modelling', 'RANKING_WHAT_TO_FIX'),
    ],
  },
  T3_SEC_APPSEC: {
    category: 'DIRECTION',
    units: [
      u('FINDING_INJECTION', 'Finding Injection in Code You Did Not Write',
        'Where untrusted data reaches an interpreter, traced through a real codebase.',
        ['Trace untrusted input to a dangerous sink'], 85),
      u('XSS_AND_CSRF_IN_PRACTICE', 'XSS and CSRF Against a Real Application',
        'Exploiting and then fixing both, on something that actually runs.',
        ['Exploit and fix an XSS and a CSRF'], 85, { after: ['FINDING_INJECTION'] }),
      u('BROKEN_ACCESS', 'Broken Access Control',
        'Changing the id in the URL — the simplest real attack, and the commonest.',
        ['Find and fix a broken access check'], 75, { after: ['XSS_AND_CSRF_IN_PRACTICE'] }),
      ...closeOut('Application Security', 'BROKEN_ACCESS'),
    ],
  },
  T3_SEC_NETWORK: {
    category: 'DIRECTION',
    units: [
      u('WHAT_IS_LISTENING', 'What Is Listening, and Why',
        'Ports, services and the attack surface nobody meant to leave open.',
        ['Audit what a machine exposes and close what it does not need'], 75),
      u('TLS_PROPERLY', 'Transport Security, Properly',
        'Certificates, what TLS does and does not protect, and the misconfigurations that undo it.',
        ['Say what TLS protects and configure it correctly'], 70, { after: ['WHAT_IS_LISTENING'] }),
    ],
  },
  T3_SEC_TESTING: {
    category: 'DIRECTION',
    units: [
      u('TESTING_AGAINST_THE_MODEL', 'Testing Against Your Own Threat Model',
        'Turning each predicted weakness into something you actually try.',
        ['Test an application for the weaknesses the model predicted'], 85),
      u('TOOLS_AND_THEIR_LIMITS', 'Scanners, and What They Miss',
        'Automated tools find the known shapes. Business logic flaws need a person.',
        ['Use a scanner and say what it cannot find'], 70, { after: ['TESTING_AGAINST_THE_MODEL'] }),
      u('WRITING_IT_UP', 'A Finding Somebody Will Act On',
        'Reproduction, impact and a fix — not a scanner dump.',
        ['Write a finding a developer can act on'], 70, { after: ['TOOLS_AND_THEIR_LIMITS'] }),
      ...closeOut('Security Testing', 'WRITING_IT_UP'),
    ],
  },
  T3_SEC_LIFECYCLE: {
    category: 'DIRECTION',
    units: [
      u('SECURITY_IN_THE_WORKFLOW', 'Security in How the Team Works',
        'Review, dependency checks and pipeline gates, rather than an audit at the end.',
        ['Put a security check where it runs every time'], 75),
      u('WHEN_SOMETHING_HAPPENS', 'When Something Actually Happens',
        'Detection, containment and the log you wish you had kept.',
        ['Describe the first hour of an incident'], 70, { after: ['SECURITY_IN_THE_WORKFLOW'] }),
    ],
  },
  T3_SEC_PROJECT: {
    category: 'DIRECTION',
    units: [
      u('BRIEF', 'Security Project — the Brief',
        'What you are assessing, the scope, and the rules you are working inside.',
        ['Write a brief with an explicit scope and rules of engagement'], 60),
      u('BUILD', 'Assessing It End to End',
        'Model, test, exploit, fix and verify on one real application.',
        ['Assess one application end to end and fix what you found'],
        190, { unitType: 'PROJECT', after: ['BRIEF'] }),
      u('REPORT', 'The Report',
        'What you found, how bad it is, and exactly how to fix it.',
        ['Write a report a team can work from'], 75, { after: ['BUILD'] }),
    ],
  },

  /* ── S18 · Mobile ────────────────────────────────────────────────────────────────────── */
  T3_MOBILE_APP: {
    category: 'DIRECTION',
    units: [
      u('SCREENS_AND_NAVIGATION', 'Screens, Navigation and the Back Button',
        'A stack of screens is not a set of pages. What changes on a device.',
        ['Build navigation that behaves the way a device user expects'], 80),
      u('STATE_ON_A_DEVICE', 'State That Survives a Rotation',
        'Lifecycle, backgrounding and the app being killed while you were not looking.',
        ['Keep state across a lifecycle event'], 80, { after: ['SCREENS_AND_NAVIGATION'] }),
      ...closeOut('Mobile Applications', 'STATE_ON_A_DEVICE'),
    ],
  },
  T3_MOBILE_DATA: {
    category: 'DIRECTION',
    units: [
      u('LOCAL_STORAGE', 'Storing Things on the Device',
        'What belongs on the device, and what must never be kept there.',
        ['Store data locally, and keep what is sensitive out of it'], 75),
      u('OFFLINE', 'Usable With No Signal',
        'Designing for the tunnel, the lift and the train.',
        ['Keep an app usable with no network'], 80, { after: ['LOCAL_STORAGE'] }),
      u('SYNC_AND_CONFLICT', 'When the Signal Comes Back',
        'Reconciling what changed in both places. The genuinely hard part.',
        ['Reconcile changes made offline with changes made elsewhere'], 85, { after: ['OFFLINE'] }),
      ...closeOut('Mobile Data', 'SYNC_AND_CONFLICT'),
    ],
  },
  T3_MOBILE_API: {
    category: 'DIRECTION',
    units: [
      u('CALLING_AN_API', 'Calling an API From a Device',
        'Slow networks, retries and a request that outlives the screen that made it.',
        ['Call an API from a device and handle a slow or failed network'], 75),
      u('LOGIN_THAT_PERSISTS', 'A Login That Survives a Restart',
        'Keeping a credential on a device safely, and refreshing it.',
        ['Keep somebody logged in across restarts without storing it unsafely'], 75,
        { after: ['CALLING_AN_API'] }),
    ],
  },
  T3_MOBILE_QUALITY: {
    category: 'DIRECTION',
    units: [
      u('BATTERY_AND_FRAMES', 'What Is Draining the Battery',
        'Wakeups, polling and the work that should not be happening.',
        ['Find what is draining battery or dropping frames, and prove the fix'], 80),
      u('TESTING_ON_DEVICES', 'Testing on Something Real',
        'Emulators lie about performance. What to test on a device.',
        ['Test on a real device and say what the emulator hid'], 65,
        { after: ['BATTERY_AND_FRAMES'] }),
    ],
  },
  T3_MOBILE_PROJECT: {
    category: 'DIRECTION',
    units: [
      u('BRIEF', 'Mobile Project — the Brief',
        'What you are building and what it must do without a network.',
        ['Write a brief including the offline behaviour'], 60),
      u('BUILD', 'Building and Shipping It',
        'Data, auth, offline and a release build on a real device.',
        ['Ship an app onto a real device with data and auth'],
        190, { unitType: 'PROJECT', after: ['BRIEF'] }),
      u('EXPLAIN', 'Explaining the Decisions',
        'Why this storage, why this sync, what you would do with more time.',
        ['Defend the significant decisions in your app'], 70, { after: ['BUILD'] }),
    ],
  },

  /* ── S18B · Software engineering ─────────────────────────────────────────────────────── */
  T3_SWE_DESIGN: {
    category: 'DIRECTION',
    units: [
      u('READING_A_REQUIREMENT', 'Reading a Requirement Properly',
        'What is being asked, what is assumed, and the question whose answer changes the design.',
        ['Turn a vague request into something you could build from'], 70),
      u('SKETCHING_A_DESIGN', 'Sketching Before Typing',
        'Components, responsibilities and the data between them — on paper, where changing it is free.',
        ['Produce a design another engineer could build from'], 80, { after: ['READING_A_REQUIREMENT'] }),
      u('SAYING_WHAT_IT_IS_NOT', 'Saying What It Deliberately Does Not Do',
        'Scope named at the start, when it is a sentence rather than three weeks.',
        ['State what is out of scope and why'], 60, { after: ['SKETCHING_A_DESIGN'] }),
      ...closeOut('Software Design', 'SAYING_WHAT_IT_IS_NOT'),
    ],
  },
  T3_SWE_QUALITY: {
    category: 'DIRECTION',
    units: [
      u('TESTS_THIS_DESIGN_NEEDS', 'The Tests This Design Invites',
        'Every design has characteristic ways of going wrong. Choosing tests from those.',
        ['Choose tests from how this design could fail, not from a checklist'], 80),
      u('REVIEWING_WELL', 'Reviewing So It Gets Fixed',
        'Understanding first, correctness before style, and wording that keeps the author willing.',
        ['Review a change so the defect is fixed and the next one still arrives'], 70,
        { after: ['TESTS_THIS_DESIGN_NEEDS'] }),
      u('BEING_REVIEWED', 'Being Reviewed Without Defending',
        'Answering a comment you disagree with, and why silent compliance is its own failure.',
        ['Answer a review honestly, and change your mind in public when you were wrong'], 60,
        { after: ['REVIEWING_WELL'] }),
      ...closeOut('Engineering Quality', 'BEING_REVIEWED'),
    ],
  },
  T3_SWE_EVOLVING: {
    category: 'DIRECTION',
    units: [
      u('READING_UNFAMILIAR_CODE', 'Reading Code You Did Not Write',
        'Finding the thread that matters in a codebase too large to read end to end.',
        ['Find where a behaviour lives in an unfamiliar codebase'], 80),
      u('CHANGING_IT_SAFELY', 'Changing It Without Breaking It',
        'A characterisation test first, then the change — the order that makes it safe.',
        ['Make a safe change in code with no tests around it'], 80, { after: ['READING_UNFAMILIAR_CODE'] }),
      u('DEBT_ON_PURPOSE', 'Debt Taken on Purpose',
        'A shortcut named, costed and written down is a decision. One nobody mentioned is a trap.',
        ['Name what a shortcut will cost and decide whether to take it'], 65,
        { after: ['CHANGING_IT_SAFELY'] }),
      ...closeOut('Evolving Code', 'DEBT_ON_PURPOSE'),
    ],
  },
  T3_SWE_WORKFLOW: {
    category: 'DIRECTION',
    units: [
      u('BRANCH_AND_REVIEW', 'Branch, Review, Merge',
        'The loop a team actually works in, and why small changes make it work.',
        ['Work a change through a branch-and-review workflow'], 70),
      u('PIPELINE_DOES_THE_SHIPPING', 'Let the Pipeline Ship It',
        'Nobody remembers a step at 6pm on a Friday. The pipeline does.',
        ['Ship through a pipeline rather than by hand'], 70, { after: ['BRANCH_AND_REVIEW'] }),
    ],
  },
  T3_SWE_DOCS: {
    category: 'DIRECTION',
    units: [
      u('WHY_IT_IS_THIS_WAY', 'Writing Down Why',
        'The code says what. Only a person can say why, and only before they forget.',
        ['Write a decision record the next engineer can act on'], 65),
      u('WHAT_IT_DOES_AT_3AM', 'What It Does at 3am',
        'Logs and diagnostics as a message to whoever is woken up — possibly you.',
        ['Leave enough behind to explain a failure without reproducing it'], 65,
        { after: ['WHY_IT_IS_THIS_WAY'] }),
    ],
  },
  T3_SWE_PROJECT: {
    category: 'DIRECTION',
    units: [
      u('BRIEF', 'Software Engineering Project — the Brief',
        'What you are building, how you will know it is good, and what is out of scope.',
        ['Write a brief with a quality bar you can be held to'], 60),
      u('BUILD', 'Building It the Way a Team Would',
        'Designed, tested, reviewed, documented and shipped through a pipeline.',
        ['Build one system to a standard a team would accept'],
        200, { unitType: 'PROJECT', after: ['BRIEF'] }),
      u('EXPLAIN', 'Defending the Design',
        'Why this shape, what you rejected, and what you would change with more time.',
        ['Defend the design against the alternative you did not take'], 70, { after: ['BUILD'] }),
    ],
  },

  /* ── S18C · Full-stack ───────────────────────────────────────────────────────────────── */
  T3_FS_BOUNDARY: {
    category: 'DIRECTION',
    units: [
      u('THE_CONTRACT', 'The Contract Between the Halves',
        'What the interface may assume and what the service promises — agreed, not inferred.',
        ['Design an API contract neither side has to guess at'], 80),
      u('WHAT_THE_CLIENT_KEEPS', 'What the Client Keeps',
        'Cached, derived or asked for every time — and the stale screen that answers it wrongly.',
        ['Decide what the client holds and what it re-fetches'], 75, { after: ['THE_CONTRACT'] }),
      u('CHANGING_BOTH_SIDES', 'Changing Both Sides at Once',
        'Shipping a change that spans the seam without breaking whichever deploys first.',
        ['Make a change across the boundary without a broken minute in between'], 75,
        { after: ['WHAT_THE_CLIENT_KEEPS'] }),
      ...closeOut('The Front-Back Seam', 'CHANGING_BOTH_SIDES'),
    ],
  },
  T3_FS_AUTH: {
    category: 'DIRECTION',
    units: [
      u('LOGIN_END_TO_END', 'A Login, All the Way Down',
        'From the form to the token to the row, and what is checked at each step.',
        ['Carry an identity from a form to a database row'], 85),
      u('NEVER_TRUST_THE_CLIENT', 'Never Trust the Client',
        'Why the useful checks are the ones the browser cannot skip.',
        ['Keep the client honest without relying on it'], 75, { after: ['LOGIN_END_TO_END'] }),
      ...closeOut('Full-Stack Auth', 'NEVER_TRUST_THE_CLIENT'),
    ],
  },
  T3_FS_DATA: {
    category: 'DIRECTION',
    units: [
      u('ONE_IDEA_THREE_SHAPES', 'One Idea, Three Shapes',
        'A row, a response and a screen are the same thing dressed differently. Keeping them honest.',
        ['Keep one concept coherent from table to screen'], 80),
      u('WHERE_TO_TRANSFORM', 'Where the Transformation Belongs',
        'In the query, the service or the component — and what each choice costs later.',
        ['Put a transformation where it will still make sense in a year'], 70,
        { after: ['ONE_IDEA_THREE_SHAPES'] }),
      ...closeOut('Full-Stack Data', 'WHERE_TO_TRANSFORM'),
    ],
  },
  T3_FS_QUALITY: {
    category: 'DIRECTION',
    units: [
      u('EACH_HALF_ALONE', 'Testing Each Half Alone',
        'Fast tests either side of the seam, and the mocks that must not become the test.',
        ['Test both halves independently without testing your mocks'], 75),
      u('AND_THE_SEAM', 'And Then the Seam',
        'The integration test that catches what neither half can see on its own.',
        ['Test across the boundary, and say which failure it catches'], 75, { after: ['EACH_HALF_ALONE'] }),
    ],
  },
  T3_FS_DEPLOY: {
    category: 'DIRECTION',
    units: [
      u('SHIPPING_THREE_THINGS', 'Shipping Three Things Together',
        'Interface, service and schema, released in an order that never leaves a broken pair.',
        ['Deploy all three parts without a broken window between them'], 85),
      u('ROLLING_ALL_THREE_BACK', 'Rolling All Three Back',
        'Including the migration, which is the part that does not undo itself.',
        ['Roll back a full-stack release, schema included'], 75, { after: ['SHIPPING_THREE_THINGS'] }),
    ],
  },
  T3_FS_PROJECT: {
    category: 'DIRECTION',
    units: [
      u('BRIEF', 'Full-Stack Project — the Brief',
        'One application, both halves, and what done means for each.',
        ['Write a brief covering interface, service and data'], 60),
      u('BUILD', 'Building the Whole Thing',
        'Interface, service, data, auth and a deployment — finished, not demonstrated.',
        ['Ship one application end to end'],
        210, { unitType: 'PROJECT', after: ['BRIEF'] }),
      u('EXPLAIN', 'Explaining the Seam',
        'Where the boundary is, why there, and what it cost you.',
        ['Defend where you drew the line between the halves'], 70, { after: ['BUILD'] }),
    ],
  },
  /* ── S19 · AI-assisted engineering (everybody) ───────────────────────────────────────── */
  T3_AI_ASSISTED: {
    category: 'UNIVERSAL',
    units: [
      u('WHAT_IT_IS_GOOD_AT', 'What an Assistant Is Actually Good At',
        'Explanation, boilerplate, tests and a first draft. And what it is not good at.',
        ['Use an assistant where it helps and not where it does not'], 60),
      u('REVIEWING_GENERATED_CODE', 'Reviewing What It Produced',
        'The same review you would give a colleague, applied to a very confident one.',
        ['Review generated code as strictly as a colleague’s'], 70,
        { after: ['WHAT_IT_IS_GOOD_AT'] }),
      u('CONFIDENT_AND_WRONG', 'Noticing a Confident Wrong Answer',
        'Invented APIs, subtly wrong logic, and why fluency is not correctness.',
        ['Spot a plausible answer that is wrong'], 70, { after: ['REVIEWING_GENERATED_CODE'] }),
      u('NEVER_SHIP_WHAT_YOU_CANNOT_EXPLAIN', 'Never Ship What You Cannot Explain',
        'The line that keeps the tool useful: you are still the engineer who owns it.',
        ['Explain every line of code you are about to ship'], 55, { after: ['CONFIDENT_AND_WRONG'] }),
    ],
  },
};
