import React, { useEffect, useState, useCallback, useMemo } from 'react';
import { attendanceApi, batchApi } from '../../api';
import { Alert, Spinner } from '../../components/common';
import { Attendance, AttendanceSummary, Batch } from '../../types';
import { useAuth } from '../../contexts/AuthContext';
import './MyAttendancePage.css';

const localDate=(d:Date=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
type Preset='thisMonth'|'lastMonth'|'thisWeek'|'last7'|'custom';
const labels:Record<Preset,string>={thisMonth:'This Month',lastMonth:'Last Month',thisWeek:'This Week',last7:'Last 7 Days',custom:'Custom Range'};
const range=(p:Preset)=>{const t=new Date();if(p==='thisMonth')return{from:localDate(new Date(t.getFullYear(),t.getMonth(),1)),to:localDate(t)};if(p==='lastMonth')return{from:localDate(new Date(t.getFullYear(),t.getMonth()-1,1)),to:localDate(new Date(t.getFullYear(),t.getMonth(),0))};if(p==='thisWeek'){const d=new Date(t);d.setDate(d.getDate()-((d.getDay()+6)%7));return{from:localDate(d),to:localDate(t)}}if(p==='last7'){const d=new Date(t);d.setDate(d.getDate()-6);return{from:localDate(d),to:localDate(t)}}return{from:localDate(t),to:localDate(t)}};
const cap=(s:string)=>s.charAt(0).toUpperCase()+s.slice(1);

export default function MyAttendancePage(){
 const {user}=useAuth(); const initial=range('thisMonth');
 const [batch,setBatch]=useState<Batch|null>(null),[records,setRecords]=useState<Attendance[]>([]),[summary,setSummary]=useState<AttendanceSummary|null>(null);
 const [loading,setLoading]=useState(true),[fetching,setFetching]=useState(false),[error,setError]=useState('');
 const [from,setFrom]=useState(initial.from),[to,setTo]=useState(initial.to),[preset,setPreset]=useState<Preset>('thisMonth'); const [page,setPage]=useState(1),[perPage,setPerPage]=useState(7);
 const fetchRecords=useCallback(async(f:string,t:string)=>{if(!user?._id)return;try{setError('');setFetching(true);const r=await attendanceApi.getStudentAttendance(user._id,f,t);const data:Attendance[]=r.data||[];data.sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());setRecords(data);setPage(1)}catch(e:any){setError(e.message||'Failed to fetch attendance')}finally{setFetching(false)}},[user]);
 useEffect(()=>{(async()=>{try{setLoading(true);if(user?.batchId){const r=await batchApi.getBatchById(user.batchId);const b=r.data||r;setBatch(b);if(user._id){const s=await attendanceApi.getStudentAttendanceSummary(user._id,user.batchId);setSummary(s.data||null)}await fetchRecords(initial.from,initial.to)}}catch(e:any){setError(e.message||'Failed to fetch batch')}finally{setLoading(false)}})()},[user]); // eslint-disable-line
 const minDate=()=>{if(!batch||!user)return'';const b=batch.startDate?new Date(batch.startDate):null,u=user.createdAt?new Date(user.createdAt):null;const d=b&&u?(b>u?b:u):(b||u);return d?d.toISOString().split('T')[0]:''};
 const maxTo=()=>{const today=localDate();if(!batch?.endDate)return today;const e=localDate(new Date(batch.endDate));return e<today?e:today};
 const applyPreset=(p:Preset)=>{setPreset(p);if(p==='custom')return;const r=range(p);setFrom(r.from);setTo(r.to);fetchRecords(r.from,r.to)};
 const filter=()=>{if(!from||!to)return setError('Please select both from and to dates');if(new Date(from)>new Date(to))return setError('From date cannot be greater than to date');fetchRecords(from,to)};
 const rangeSummary=useMemo(()=>{const present=records.filter(a=>a.status==='present').length,absent=records.filter(a=>a.status==='absent').length,leave=records.filter(a=>a.status==='leave').length,total=records.length;return{total,present,absent,leave,percentage:total?Math.round(present/total*100):0}},[records]);
 const display=records.length?rangeSummary:(summary||rangeSummary), pct=(n:number)=>display.total?Math.round(n/display.total*100):0;
 const rating=display.percentage>=90?'Excellent':display.percentage>=75?'Good':display.percentage>=50?'Needs attention':'Low attendance';
 const pages=Math.max(1,Math.ceil(records.length/perPage)),start=(page-1)*perPage,shown=records.slice(start,start+perPage);
 const pageNums=():Array<number|'…'>=>pages<=5?Array.from({length:pages},(_,i)=>i+1):page<=3?[1,2,3,'…',pages]:page>=pages-2?[1,'…',pages-2,pages-1,pages]:[1,'…',page,'…',pages];
 if(loading)return <Spinner fullScreen/>;
 return <div className="ma-page">
  <header className="ma-header"><div><h1>My Attendance</h1><p>Track your class attendance and stay consistent in your learning journey.</p></div>{batch&&<div className="ma-batch"><i className="bi bi-people"/><span>Batch <strong>{batch.name}</strong></span></div>}</header>
  {error&&<Alert type="error" message={error} onClose={()=>setError('')}/>} 
  <section className="ma-top-grid">
   <div className="ma-metric ma-overall"><div><span>OVERALL ATTENDANCE</span><strong>{display.percentage}%</strong><em className={display.percentage>=75?'good':'low'}>{rating}</em><small>{display.present} attended · {display.total} total classes</small></div><div className="ma-ring" style={{'--pct':`${display.percentage*3.6}deg`} as React.CSSProperties}><span>{display.percentage}%</span></div></div>
   <div className="ma-metric"><i className="bi bi-calendar3 blue"/><div><span>SELECTED RANGE</span><strong>{display.present} / {display.total}</strong><small>Classes attended</small><div className="ma-line"><b style={{width:`${display.percentage}%`}}/></div></div></div>
   <div className="ma-metric"><i className="bi bi-check-circle green"/><div><span>PRESENT</span><strong>{display.present}</strong><small>{pct(display.present)}% of classes</small></div></div>
   <div className="ma-metric"><i className="bi bi-x-circle red"/><div><span>ABSENT</span><strong>{display.absent}</strong><small>{pct(display.absent)}% of classes</small></div></div>
   <div className="ma-metric"><i className="bi bi-clock amber"/><div><span>LEAVE</span><strong>{display.leave}</strong><small>{pct(display.leave)}% of classes</small></div></div>
  </section>
  <section className="ma-filterbar"><div className="ma-filter-title"><i className="bi bi-funnel"/><span>Attendance period</span></div><select value={preset} onChange={e=>applyPreset(e.target.value as Preset)}>{(Object.keys(labels) as Preset[]).map(p=><option key={p} value={p}>{labels[p]}</option>)}</select><label>From<input type="date" value={from} min={minDate()} max={localDate()} onChange={e=>{setFrom(e.target.value);setPreset('custom')}}/></label><label>To<input type="date" value={to} min={from||minDate()} max={maxTo()} onChange={e=>{setTo(e.target.value);setPreset('custom')}}/></label><button onClick={filter} disabled={fetching}>{fetching?<><span className="spinner-border spinner-border-sm"/> Loading</>:<><i className="bi bi-search"/> Apply</>}</button></section>
  <div className="ma-content-grid"><main className="ma-card"><div className="ma-card-head"><div><h2>Attendance History</h2><p>Your class-by-class attendance for the selected period.</p></div><div className="ma-legend"><span><i className="present"/>Present</span><span><i className="absent"/>Absent</span><span><i className="leave"/>Leave</span></div></div>
   {!records.length?<div className="ma-empty"><i className="bi bi-calendar-x"/><h3>No attendance records</h3><p>No records were found for the selected dates.</p></div>:<><div className="ma-table-wrap"><table><thead><tr><th>Date</th><th>Day</th><th>Status</th><th>Remarks</th></tr></thead><tbody>{shown.map(r=>{const d=new Date(r.date);return <tr key={r._id}><td data-label="Date"><strong>{d.toLocaleDateString('en-US',{day:'numeric',month:'short',year:'numeric'})}</strong></td><td data-label="Day">{d.toLocaleDateString('en-US',{weekday:'long'})}</td><td data-label="Status"><span className={`ma-badge ${r.status}`}><i className={`bi ${r.status==='present'?'bi-check-lg':r.status==='absent'?'bi-x-lg':'bi-clock'}`}/>{cap(r.status)}</span></td><td data-label="Remarks">{r.remarks||'—'}</td></tr>})}</tbody></table></div><div className="ma-foot"><span>Showing {start+1}–{Math.min(start+perPage,records.length)} of {records.length}</span><div>{pageNums().map((n,i)=>n==='…'?<em key={i}>…</em>:<button key={n} className={page===n?'active':''} onClick={()=>setPage(n as number)}>{n}</button>)}</div><select value={perPage} onChange={e=>{setPerPage(+e.target.value);setPage(1)}}>{[5,7,10,20].map(n=><option key={n}>{n}</option>)}</select></div></>}
  </main><aside><section className="ma-card ma-overview"><h3>Attendance Overview</h3><div className="ma-big-ring" style={{'--pct':`${display.percentage*3.6}deg`} as React.CSSProperties}><span><strong>{display.present}/{display.total}</strong>Classes</span></div><dl><div><dt><i className="present"/>Present</dt><dd>{display.present} ({pct(display.present)}%)</dd></div><div><dt><i className="absent"/>Absent</dt><dd>{display.absent} ({pct(display.absent)}%)</dd></div><div><dt><i className="leave"/>Leave</dt><dd>{display.leave} ({pct(display.leave)}%)</dd></div></dl><div className={`ma-insight ${display.percentage>=75?'good':'warn'}`}><i className={`bi ${display.percentage>=75?'bi-stars':'bi-exclamation-triangle'}`}/><span><strong>{rating}</strong><small>{display.percentage>=75?'You are maintaining good consistency. Keep it up!':'Aim for at least 75% attendance and stay consistent.'}</small></span></div></section>
   <section className="ma-card ma-help"><i className="bi bi-headset"/><div><h3>Need help?</h3><p>If an attendance record looks incorrect, contact your mentor or support team.</p><button onClick={()=>window.location.assign('/ai-mentor')}>Ask AI Mentor <i className="bi bi-arrow-right"/></button></div></section>
  </aside></div>
  <footer className="ma-footer"><i className="bi bi-shield-check"/><div><strong>Good attendance builds a strong foundation for your success.</strong><span>Keep attending classes and make the most of your learning journey.</span></div><button onClick={()=>window.location.assign('/my-learning')}>View My Learning Plan <i className="bi bi-arrow-right"/></button></footer>
 </div>
}
