import express from 'express';
import authRoutes from './authRoutes';
import tenantRoutes from './tenantRoutes';
import courseRoutes from './courseRoutes';
import subjectRoutes from './subjectRoutes';
import chapterRoutes from './chapterRoutes';
import enrollmentRoutes from './enrollmentRoutes';
import userRoutes from './userRoutes';
import roleRoutes from './roleRoutes';
import batchRoutes from './batchRoutes';
import attendanceRoutes from './attendanceRoutes';
import quizRoutes from './quizRoutes';
import questionRoutes from './questionRoutes';
import contentRoutes from './contentRoutes';
import progressRoutes from './progressRoutes';
import studentProfileRoutes from './studentProfileRoutes';
import oauthRoutes from './oauthRoutes';
import assignmentRoutes from './assignmentRoutes';
import dashboardRoutes from './dashboardRoutes';
import studentReportRoutes from './studentReportRoutes';
import interviewQuestionRoutes from './interviewQuestionRoutes';
import mockInterviewRoutes from './mockInterviewRoutes';
import topicRoutes from './topicRoutes';
import subTopicRoutes from './subTopicRoutes';
import leadRoutes from './leadRoutes';
import leadStageRoutes from './leadStageRoutes';
import leadFormConfigRoutes from './leadFormConfigRoutes';
import marketingRoutes from './marketingRoutes';
import codeSnippetRoutes from './codeSnippetRoutes';
import shareRoutes from './shareRoutes';
import topicMasteryRoutes from './topicMasteryRoutes';
import learningRequestRoutes from './learningRequestRoutes';
import adCampaignRoutes from './adCampaignRoutes';
import leadStageHistoryRoutes from './leadStageHistoryRoutes';
import whatsappRoutes from './whatsappRoutes';
import followUpRoutes from './followUpRoutes';
import seatReservationRoutes from './seatReservationRoutes';
import leadPriorityRoutes from './leadPriorityRoutes';
import qualificationRoutes from './qualificationRoutes';
import salesContentRoutes from './salesContentRoutes';
import leadAIRoutes from './leadAIRoutes';
import lostReasonRoutes from './lostReasonRoutes';
import publicLeadRoutes from './publicLeadRoutes';
import metaLeadAdsRoutes from './metaLeadAdsRoutes';
import googleSheetRoutes from './googleSheetRoutes';
import leadScoringRoutes from './leadScoringRoutes';
import interviewTemplateRoutes from './interviewTemplateRoutes';
import classRecordingRoutes from './classRecordingRoutes';
import departmentRoutes from '../college/departmentRoutes';
import membershipRoutes from '../college/membershipRoutes';
import placementDriveRoutes from '../placement/placementDriveRoutes';
import alumniRoutes from '../alumni/alumniRoutes';
import notificationRoutes from '../notifications/notificationRoutes';
// Boot notification listeners
import '../notifications/notificationService';

const router = express.Router();

// PUBLIC ROUTES (no auth required)
router.use('/public', publicLeadRoutes);
router.use('/meta-leads', metaLeadAdsRoutes);

router.use('/auth', authRoutes);
router.use('/tenants', tenantRoutes);
router.use('/courses', courseRoutes);
router.use('/subjects', subjectRoutes);
router.use('/chapters', chapterRoutes);
router.use('/enrollments', enrollmentRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/batches', batchRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/quizzes', quizRoutes);
router.use('/questions', questionRoutes);
router.use('/content', contentRoutes);
router.use('/progress', progressRoutes);
router.use('/student-profile', studentProfileRoutes);
router.use('/oauth', oauthRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/student-reports', studentReportRoutes);
router.use('/interview-questions', interviewQuestionRoutes);
router.use('/mock-interviews', mockInterviewRoutes);
router.use('/topics', topicRoutes);
router.use('/sub-topics', subTopicRoutes);
router.use('/leads', leadRoutes);
router.use('/lead-stages', leadStageRoutes);
router.use('/lead-form-config', leadFormConfigRoutes);
router.use('/marketing', marketingRoutes);
router.use('/code-snippets', codeSnippetRoutes);
router.use('/share', shareRoutes);
router.use('/topic-mastery', topicMasteryRoutes);
router.use('/learning-requests', learningRequestRoutes);
router.use('/campaigns', adCampaignRoutes);
router.use('/stage-history', leadStageHistoryRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/follow-ups', followUpRoutes);
router.use('/seat-reservations', seatReservationRoutes);
router.use('/lead-priority', leadPriorityRoutes);
router.use('/qualification', qualificationRoutes);
router.use('/sales-content', salesContentRoutes);
router.use('/lead-ai', leadAIRoutes);
router.use('/lost-reasons', lostReasonRoutes);
router.use('/google-sheet-integrations', googleSheetRoutes);
router.use('/lead-scoring', leadScoringRoutes);
router.use('/interview-module', interviewTemplateRoutes);
router.use('/class-recordings', classRecordingRoutes);

// ─── College Module ────────────────────────────────────────────────────────────
router.use('/college/departments', departmentRoutes);
router.use('/college/membership', membershipRoutes);
router.use('/college/placement', placementDriveRoutes);
router.use('/college/alumni', alumniRoutes);
router.use('/notifications', notificationRoutes);

export default router;