import mongoose, { Schema, Document } from 'mongoose';
import { PhaseKey, ReasonCode, WorkType } from '../data/roadmapPolicy';
import { GapStatus } from '../data/roleReadinessPolicy';

/**
 * A student's committed 90-day plan.
 *
 * WHY THIS IS STORED, WHEN MODULE 8 IS NOT.
 * Readiness is a statement about now, so deriving it on every request is right — there is
 * nothing to go stale. A roadmap is a statement about what somebody agreed to do, and it
 * has to survive the evidence it was built from changing. If it were derived, finishing an
 * assessment on Tuesday would silently rewrite what Monday had asked of the student, and
 * neither they nor an admin could ever say what the plan had been. A plan you cannot look
 * back at is not a plan.
 *
 * WHY THIS IS NOT THE EXISTING ROADMAP.
 * passportRoadmapService builds the 90-day mission journey from PassportAttempt's six
 * assessment categories, and stores nothing. That system and this one share no data: no
 * skillKey appears anywhere in the mission path, and no category appears anywhere in
 * Modules 3–8. This is not a second copy of that journey — it is the layer above it,
 * answering "what should I achieve" in canonical skills, while missions keep answering
 * "what should I do today". Neither model is touched by the other.
 *
 * WHY OBJECTIVES ARE EMBEDDED.
 * A plan is read whole and written once. Its objectives are meaningless apart from the plan
 * that produced them, they are bounded by the policy's own caps, and a separate collection
 * would buy a join for nothing.
 *
 * WHAT IS NOT STORED HERE.
 * No answers, no evidence rows, no assessment content. The input snapshot keeps only what is
 * needed to explain the plan (§58) — the numbers a student or an admin would ask about, not
 * the material behind them.
 */

/**
 * Two persisted states, and only two.
 *
 *   ACTIVE      the plan in force. At most one per student, enforced by the index below.
 *   SUPERSEDED  replaced by an explicit replan. Kept — this is the history.
 *
 * `completed` and `outdated` are deliberately NOT stored. Both are functions of things that
 * change on their own — the date passing, a role being changed, a blueprint being
 * republished — and a stored copy would be wrong until something happened to notice. They
 * are derived on read, which also means nothing rewrites a student's plan in the background.
 */
export type RoadmapStatus = 'ACTIVE' | 'SUPERSEDED';
export const ROADMAP_STATUSES: RoadmapStatus[] = ['ACTIVE', 'SUPERSEDED'];

/** Why this plan was made. Kept so "why did my roadmap change?" has an answer. */
export type GenerationReason =
  | 'FIRST_PLAN'
  | 'REPLAN_REQUESTED'
  | 'REPLAN_ROLE_CHANGED'
  | 'REPLAN_COMMITMENT_CHANGED'
  | 'REPLAN_BLUEPRINT_CHANGED';

export interface IRoadmapObjective {
  skillKey: string;
  skillName: string;
  workType: WorkType;
  plannedMinutes: number;
  phase: PhaseKey;
  week: number;
  sequence: number;
  reasonCode: ReasonCode;
  sourceGapStatus: GapStatus;
  targetLevel: string;
  targetScore: number;
  studentScore?: number | null;
  prerequisiteFor?: string;
  explanation: string;
  /**
   * Generated by the planner, or put there by a person.
   *
   * Worth one field: an admin who edits a plan should not have their change presented as
   * something the engine decided, and a replan should be able to tell the difference.
   */
  origin: 'GENERATED' | 'MANUAL';
}

export interface ICareerRoadmap extends Document {
  tenantId: string;
  studentId: mongoose.Types.ObjectId;

  roleKey: string;
  roleName: string;

  status: RoadmapStatus;
  policyVersion: string;
  /** 1 for a student's first plan, incrementing on each replan. Not a version history. */
  roadmapVersion: number;

  startDate: Date;
  endDate: Date;
  roadmapDays: number;
  weekCount: number;

  generatedAt: Date;
  generatedBy: 'STUDENT' | 'ADMIN';
  generationReason: GenerationReason;
  supersededAt?: Date;
  supersededBy?: mongoose.Types.ObjectId;

  /** Enough provenance to explain the plan, and no more. */
  input: {
    careerStage?: string | null;
    minutesPerDay: number;
    daysPerWeek: number;
    readiness?: number | null;
    coverage: number;
    roleConfidence: string;
    blueprintVersion: number;
    blueprintUpdatedAt?: Date;
    requiredSkills: number;
    assessedSkills: number;
    /** True when the window was cut short by the membership expiring, not by policy. */
    entitlementLimited: boolean;
  };

  capacity: {
    weeklyCapacityMinutes: number;
    weeklyPlannableMinutes: number;
    theoreticalMinutes: number;
    plannableMinutes: number;
    plannedMinutes: number;
  };

  planningConfidence: 'LOW' | 'MEDIUM' | 'HIGH';

  phases: {
    key: PhaseKey; title: string; blurb: string;
    fromWeek: number; toWeek: number; fromDay: number; toDay: number;
    plannedMinutes: number;
  }[];

  objectives: IRoadmapObjective[];

  /** Not ignored — what the next plan should pick up first. */
  deferred: { skillKey: string; skillName: string; reasonCode: ReasonCode; reason: string }[];

  report: Record<string, number>;

  createdAt: Date;
  updatedAt: Date;
}

const ObjectiveSchema = new Schema<IRoadmapObjective>({
  skillKey:       { type: String, required: true, uppercase: true, trim: true },
  skillName:      { type: String, required: true },
  workType:       { type: String, required: true },
  plannedMinutes: { type: Number, required: true, min: 0 },
  phase:          { type: String, required: true },
  week:           { type: Number, required: true, min: 1 },
  sequence:       { type: Number, required: true },
  reasonCode:     { type: String, required: true },
  sourceGapStatus:{ type: String, required: true },
  targetLevel:    { type: String, required: true },
  targetScore:    { type: Number, required: true },
  studentScore:   { type: Number, default: null },
  prerequisiteFor:{ type: String },
  explanation:    { type: String, default: '' },
  origin:         { type: String, enum: ['GENERATED', 'MANUAL'], default: 'GENERATED' },
}, { _id: false });

const CareerRoadmapSchema = new Schema<ICareerRoadmap>(
  {
    tenantId:  { type: String, required: true, index: true },
    studentId: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true },

    roleKey:  { type: String, required: true, uppercase: true, trim: true },
    roleName: { type: String, required: true },

    status:         { type: String, enum: ROADMAP_STATUSES, default: 'ACTIVE' },
    policyVersion:  { type: String, required: true },
    roadmapVersion: { type: Number, default: 1 },

    startDate:   { type: Date, required: true },
    endDate:     { type: Date, required: true },
    roadmapDays: { type: Number, required: true },
    weekCount:   { type: Number, required: true },

    generatedAt:      { type: Date, default: Date.now },
    generatedBy:      { type: String, enum: ['STUDENT', 'ADMIN'], default: 'STUDENT' },
    generationReason: { type: String, default: 'FIRST_PLAN' },
    supersededAt:     { type: Date },
    supersededBy:     { type: Schema.Types.ObjectId, ref: 'CareerRoadmap' },

    input: {
      careerStage:         { type: String, default: null },
      minutesPerDay:       { type: Number, required: true },
      daysPerWeek:         { type: Number, required: true },
      readiness:           { type: Number, default: null },
      coverage:            { type: Number, default: 0 },
      roleConfidence:      { type: String, default: 'LOW' },
      blueprintVersion:    { type: Number, default: 1 },
      blueprintUpdatedAt:  { type: Date },
      requiredSkills:      { type: Number, default: 0 },
      assessedSkills:      { type: Number, default: 0 },
      entitlementLimited:  { type: Boolean, default: false },
    },

    capacity: {
      weeklyCapacityMinutes:  { type: Number, default: 0 },
      weeklyPlannableMinutes: { type: Number, default: 0 },
      theoreticalMinutes:     { type: Number, default: 0 },
      plannableMinutes:       { type: Number, default: 0 },
      plannedMinutes:         { type: Number, default: 0 },
    },

    planningConfidence: { type: String, enum: ['LOW', 'MEDIUM', 'HIGH'], default: 'LOW' },

    phases: [{
      key: String, title: String, blurb: String,
      fromWeek: Number, toWeek: Number, fromDay: Number, toDay: Number,
      plannedMinutes: Number,
      _id: false,
    }],

    objectives: { type: [ObjectiveSchema], default: [] },

    deferred: [{
      skillKey: String, skillName: String, reasonCode: String, reason: String,
      _id: false,
    }],

    report: { type: Schema.Types.Mixed, default: {} },
  },
  { timestamps: true },
);

/**
 * ONE ACTIVE PLAN PER STUDENT, guaranteed by the database rather than by remembering to
 * check. Two tabs, a double-click or a retried request would otherwise leave a student with
 * two plans, both claiming to be current, and no way to say which one their week came from.
 * Partial, so superseded history is unlimited (§67).
 */
CareerRoadmapSchema.index(
  { tenantId: 1, studentId: 1 },
  { unique: true, partialFilterExpression: { status: 'ACTIVE' } },
);

/** History for one student, newest first. */
CareerRoadmapSchema.index({ tenantId: 1, studentId: 1, generatedAt: -1 });
/** The admin board: who has a plan for which role. */
CareerRoadmapSchema.index({ tenantId: 1, roleKey: 1, status: 1 });

export default mongoose.model<ICareerRoadmap>('CareerRoadmap', CareerRoadmapSchema);
