import mongoose, { Schema, Document } from 'mongoose';
import { IMemberAudience, MemberAudienceSchema } from './memberAudience';

/**
 * The two products this bank serves. Named rather than boolean flags so a third surface
 * costs one entry here instead of a schema change everywhere that reads it.
 */
export const PROBLEM_AUDIENCES = ['lms', 'careerpilot'] as const;
export type ProblemAudience = typeof PROBLEM_AUDIENCES[number];

/**
 * "Problems this audience may see."
 *
 * Written as a Mongo condition so a bank of thousands is filtered by the database rather
 * than fetched and discarded. Rows written before `audiences` existed have no field at all,
 * and are read as LMS-only — the same rule the schema default encodes, applied to documents
 * the default never touched.
 */
export const audienceFilter = (audience: ProblemAudience) => (
  audience === 'lms'
    ? { $or: [{ audiences: 'lms' }, { audiences: { $exists: false } }, { audiences: { $size: 0 } }] }
    : { audiences: audience }
);

// A problem in the Logical Thinking Lab question bank. Generated by AI (admin-triggered)
// or authored manually, then served to students by the daily-challenge engine. Test
// cases / reference solution / hints are NEVER sent to students unrevealed.
export interface IThinkingProblem extends Document {
  tenantId: string;
  title: string;
  category: string;            // Arithmetic, Patterns, Arrays, Recursion, Brain Teasers, Interview…
  difficulty: 'easy' | 'medium' | 'hard' | 'expert' | 'interview';
  language: string;            // default language for starter code
  statement: string;          // the problem text
  examples: { input: string; expectedOutput: string; explanation?: string }[];
  constraints?: string;
  notes?: string;
  starterCode?: string;
  testCases: { input: string; expectedOutput: string; hidden: boolean }[];
  hints: string[];             // up to 3, revealed one at a time
  referenceSolution?: string;  // locked until submission
  expectedTimeComplexity?: string;
  expectedSpaceComplexity?: string;
  imageUrl?: string;
  videoUrl?: string;
  referenceVideo?: string;     // shown after solving
  xp: number;
  estimatedMinutes?: number;
  tags?: string[];
  /**
   * WHO this problem is for. One bank, two products.
   *
   * Defaults to ['lms'] rather than both, and that is deliberate: every problem written
   * before this field existed was authored for the Thinking Lab and has only ever been
   * served to LMS students. Defaulting to both would silently publish the entire LMS bank
   * to CareerPilot members the moment their list starts reading it — an audience those
   * problems were never reviewed for. Opting a problem in is one tick; un-publishing a
   * hundred after the fact is not.
   */
  audiences: ProblemAudience[];
  /**
   * Which members this is for, beyond the product tag above.
   *
   * Empty on every axis means everyone, so nothing already written changes. Narrowing is
   * how a second-year CSE student and a final-year ECE student stop being handed the same
   * problem on the same day.
   */
  audience: IMemberAudience;
  /**
   * Failed attempts after which the solution video and reference solution unlock.
   *
   * A stuck student is the case this exists for. The gate is enforced where the payload is
   * built, never in the UI — a URL withheld only by a client is a URL anyone can read out
   * of the network tab.
   */
  solutionUnlockAfterAttempts: number;
  /**
   * Uploaded video, as a storage key rather than a URL. Sits alongside videoUrl and
   * referenceVideo (which stay for externally hosted links): admins asked for both, and a
   * key is streamed through a gated endpoint while a link is simply followed.
   */
  videoKey?: string;
  solutionVideoKey?: string;
  /** Distinct members who have attempted this. Counted, not aggregated on read. */
  attemptCount: number;
  source: 'ai' | 'manual';
  active: boolean;
  timesAssigned: number;
  timesSolved: number;
  createdBy?: mongoose.Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

const ThinkingProblemSchema = new Schema<IThinkingProblem>(
  {
    tenantId:   { type: String, required: true, index: true },
    title:      { type: String, required: true },
    category:   { type: String, required: true, index: true },
    difficulty: { type: String, enum: ['easy', 'medium', 'hard', 'expert', 'interview'], default: 'easy', index: true },
    language:   { type: String, default: 'javascript' },
    statement:  { type: String, required: true },
    examples:   { type: [{ input: String, expectedOutput: String, explanation: String, _id: false }], default: [] },
    constraints:{ type: String },
    notes:      { type: String },
    starterCode:{ type: String, default: '' },
    testCases:  { type: [{ input: String, expectedOutput: String, hidden: Boolean, _id: false }], default: [] },
    hints:      { type: [String], default: [] },
    referenceSolution: { type: String },
    expectedTimeComplexity:  { type: String },
    expectedSpaceComplexity: { type: String },
    imageUrl:   { type: String },
    videoUrl:   { type: String },
    referenceVideo: { type: String },
    xp:         { type: Number, default: 50 },
    estimatedMinutes: { type: Number, default: 15 },
    tags:       { type: [String], default: [] },
    audiences:  { type: [String], enum: PROBLEM_AUDIENCES, default: ['lms'] },
    audience:   MemberAudienceSchema,
    solutionUnlockAfterAttempts: { type: Number, default: 3 },
    videoKey:          { type: String, default: '' },
    solutionVideoKey:  { type: String, default: '' },
    attemptCount:      { type: Number, default: 0 },
    source:     { type: String, enum: ['ai', 'manual'], default: 'ai' },
    active:     { type: Boolean, default: true },
    timesAssigned: { type: Number, default: 0 },
    timesSolved:   { type: Number, default: 0 },
    createdBy:  { type: Schema.Types.ObjectId, ref: 'User' },
  },
  { timestamps: true }
);
ThinkingProblemSchema.index({ tenantId: 1, active: 1, difficulty: 1, category: 1 });

export default mongoose.model<IThinkingProblem>('ThinkingProblem', ThinkingProblemSchema);
