import mongoose, { Schema, Document } from 'mongoose';

// A problem in the Logical Thinking Lab question bank. Generated by AI (admin-triggered)
// or authored manually, then served to students by the daily-challenge engine. Test
// cases / reference solution / hints are NEVER sent to students unrevealed.
export interface IThinkingProblem extends Document {
  tenantId: string;
  title: string;
  category: string;            // Arithmetic, Patterns, Arrays, Recursion, Brain Teasers, Interview…
  difficulty: 'easy' | 'medium' | 'hard' | 'expert' | 'interview';
  language: string;            // default language for starter code
  statement: string;          // the problem text
  examples: { input: string; expectedOutput: string; explanation?: string }[];
  constraints?: string;
  notes?: string;
  starterCode?: string;
  testCases: { input: string; expectedOutput: string; hidden: boolean }[];
  hints: string[];             // up to 3, revealed one at a time
  referenceSolution?: string;  // locked until submission
  expectedTimeComplexity?: string;
  expectedSpaceComplexity?: string;
  xp: number;
  estimatedMinutes?: number;
  tags?: string[];
  source: 'ai' | 'manual';
  active: boolean;
  timesAssigned: number;
  timesSolved: number;
  createdBy?: mongoose.Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

const ThinkingProblemSchema = new Schema<IThinkingProblem>(
  {
    tenantId:   { type: String, required: true, index: true },
    title:      { type: String, required: true },
    category:   { type: String, required: true, index: true },
    difficulty: { type: String, enum: ['easy', 'medium', 'hard', 'expert', 'interview'], default: 'easy', index: true },
    language:   { type: String, default: 'javascript' },
    statement:  { type: String, required: true },
    examples:   { type: [{ input: String, expectedOutput: String, explanation: String, _id: false }], default: [] },
    constraints:{ type: String },
    notes:      { type: String },
    starterCode:{ type: String, default: '' },
    testCases:  { type: [{ input: String, expectedOutput: String, hidden: Boolean, _id: false }], default: [] },
    hints:      { type: [String], default: [] },
    referenceSolution: { type: String },
    expectedTimeComplexity:  { type: String },
    expectedSpaceComplexity: { type: String },
    xp:         { type: Number, default: 50 },
    estimatedMinutes: { type: Number, default: 15 },
    tags:       { type: [String], default: [] },
    source:     { type: String, enum: ['ai', 'manual'], default: 'ai' },
    active:     { type: Boolean, default: true },
    timesAssigned: { type: Number, default: 0 },
    timesSolved:   { type: Number, default: 0 },
    createdBy:  { type: Schema.Types.ObjectId, ref: 'User' },
  },
  { timestamps: true }
);
ThinkingProblemSchema.index({ tenantId: 1, active: 1, difficulty: 1, category: 1 });

export default mongoose.model<IThinkingProblem>('ThinkingProblem', ThinkingProblemSchema);
