import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import passportApi, { CompanyRow, TaxItem, CompanyDetail } from '../../api/passportApi';
import PassportShell, { LockedPanel } from './PassportShell';

/**
 * Company Questions — what companies actually asked, by round.
 *
 * One component covers both screens: the grid at /careerpilot/companies and a single
 * company at /careerpilot/companies/:slug. They share the entitlement check and the empty
 * states, and splitting them would duplicate both.
 */

const DIFF_COLOR: Record<string, string> = { easy: '#16a34a', medium: '#b45309', hard: '#b91c1c' };

// ─── One company ─────────────────────────────────────────────────────────────

const CompanyView: React.FC<{ slug: string }> = ({ slug }) => {
  const nav = useNavigate();
  const [d, setD] = useState<CompanyDetail | null>(null);
  const [round, setRound] = useState('');
  const [open, setOpen] = useState<string | null>(null);
  const [err, setErr] = useState('');
  const [contribute, setContribute] = useState(false);
  const [form, setForm] = useState({ questionText: '', round: '', category: '', difficulty: 'medium', role: '', year: '', answer: '' });
  const [sent, setSent] = useState('');

  const load = (r: string) => {
    passportApi.companyDetail(slug, r ? { round: r } : {})
      .then(setD)
      .catch(e => setErr(e?.response?.data?.message || 'Could not load that company'));
  };
  useEffect(() => { load(round); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [slug, round]);

  const submit = async () => {
    try {
      const r = await passportApi.contributeQuestion(slug, { ...form, year: Number(form.year) || undefined });
      setSent(r.message);
      setContribute(false);
      setForm({ questionText: '', round: '', category: '', difficulty: 'medium', role: '', year: '', answer: '' });
    } catch (e: any) { setErr(e?.response?.data?.message || 'Could not submit'); }
  };

  if (err) return <PassportShell><div className="pm-msg err">{err}</div></PassportShell>;
  if (!d) return <PassportShell><div className="pm-card">Loading…</div></PassportShell>;

  const label = (list: TaxItem[], key: string) => list.find(x => x.key === key)?.label || key;

  return (
    <PassportShell>
      <button className="pm-btn ghost" onClick={() => nav('/careerpilot/companies')} style={{ marginBottom: 10 }}>← All companies</button>

      <div className="pm-head">
        <h1>{d.company.name}</h1>
        <p>{d.company.about || 'Questions asked in past interviews, grouped by round.'}</p>
      </div>

      {sent && <div className="pm-msg ok">{sent}</div>}

      <div className="cq-rounds">
        <button className={`cq-round${round === '' ? ' on' : ''}`} onClick={() => setRound('')}>
          All <em>{d.rounds.reduce((s, r) => s + (r.count || 0), 0)}</em>
        </button>
        {d.rounds.filter(r => (r.count || 0) > 0).map(r => (
          <button key={r.key} className={`cq-round${round === r.key ? ' on' : ''}`} onClick={() => setRound(r.key)}>
            {r.label} <em>{r.count}</em>
          </button>
        ))}
      </div>

      {!d.questions.length ? (
        <div className="pm-card">
          Nothing here yet for this round. If you've interviewed here, you can add what you were asked.
        </div>
      ) : d.questions.map(q => (
        <div className="cq-q" key={q.id}>
          <button className="cq-q-head" onClick={() => setOpen(open === q.id ? null : q.id)}>
            <span className="tx">{q.questionText}</span>
            <span className="chev">{open === q.id ? '▲' : '▼'}</span>
          </button>
          <div className="cq-q-meta">
            <span className="rd">{label(d.rounds, q.round)}</span>
            {q.category && <span className="cat">{label(d.categories, q.category)}</span>}
            <span className="diff" style={{ color: DIFF_COLOR[q.difficulty] || '#64748b' }}>{q.difficulty}</span>
            {q.year && <span className="yr">{q.year}</span>}
            {/* A prediction is never allowed to look like a recollection. */}
            {q.aiPredicted && <span className="pred" title="Generated by AI to help you prepare — not a question we have a record of being asked">AI-predicted</span>}
            {q.practiceProblemId && (
              <button className="solve" onClick={() => nav(`/careerpilot/practice/${q.practiceProblemId}`)}>▶ Solve it</button>
            )}
          </div>
          {open === q.id && (
            <div className="cq-q-body">
              {q.answer
                ? <p>{q.answer}</p>
                : <p className="muted">No model answer recorded for this one yet — try it in a mock interview.</p>}
            </div>
          )}
        </div>
      ))}

      <div className="pm-card" style={{ marginTop: 16 }}>
        {!contribute ? (
          <>
            <h3 style={{ fontSize: 15, fontWeight: 900, color: '#0f172a', margin: '0 0 6px' }}>Interviewed here?</h3>
            <p style={{ fontSize: 13, color: '#64748b', margin: '0 0 12px', lineHeight: 1.6 }}>
              Add what you were asked. We review it before it goes live, and you earn coins once it's approved.
            </p>
            <button className="pm-btn primary" onClick={() => setContribute(true)}>Add a question</button>
          </>
        ) : (
          <>
            <h3 style={{ fontSize: 15, fontWeight: 900, color: '#0f172a', margin: '0 0 10px' }}>What were you asked?</h3>
            <textarea className="cq-input" style={{ minHeight: 80 }} placeholder="Write the question as closely as you remember it…"
              value={form.questionText} onChange={e => setForm(f => ({ ...f, questionText: e.target.value }))} />
            <div className="cq-form-row">
              <select className="cq-input" value={form.round} onChange={e => setForm(f => ({ ...f, round: e.target.value }))}>
                <option value="">Which round?</option>
                {d.rounds.map(r => <option key={r.key} value={r.key}>{r.label}</option>)}
              </select>
              <select className="cq-input" value={form.category} onChange={e => setForm(f => ({ ...f, category: e.target.value }))}>
                <option value="">Topic</option>
                {d.categories.map(c => <option key={c.key} value={c.key}>{c.label}</option>)}
              </select>
            </div>
            <div className="cq-form-row">
              <input className="cq-input" placeholder="Role (e.g. SDE-1)" value={form.role} onChange={e => setForm(f => ({ ...f, role: e.target.value }))} />
              <input className="cq-input" placeholder="Year" inputMode="numeric" value={form.year} onChange={e => setForm(f => ({ ...f, year: e.target.value }))} />
            </div>
            <div style={{ display: 'flex', gap: 8, marginTop: 12 }}>
              <button className="pm-btn primary" disabled={form.questionText.trim().length < 12} onClick={submit}>Submit</button>
              <button className="pm-btn ghost" onClick={() => setContribute(false)}>Cancel</button>
            </div>
          </>
        )}
      </div>
    </PassportShell>
  );
};

// ─── The grid ────────────────────────────────────────────────────────────────

const Companies: React.FC = () => {
  const { slug } = useParams();
  const nav = useNavigate();
  const [companies, setCompanies] = useState<CompanyRow[] | null>(null);
  const [types, setTypes] = useState<TaxItem[]>([]);
  const [type, setType] = useState('');
  const [q, setQ] = useState('');
  const [locked, setLocked] = useState<{ priceInr?: number } | null>(null);
  const [err, setErr] = useState('');

  useEffect(() => {
    if (slug) return;
    passportApi.listCompanies()
      .then(r => {
        if (r.locked) setLocked({ priceInr: r.priceInr });
        else { setCompanies(r.companies || []); setTypes(r.companyTypes || []); }
      })
      .catch(e => setErr(e?.response?.data?.message || 'Could not load companies'));
  }, [slug]);

  if (slug) return <CompanyView slug={slug} />;

  if (locked) {
    return (
      <PassportShell>
        <LockedPanel
          title="Company Questions are part of your membership"
          blurb="What real companies asked, round by round — coding, aptitude, technical, GD and HR — so you walk in knowing the shape of the interview."
          priceInr={locked.priceInr}
        />
      </PassportShell>
    );
  }
  if (err) return <PassportShell><div className="pm-msg err">{err}</div></PassportShell>;
  if (!companies) return <PassportShell><div className="pm-card">Loading…</div></PassportShell>;

  const shown = companies.filter(c =>
    (!type || c.type === type) && (!q || c.name.toLowerCase().includes(q.toLowerCase())));

  return (
    <PassportShell>
      <div className="pm-head">
        <h1>Company Questions</h1>
        <p>What these companies actually asked, grouped by round.</p>
      </div>

      <div className="cq-filters">
        <input className="cq-input" placeholder="Search a company…" value={q} onChange={e => setQ(e.target.value)} />
        <div className="cq-types">
          <button className={`cq-type${type === '' ? ' on' : ''}`} onClick={() => setType('')}>All</button>
          {types.map(t => (
            <button key={t.key} className={`cq-type${type === t.key ? ' on' : ''}`} onClick={() => setType(t.key)}>{t.label}</button>
          ))}
        </div>
      </div>

      {!companies.length && <div className="pm-card">No companies yet — check back soon.</div>}
      {!!companies.length && !shown.length && <div className="pm-card">No company matches that.</div>}

      <div className="cq-grid">
        {shown.map(c => (
          <button className="cq-card" key={c.id} onClick={() => nav(`/careerpilot/companies/${c.slug}`)}>
            {c.logoUrl
              ? <img src={c.logoUrl} alt="" onError={e => { (e.currentTarget as HTMLImageElement).style.display = 'none'; }} />
              : <span className="mk">{c.name.slice(0, 2).toUpperCase()}</span>}
            <b>{c.name}</b>
            <span className="ty">{types.find(t => t.key === c.type)?.label || c.type}</span>
            <span className="ct">{c.questionCount} question{c.questionCount === 1 ? '' : 's'}</span>
          </button>
        ))}
      </div>
    </PassportShell>
  );
};

export default Companies;
