import User from '../models/User';
import CareerSkill from '../models/CareerSkill';
import StudentSkillProfile from '../models/StudentSkillProfile';
import CareerRoadmap, { ICareerRoadmap, GenerationReason } from '../models/CareerRoadmap';
import { getCareerContext, StudentCareerContext } from './careerContextService';
import { calculateStudentRoleReadiness, RoleReadinessResult } from './roleReadinessService';
import PassportConfig from '../models/PassportConfig';
import { isEntitled } from './passportEntitlementService';
import { buildRoadmapPlan, PlannerGraphNode, PlannerProfile } from './roadmapPlannerService';
import {
  MAX_ROADMAP_DAYS, PREREQUISITE_DEPTH, ROADMAP_VERSION, RoadmapUnavailable,
} from '../data/roadmapPolicy';

/**
 * Making, storing and reading a student's 90-day plan.
 *
 * The division of labour matters here. roadmapPlannerService decides the plan and touches
 * nothing; this service gathers what it needs, writes the result down, and answers questions
 * about the plan that is already in force. Keeping the decision pure is what makes it
 * testable; keeping the writes here is what makes them auditable.
 *
 * A ROADMAP IS NEVER REGENERATED BY ACCIDENT. Nothing in this file rewrites a plan because
 * an input changed. A student who improves a score, an admin who republishes a blueprint and
 * a clock that ticks past midnight all leave the stored plan exactly as it was; the only
 * things that create a plan are an explicit generate and an explicit replan. Whether a plan
 * has fallen out of date is reported, never acted upon — that decision belongs to the person
 * whose plan it is.
 *
 * NOTHING HERE TOUCHES SKILL DNA. Completing a roadmap item is not evidence of anything;
 * marking "Learn OOP" done must never move an OOP score, or the measurement becomes a
 * self-assessment and every downstream number becomes worthless.
 */

export interface RoadmapUnavailableResult {
  available: false;
  reason: RoadmapUnavailable;
  message: string;
  /** For CAREER_CONTEXT_INCOMPLETE — exactly which answers are still needed. */
  missing?: string[];
  role?: { key: string; name?: string };
}

export interface RoadmapView {
  available: true;
  roadmap: ICareerRoadmap;
  /** 1-based, clamped to the window. Past the end it stays at the last day. */
  currentDay: number;
  currentWeek: number;
  completed: boolean;
  outdated: boolean;
  outdatedReasons: OutdatedReason[];
}

export type OutdatedReason = 'ROLE_CHANGED' | 'COMMITMENT_CHANGED' | 'BLUEPRINT_CHANGED';

export type RoadmapOutcome = RoadmapView | RoadmapUnavailableResult;

/** Everything the planner needs, gathered in batched queries rather than per skill. */
interface PlanningInputs {
  context: StudentCareerContext;
  readiness: RoleReadinessResult;
  graph: Map<string, PlannerGraphNode>;
  profiles: Map<string, PlannerProfile>;
  roadmapDays: number;
  entitlementLimited: boolean;
}

const startOfUtcDay = (d: Date): Date => {
  const x = new Date(d);
  x.setUTCHours(0, 0, 0, 0);
  return x;
};

/** Whole days from `from` to `to`, matching how the existing journey counts them. */
const daysBetween = (from: Date, to: Date): number =>
  Math.floor((startOfUtcDay(to).getTime() - startOfUtcDay(from).getTime()) / 86400000);

/**
 * The canonical subgraph around a set of skills, to the depth the planner can walk.
 *
 * One query per level — four at the very most, whatever the size of the blueprint. Resolving
 * a prerequisite chain with a lookup per skill would be thirty round trips to plan one
 * student, and the whole point of the shared graph is that it is loaded once.
 */
async function loadGraph(keys: string[]): Promise<Map<string, PlannerGraphNode>> {
  const graph = new Map<string, PlannerGraphNode>();
  let frontier = [...new Set(keys)];

  // One extra round beyond the planner's depth, because a GROUP standing between two skills
  // is traversed without counting as a level.
  for (let round = 0; round <= PREREQUISITE_DEPTH + 1 && frontier.length; round++) {
    const docs = await CareerSkill.find({ key: { $in: frontier } })
      .select('key name nodeType prerequisiteKeys active').lean() as any[];

    const next: string[] = [];
    for (const d of docs) {
      if (graph.has(d.key)) continue;
      graph.set(d.key, {
        key: d.key,
        name: d.name,
        nodeType: d.nodeType === 'GROUP' ? 'GROUP' : 'SKILL',
        prerequisiteKeys: Array.isArray(d.prerequisiteKeys) ? d.prerequisiteKeys : [],
        active: d.active !== false,
      });
      for (const p of d.prerequisiteKeys || []) if (!graph.has(p)) next.push(p);
    }
    frontier = [...new Set(next)];
  }

  return graph;
}

/**
 * How long this plan may run, from the membership's end date alone.
 *
 * PURELY A QUESTION ABOUT THE DATE. Whether somebody is allowed a plan at all is a separate
 * question, answered by the entitlement check in gatherInputs — mixing the two is what
 * produced the bug this replaces. The old version bailed out to the full ninety days
 * whenever `membershipActive()` was false, so the two states it could not tell apart —
 * "no expiry has ever been set" and "the membership ran out in March" — were handed the
 * same answer, and the expired member got a fresh 90-day roadmap for free.
 *
 * The three cases are now distinct:
 *
 *   no expiry date      perpetual under existing semantics; the full window
 *   expiry ahead of us  min(90, days remaining) — never plan work into weeks they cannot reach
 *   expiry behind us    EXPIRED. No window at all, and the caller must refuse.
 */
function windowFor(passport: any, now: Date): {
  roadmapDays: number;
  entitlementLimited: boolean;
  expired: boolean;
} {
  const raw = passport?.expiresAt ? new Date(passport.expiresAt) : null;

  // No authoritative end date. §7 is explicit that one has to already exist for us to clamp
  // to it, and inventing one here would be inventing a subscription model.
  if (!raw || Number.isNaN(raw.getTime())) {
    return { roadmapDays: MAX_ROADMAP_DAYS, entitlementLimited: false, expired: false };
  }

  const left = daysBetween(now, raw) + 1;
  if (left <= 0) return { roadmapDays: 0, entitlementLimited: true, expired: true };
  if (left >= MAX_ROADMAP_DAYS) return { roadmapDays: MAX_ROADMAP_DAYS, entitlementLimited: false, expired: false };
  return { roadmapDays: left, entitlementLimited: true, expired: false };
}

/**
 * Gather the planning inputs, or say precisely why we cannot.
 *
 * The order of the checks is the order a student would fix them: a role first, because
 * without one nothing else has a target; then whether that role has been configured; then
 * whether we know how much time they have. Each failure names one next action rather than a
 * generic "not ready", because "not ready" is where students give up.
 */
async function gatherInputs(
  tenantId: string,
  studentId: string,
  now: Date,
): Promise<PlanningInputs | RoadmapUnavailableResult> {
  const context = await getCareerContext(tenantId, studentId, now);
  if (!context) {
    return { available: false, reason: 'CAREER_CONTEXT_INCOMPLETE', message: 'Account not found.' };
  }

  // Module 8 owns role resolution, blueprint readiness and every gap verdict. Re-deriving
  // any of it here is how two screens end up disagreeing about the same student.
  const readiness = await calculateStudentRoleReadiness(tenantId, studentId);
  if (!readiness.available) {
    const un = readiness as { reason: string; message: string; role?: { key: string; name?: string } };
    return {
      available: false,
      reason: un.reason === 'ROLE_NOT_SELECTED' ? 'ROLE_NOT_SELECTED' : 'ROLE_BLUEPRINT_NOT_READY',
      message: un.reason === 'ROLE_NOT_SELECTED'
        ? 'Choose a target role before we build your plan — a roadmap without one would be a guess.'
        : 'This role is not configured yet, so we cannot plan against it.',
      role: un.role,
    };
  }

  // Capacity is the one input with no safe default. Inventing "two hours a day" would build
  // a plan around time the student never said they had, and they would fall behind in week
  // one through no fault of their own.
  const minutesPerDay = context.availability.minutesPerDay;
  const daysPerWeek = context.availability.daysPerWeek;
  if (!minutesPerDay || !daysPerWeek) {
    const missing: string[] = [];
    if (!minutesPerDay) missing.push('availability.minutesPerDay');
    if (!daysPerWeek) missing.push('availability.daysPerWeek');
    return {
      available: false,
      reason: 'CAREER_CONTEXT_INCOMPLETE',
      message: 'Tell us how much time you can give this, and we will build a plan that fits it.',
      missing,
      role: { key: readiness.role.key, name: readiness.role.name },
    };
  }

  const ready = readiness as RoleReadinessResult;
  const graph = await loadGraph(ready.skills.map(s => s.skillKey));

  // Skill DNA for the whole subgraph, not just the blueprint: a prerequisite the role never
  // listed still has to be checked before we decide to teach it.
  const rows = await StudentSkillProfile
    .find({ tenantId, studentId, skillKey: { $in: [...graph.keys()] } })
    .select('skillKey score confidence').lean() as any[];

  const profiles = new Map<string, PlannerProfile>(
    rows.map(r => [r.skillKey, { score: r.score, confidence: r.confidence }]),
  );

  const [user, cfg] = await Promise.all([
    User.findOne({ _id: studentId, tenantId }).select('passport').lean() as any,
    PassportConfig.findOne({ tenantId }).lean() as any,
  ]);

  const { roadmapDays, entitlementLimited, expired } = windowFor(user?.passport, now);

  /**
   * May this member have a plan at all?
   *
   * Gated on `roadmap_full` — the feature key this product already uses for "Full 90-day
   * Roadmap", so a tenant that has re-tiered it in Platform Settings re-tiers this too, and
   * nothing new has to be configured. isEntitled fails closed on an unknown key.
   *
   * The expiry check is deliberately SEPARATE and not an else-branch. A tenant may set
   * roadmap_full to `free`, which is their decision and lets a free member plan — but an
   * authoritative end date that has already passed still cannot buy a fresh ninety days,
   * because those days do not exist. Either condition refuses on its own.
   */
  if (!isEntitled(cfg?.entitlements, user?.passport, 'roadmap_full', now) || expired) {
    return {
      available: false,
      reason: 'MEMBERSHIP_REQUIRED',
      message: expired
        ? 'Your CareerPilot membership has ended, so we cannot plan the next 90 days yet. Renewing brings your plan back.'
        : 'A CareerPilot membership is needed to build your 90-day plan.',
      role: { key: ready.role.key, name: ready.role.name },
    };
  }

  return { context, readiness: ready, graph, profiles, roadmapDays, entitlementLimited };
}

/** Build the plan document body from gathered inputs. Pure apart from the planner call. */
function planFrom(inputs: PlanningInputs, now: Date) {
  const { context, readiness } = inputs;

  const plan = buildRoadmapPlan({
    roleKey: readiness.role.key,
    roleName: readiness.role.name,
    stage: context.derived.stage,
    coverage: readiness.coverage,
    roleConfidence: readiness.confidence,
    minutesPerDay: context.availability.minutesPerDay!,
    daysPerWeek: context.availability.daysPerWeek!,
    roadmapDays: inputs.roadmapDays,
    skills: readiness.skills,
    graph: inputs.graph,
    profiles: inputs.profiles,
  });

  const startDate = startOfUtcDay(now);
  const endDate = new Date(startDate.getTime() + (inputs.roadmapDays - 1) * 86400000);

  return {
    plan,
    body: {
      roleKey: readiness.role.key,
      roleName: readiness.role.name,
      policyVersion: plan.policyVersion,
      startDate,
      endDate,
      roadmapDays: plan.roadmapDays,
      weekCount: plan.weekCount,
      generatedAt: now,
      input: {
        careerStage: context.derived.stage,
        minutesPerDay: context.availability.minutesPerDay!,
        daysPerWeek: context.availability.daysPerWeek!,
        readiness: readiness.readiness,
        coverage: readiness.coverage,
        roleConfidence: readiness.confidence,
        blueprintVersion: readiness.blueprintVersion,
        blueprintUpdatedAt: readiness.blueprintUpdatedAt,
        requiredSkills: readiness.summary.requiredSkills,
        assessedSkills: readiness.summary.assessedSkills,
        entitlementLimited: inputs.entitlementLimited,
      },
      capacity: plan.capacity,
      planningConfidence: plan.planningConfidence,
      phases: plan.phases,
      objectives: plan.objectives.map(o => ({ ...o, origin: 'GENERATED' as const })),
      deferred: plan.deferred,
      report: plan.report,
    },
  };
}

/**
 * Has the world moved on since this plan was made?
 *
 * Three things invalidate a plan's premise: a different target, a different amount of time,
 * or a role that now requires different skills. A CHANGED SKILL DNA IS NOT ONE OF THEM — the
 * student improving at what the plan asked them to improve at is the plan working, not the
 * plan expiring, and treating it as staleness would tell somebody to rebuild their roadmap
 * every time they finished an assessment.
 */
export function stalenessOf(
  roadmap: ICareerRoadmap,
  context: StudentCareerContext | null,
  currentBlueprintVersion?: number,
): OutdatedReason[] {
  const reasons: OutdatedReason[] = [];
  if (!context) return reasons;

  if (context.career.primaryRole && context.career.primaryRole !== roadmap.roleKey) {
    reasons.push('ROLE_CHANGED');
  }
  const { minutesPerDay, daysPerWeek } = context.availability;
  if ((minutesPerDay && minutesPerDay !== roadmap.input.minutesPerDay)
    || (daysPerWeek && daysPerWeek !== roadmap.input.daysPerWeek)) {
    reasons.push('COMMITMENT_CHANGED');
  }
  if (currentBlueprintVersion !== undefined && currentBlueprintVersion !== roadmap.input.blueprintVersion) {
    reasons.push('BLUEPRINT_CHANGED');
  }
  return reasons;
}

/** Everything derived from a stored plan and the clock. Nothing here writes. */
function viewOf(roadmap: ICareerRoadmap, outdatedReasons: OutdatedReason[], now: Date): RoadmapView {
  const elapsed = daysBetween(roadmap.startDate, now) + 1;
  return {
    available: true,
    roadmap,
    currentDay: Math.min(roadmap.roadmapDays, Math.max(1, elapsed)),
    currentWeek: Math.min(roadmap.weekCount, Math.max(1, Math.ceil(Math.max(1, elapsed) / 7))),
    completed: elapsed > roadmap.roadmapDays,
    outdated: outdatedReasons.length > 0,
    outdatedReasons,
  };
}

/**
 * The student's current plan, or why there isn't one.
 *
 * Reading never generates. A roadmap is something somebody chose to start, and creating one
 * as a side effect of opening a page would mean the plan's start date was whenever they
 * happened to look.
 */
export async function getActiveRoadmap(
  tenantId: string,
  studentId: string,
  now: Date = new Date(),
): Promise<RoadmapOutcome> {
  const roadmap = await CareerRoadmap.findOne({ tenantId, studentId, status: 'ACTIVE' });

  if (!roadmap) {
    // No plan yet: report what still stands in the way, so the screen can offer the one
    // action that would fix it.
    const inputs = await gatherInputs(tenantId, studentId, now);
    if (!('context' in inputs)) return inputs;
    return {
      available: false,
      reason: 'NO_READINESS_DATA',
      message: 'Your skills and role gaps are ready — generate your 90-day plan whenever you are.',
      role: { key: inputs.readiness.role.key, name: inputs.readiness.role.name },
    };
  }

  const [context, readiness] = await Promise.all([
    getCareerContext(tenantId, studentId, now),
    calculateStudentRoleReadiness(tenantId, studentId).catch(() => null),
  ]);

  const blueprintVersion = readiness && readiness.available
    ? (readiness as RoleReadinessResult).blueprintVersion
    : undefined;

  return viewOf(roadmap, stalenessOf(roadmap, context, blueprintVersion), now);
}

export interface GenerateOptions {
  actor?: 'STUDENT' | 'ADMIN';
  /** Explicitly replace the active plan. Without it, generation returns what already exists. */
  replan?: boolean;
  reason?: GenerationReason;
  now?: Date;
}

export interface GenerateResult {
  outcome: RoadmapOutcome;
  /** False when an existing plan was returned untouched, which is the normal retry case. */
  created: boolean;
  /** Set when generation was refused for a reason that is not a missing input. */
  refused?: 'PROGRAM_WINDOW_COMPLETED';
}

/**
 * Generate, or return the plan that already exists.
 *
 * IDEMPOTENT BY DEFAULT. A double-clicked button, a retried request and a page that loads
 * twice must not leave a student with two plans — so without an explicit replan this returns
 * the active one untouched. The unique partial index is the real guarantee; the check below
 * only saves the work.
 */
export async function generateRoadmap(
  tenantId: string,
  studentId: string,
  opts: GenerateOptions = {},
): Promise<GenerateResult> {
  const now = opts.now || new Date();
  const existing = await CareerRoadmap.findOne({ tenantId, studentId, status: 'ACTIVE' });

  if (existing) {
    const elapsed = daysBetween(existing.startDate, now) + 1;
    const finished = elapsed > existing.roadmapDays;

    // A finished programme stays finished. Rolling straight into another 90 days would be
    // renewal, which is a commercial decision this module does not get to make.
    if (finished) {
      const context = await getCareerContext(tenantId, studentId, now);
      return {
        outcome: viewOf(existing, stalenessOf(existing, context), now),
        created: false,
        refused: 'PROGRAM_WINDOW_COMPLETED',
      };
    }

    if (!opts.replan) {
      const context = await getCareerContext(tenantId, studentId, now);
      return { outcome: viewOf(existing, stalenessOf(existing, context), now), created: false };
    }
  }

  // Everything is read and the plan fully built BEFORE anything is written, so a failure
  // while planning cannot leave a student with their old plan retired and no new one.
  const inputs = await gatherInputs(tenantId, studentId, now);
  if (!('context' in inputs)) return { outcome: inputs, created: false };

  const { body } = planFrom(inputs, now);

  if (existing) {
    existing.status = 'SUPERSEDED';
    existing.supersededAt = now;
    await existing.save();
  }

  try {
    const created = await CareerRoadmap.create({
      ...body,
      tenantId,
      studentId,
      status: 'ACTIVE',
      roadmapVersion: (existing?.roadmapVersion || 0) + 1,
      generatedBy: opts.actor || 'STUDENT',
      generationReason: opts.reason || (existing ? 'REPLAN_REQUESTED' : 'FIRST_PLAN'),
    });

    if (existing) {
      existing.supersededBy = created._id as any;
      await existing.save();
    }

    return {
      outcome: viewOf(created, stalenessOf(created, inputs.context, inputs.readiness.blueprintVersion), now),
      created: true,
    };
  } catch (e: any) {
    // Two requests raced and the index did its job. Whoever lost returns the winner's plan
    // rather than an error — the student asked for a roadmap and there is one.
    if (e?.code === 11000) {
      const winner = await CareerRoadmap.findOne({ tenantId, studentId, status: 'ACTIVE' });
      if (winner) {
        return { outcome: viewOf(winner, stalenessOf(winner, inputs.context), now), created: false };
      }
    }
    // The replacement could not be written, so put the old plan back. Leaving a student with
    // no active plan because a save failed would be the worst outcome of the three.
    if (existing) {
      existing.status = 'ACTIVE';
      existing.supersededAt = undefined;
      await existing.save().catch(() => { /* nothing further to try */ });
    }
    throw e;
  }
}

/**
 * Explain a plan the way an admin would need it explained.
 *
 * The capacity arithmetic and the phase split, written out. "Why did Rahul get four weeks of
 * foundations and Priya one?" deserves the workings, not a restatement of the outcome.
 */
export function explainRoadmap(roadmap: ICareerRoadmap): string[] {
  const c = roadmap.capacity;
  const lines = [
    `policy ${roadmap.policyVersion}  ·  window ${roadmap.roadmapDays} days  ·  ${roadmap.weekCount} weeks`,
    `capacity ${roadmap.input.minutesPerDay}min × ${roadmap.input.daysPerWeek}d = ${c.weeklyCapacityMinutes}/week`
      + `  →  plannable ${c.plannableMinutes}  ·  planned ${c.plannedMinutes}`,
    `readiness ${roadmap.input.readiness ?? 'n/a'}  ·  coverage ${roadmap.input.coverage}`
      + `  ·  role confidence ${roadmap.input.roleConfidence}  ·  planning confidence ${roadmap.planningConfidence}`,
  ];

  for (const p of roadmap.phases) {
    lines.push(`${p.key}  weeks ${p.fromWeek}–${p.toWeek}  (days ${p.fromDay}–${p.toDay})  ${p.plannedMinutes} min`);
  }
  for (const [k, v] of Object.entries(roadmap.report || {})) lines.push(`${k} = ${v}`);
  if (roadmap.deferred?.length) {
    lines.push(`deferred (${roadmap.deferred.length}): ${roadmap.deferred.map(d => d.skillKey).join(', ')}`);
  }
  return lines;
}

export { ROADMAP_VERSION };
