import { IPassportPathway, IPathwayMatch, IPathwayScoreRule } from '../models/PassportContent';

/**
 * Deciding which pathway a member gets.
 *
 * This replaces four hard-coded substring tests in passportScoringService. The old code
 * could only ever return one of `software_dev | data_analytics | ai_ready | it_bridge`,
 * so a pathway an admin created in the Pathways screen was unreachable — defined, listed,
 * editable, and assigned to nobody. Rules move the decision into data an admin owns.
 *
 * Two properties this must keep, because things downstream depend on them:
 *
 *   DETERMINISTIC. The same member and the same rules always produce the same pathway.
 *   The roadmap preview on the result page and the daily mission view are generated by
 *   separate calls, and they agree only because every input is pure. No clock, no
 *   randomness, and deliberately no AI at this point in the flow.
 *
 *   TOTAL. Every member lands somewhere. A member who matches no rule would otherwise
 *   have no pathway, and their dashboard, roadmap and card all read from it. That is what
 *   `fallback` is for, and why saving rules without exactly one fallback is refused.
 *
 * Note what is deliberately NOT decided here: the STAGE variant. Rules choose the track
 * (`software_dev`), and pathwayOf() then resolves `software_dev:placement` from the
 * member's own derived stage. Keeping those separate is what stops a low score from
 * moving someone onto a different subject — a weak Data Analytics member should get
 * easier Data Analytics, not Java.
 */

export interface MatchMember {
  careerGoal?: string | null;
  stage?: string | null;
  background?: string | null;
  careerScore?: number | null;
  categoryScores?: { key: string; score: number }[] | null;
}

export interface MatchTrace {
  key: string;
  label: string;
  matched: boolean;
  /** Why it lost — first failing condition, in the admin's words. */
  reason: string;
  priority: number;
  fallback: boolean;
}

export interface MatchResult {
  pathway: IPassportPathway | null;
  /** How it was reached, which the preview screen shows and the diff records. */
  via: 'rule' | 'fallback' | 'none';
  trace: MatchTrace[];
}

const norm = (s: any): string => String(s ?? '').trim().toLowerCase();

/** Score for one rule target — 'overall' is the Career Score, anything else a category. */
function scoreOf(member: MatchMember, category: string): number | null {
  if (category === 'overall') {
    return typeof member.careerScore === 'number' ? member.careerScore : null;
  }
  const hit = (member.categoryScores || []).find(c => c.key === category);
  return hit ? hit.score : null;
}

/**
 * A score rule against a category the member was never asked about.
 *
 * Treated as NOT MATCHING. The alternative — passing an absent score — would route
 * members on evidence that does not exist, and this is the exact failure the scorer
 * already guards against when it refuses to average un-asked categories into the
 * Career Score. Better to fall through to the fallback pathway than to place someone
 * on a track because of a number nobody measured.
 */
function scoreRuleHolds(member: MatchMember, r: IPathwayScoreRule): { ok: boolean; why: string } {
  const v = scoreOf(member, r.category);
  const name = r.category === 'overall' ? 'Career Score' : r.category;
  if (v === null) return { ok: false, why: `no ${name} on record` };
  if (typeof r.min === 'number' && v < r.min) return { ok: false, why: `${name} ${v} is below ${r.min}` };
  if (typeof r.max === 'number' && v > r.max) return { ok: false, why: `${name} ${v} is above ${r.max}` };
  return { ok: true, why: '' };
}

/** Does one pathway's rule accept this member? Returns the first failure for the trace. */
export function ruleHolds(m: IPathwayMatch, member: MatchMember): { ok: boolean; why: string } {
  if (!m.enabled) return { ok: false, why: 'rule is off' };

  // Goals are compared case- and space-insensitively: they are free text from the
  // signup form's own option list, and 'Data Analytics' must match 'data analytics'.
  const goals = (m.goals || []).filter(Boolean);
  if (goals.length) {
    const mine = norm(member.careerGoal);
    // An undecided member is never narrowed by a goal rule — the same carve-out the
    // question selector makes, for the same reason: choosing for them is the mistake.
    if (!mine || /not sure/.test(mine)) return { ok: false, why: 'no career goal chosen yet' };
    if (!goals.some(g => norm(g) === mine)) return { ok: false, why: `goal is ${member.careerGoal}` };
  }

  const stages = (m.stages || []).filter(Boolean);
  if (stages.length) {
    if (!member.stage) return { ok: false, why: 'no stage on record' };
    if (!stages.includes(member.stage)) return { ok: false, why: `stage is ${member.stage}` };
  }

  const bgs = (m.backgrounds || []).filter(b => b && b !== 'any');
  if (bgs.length) {
    if (!member.background) return { ok: false, why: 'no background on record' };
    if (!bgs.includes(member.background)) return { ok: false, why: `background is ${member.background}` };
  }

  for (const r of (m.scores || [])) {
    const res = scoreRuleHolds(member, r);
    if (!res.ok) return res;
  }

  return { ok: true, why: '' };
}

/**
 * The winner, plus every pathway's verdict so an admin can see why.
 *
 * The trace is not debug output — it is the feature. An admin writing routing rules
 * against six categories and four stages cannot hold the interactions in their head, and
 * a rule that quietly matches nobody looks identical to one that works until a member
 * complains weeks later.
 */
export function matchPathway(pathways: IPassportPathway[], member: MatchMember): MatchResult {
  const list = pathways || [];
  const trace: MatchTrace[] = [];

  // Only TRACK definitions compete. A stage variant (`software_dev:placement`, or a row
  // carrying `stage`) is a different rendering of a track already in the running, not a
  // separate destination — letting both compete would make priority meaningless.
  const tracks = list.filter(p => !p.stage && !String(p.key).includes(':'));

  const fb = tracks.find(p => p.match?.fallback && p.match?.enabled);

  const candidates: { p: IPassportPathway; m: IPathwayMatch }[] = [];
  for (const p of tracks) {
    const m = p.match;
    if (!m) {
      trace.push({ key: p.key, label: p.label, matched: false, reason: 'no rule set', priority: 0, fallback: false });
      continue;
    }
    // The fallback does not compete. It is where members land when nothing else claims
    // them, which is a different job from matching — and it usually carries no conditions,
    // so letting it race would mean it "matched" everybody and the preview could never
    // show how many people no rule actually accounted for.
    if (m.fallback) {
      trace.push({ key: p.key, label: p.label, matched: false, reason: 'catches whoever is left', priority: m.priority || 0, fallback: true });
      continue;
    }
    const { ok, why } = ruleHolds(m, member);
    trace.push({
      key: p.key, label: p.label, matched: ok,
      reason: ok ? 'matches' : why,
      priority: m.priority || 0, fallback: false,
    });
    if (ok) candidates.push({ p, m });
  }

  if (candidates.length) {
    // Stable: sort only on priority, so equal priorities keep author order.
    candidates.sort((a, b) => (b.m.priority || 0) - (a.m.priority || 0));
    return { pathway: candidates[0].p, via: 'rule', trace };
  }

  // Reached regardless of the fallback's own conditions — a fallback that could reject
  // somebody would not be total, and totality is the whole reason it exists.
  if (fb) return { pathway: fb, via: 'fallback', trace };

  // No rule and no fallback. Returning the first track keeps a member's dashboard
  // working; validateRules() is what stops this state being saved in the first place.
  return { pathway: tracks[0] || list[0] || null, via: 'none', trace };
}

/**
 * Problems worth blocking a save for.
 *
 * Only two are errors, and both make members undeliverable. Everything else is a
 * warning: an admin part-way through authoring should not be locked out of saving.
 */
export function validateRules(pathways: IPassportPathway[]): { errors: string[]; warnings: string[] } {
  const errors: string[] = [];
  const warnings: string[] = [];
  const tracks = (pathways || []).filter(p => !p.stage && !String(p.key).includes(':'));

  // Describes what WOULD be wrong if these rules were the ones deciding. Whether that
  // matters yet is the caller's question: while rules are off these are things to fix
  // before going live, and only switching them on makes them blocking.
  const usingRules = tracks.some(p => p.match?.enabled);
  if (!usingRules) {
    warnings.push('No pathway has a rule yet. Switch one on to start sorting members yourself.');
    return { errors, warnings };
  }

  const fallbacks = tracks.filter(p => p.match?.fallback && p.match?.enabled);
  if (fallbacks.length === 0) {
    errors.push('No fallback pathway. Members who match no rule would have nowhere to go — mark one pathway as the fallback.');
  } else if (fallbacks.length > 1) {
    errors.push(`${fallbacks.length} pathways are marked fallback (${fallbacks.map(p => p.label).join(', ')}). Exactly one can be.`);
  }

  for (const p of tracks) {
    const m = p.match;
    if (!m || !m.enabled) continue;
    for (const r of (m.scores || [])) {
      if (typeof r.min === 'number' && typeof r.max === 'number' && r.min > r.max) {
        errors.push(`${p.label}: ${r.category} asks for above ${r.min} and below ${r.max}, which nothing satisfies.`);
      }
    }
    const hasCondition = (m.goals?.length || m.stages?.length || m.backgrounds?.length || m.scores?.length);
    if (!hasCondition && !m.fallback) {
      warnings.push(`${p.label} has no conditions, so it matches every member. Give it conditions or make it the fallback.`);
    }
  }

  return { errors, warnings };
}
