/**
 * Generate, store and replan a student's adaptive plan.
 *
 * WHAT THIS OWNS. Gathering the inputs — Skill DNA, the skill graph, the curriculum, the
 * student's direction and availability — calling the pure planner, resolving content, and
 * writing the result down. The decisions themselves belong to curriculumPersonalizationService,
 * which has no database access precisely so its rules can be read and tested without one.
 *
 * A PLAN IS NEVER GENERATED BY ACCIDENT. Opening a page must not create one. Only an explicit
 * generate, or a replan triggered by named evidence, may write — because a plan that silently
 * rebuilds itself on a page load is one a student can never learn to trust, and a support
 * question about "why did my plan change" would have no answer.
 *
 * REPLANNING NEVER TOUCHES COMPLETED WORK. A new version supersedes the old one; progress lives
 * on the enrollment and is not consulted, let alone rewritten. History is history.
 */

import mongoose from 'mongoose';
import StudentCurriculumAssignment, { IStudentCurriculumAssignment } from '../models/StudentCurriculumAssignment';
import LearningCurriculum from '../models/LearningCurriculum';
import StudentSkillProfile from '../models/StudentSkillProfile';
import CareerSkill from '../models/CareerSkill';
import CurriculumEnrollment from '../models/CurriculumEnrollment';
import User from '../models/User';
import {
  personalizeCurriculum, PlannableTopic, SkillBelief, TopicDecision,
} from './curriculumPersonalizationService';
import { resolveContentForTopic } from './adaptiveContentResolver';
import { resolveDirection } from './careerDirectionService';
import { ADAPTIVE_CURRICULUM_VERSION, ReplanTrigger, isSignificantChange, stateForScore } from '../data/adaptiveCurriculumPolicy';

/** Minutes assumed for a topic that nobody has estimated. One focused session. */
const DEFAULT_TOPIC_MINUTES = 90;

export interface GenerateOptions {
  tenantId: string;
  studentId: string;
  curriculumId: string;
  /** Rebuild an existing plan. Without it an existing ACTIVE plan is returned untouched. */
  replan?: boolean;
  trigger?: ReplanTrigger;
  generatedFromAssessmentId?: string;
}

export interface GenerateResult {
  assignment: IStudentCurriculumAssignment | null;
  created: boolean;
  refused?: string;
  /** Skills the content bank cannot teach yet. Reported, never hidden. */
  contentGaps: string[];
}

/* ------------------------------------------------------------------ *
 * Input gathering
 * ------------------------------------------------------------------ */

/**
 * Flatten a curriculum into plannable topics.
 *
 * Topics without skillKeys are kept, not dropped. A curriculum is mapped to skills by hand over
 * time, and a half-mapped one must still produce a usable plan — an unmapped topic simply has no
 * measurement to personalize against and is taught at its default depth. Dropping it would make
 * enabling the feature look like content had gone missing.
 */
function toPlannableTopics(curriculum: any): PlannableTopic[] {
  const topics = (curriculum.topics || []) as any[];

  /**
   * Module names and ordering come from the curriculum's own module headers.
   *
   * A topic stores only its moduleCode, so reading `t.moduleName` — which is what this did —
   * yielded undefined for every topic, and every module in every student's plan was persisted
   * with no name at all. The screen had a module code or a blank where "Programming Fundamentals"
   * belonged, for as long as this has been running.
   *
   * displayOrder comes from the header too. The topic's own `order` sorted correctly by accident,
   * because topics happen to be numbered straight through the curriculum — but reordering topics
   * inside one module would have silently reordered the modules. The header is the thing that
   * actually knows where a module sits.
   */
  const headers = new Map<string, { moduleName?: string; displayOrder?: number }>(
    ((curriculum.modules || []) as any[]).map(m => [String(m.moduleCode), m]),
  );

  return topics.map((t, i) => {
    const days = Math.max(1, (t.endDay || t.startDay || 1) - (t.startDay || 1) + 1);
    const header = headers.get(String(t.moduleCode));
    return {
      topicId: t._id ? String(t._id) : undefined,
      topicCode: t.topicCode,
      title: t.title,
      moduleCode: t.moduleCode || 'UNGROUPED',
      // The header's name, falling back to anything the topic carries, then to the code — a
      // module always renders as something a person can read.
      moduleName: header?.moduleName || t.moduleName || t.moduleCode,
      /**
       * Deliberately the TOPIC's order, not the module header's displayOrder.
       *
       * The personalizer sorts on moduleOrder and falls through to state when it ties. Every topic
       * in a module sharing one displayOrder would therefore reorder topics INSIDE a module by how
       * urgent they are — conditions after loops, which is not a syllabus. Topics are numbered
       * straight through the curriculum, so the topic's own order already sorts the modules
       * correctly AND keeps the authored sequence within each one.
       */
      moduleOrder: typeof t.order === 'number' ? t.order : i,
      order: typeof t.order === 'number' ? t.order : i,
      skillKeys: (t.skillKeys || []).map((k: string) => String(k).toUpperCase()),
      prerequisiteSkillKeys: (t.prerequisiteSkillKeys || []).map((k: string) => String(k).toUpperCase()),
      applicableDirections: t.applicableDirections || [],
      mandatory: t.mandatory !== false,
      defaultDepth: t.defaultDepth,
      // Day ranges are the only estimate a curriculum carries today. Treated as a rough
      // proxy rather than a truth: one authored day is one session's worth of work.
      estimatedMinutes: days * DEFAULT_TOPIC_MINUTES,
    };
  });
}

/** Skill DNA for the skills this curriculum actually teaches. Absence stays absence. */
async function loadBeliefs(tenantId: string, studentId: string, skillKeys: string[]): Promise<Map<string, SkillBelief>> {
  const out = new Map<string, SkillBelief>();
  if (!skillKeys.length) return out;
  const rows = await StudentSkillProfile.find({
    tenantId, studentId: new mongoose.Types.ObjectId(studentId), skillKey: { $in: skillKeys },
  }).select('skillKey score confidence').lean() as any[];
  for (const r of rows) {
    out.set(String(r.skillKey).toUpperCase(), {
      skillKey: r.skillKey, score: r.score ?? null, confidence: r.confidence ?? null,
    });
  }
  return out;
}

/**
 * Prerequisites and names from the canonical skill graph.
 *
 * GROUP nodes are traversed rather than required: a group is a shelf, not a capability, and
 * blocking a student on one would mean waiting for something nobody can demonstrate.
 */
async function loadGraph(skillKeys: string[]): Promise<{
  prerequisites: Map<string, string[]>;
  names: Map<string, string>;
}> {
  const prerequisites = new Map<string, string[]>();
  const names = new Map<string, string>();
  if (!skillKeys.length) return { prerequisites, names };

  const seen = new Set<string>(skillKeys);
  let frontier = [...skillKeys];

  // Two rounds: direct prerequisites, and theirs. Deeper than that and a first-year is being
  // blocked on something four steps removed from what they are trying to learn.
  for (let round = 0; round < 2 && frontier.length; round++) {
    const rows = await CareerSkill.find({ key: { $in: frontier } })
      .select('key name nodeType prerequisiteKeys').lean() as any[];
    const next: string[] = [];
    for (const r of rows) {
      const key = String(r.key).toUpperCase();
      names.set(key, r.name || key);
      const prereqs = (r.prerequisiteKeys || []).map((k: string) => String(k).toUpperCase());
      prerequisites.set(key, prereqs);
      for (const p of prereqs) if (!seen.has(p)) { seen.add(p); next.push(p); }
    }
    frontier = next;
  }

  // Names for prerequisites pulled in on the last round, so a lock can say what is blocking it.
  const missingNames = [...seen].filter(k => !names.has(k));
  if (missingNames.length) {
    const rows = await CareerSkill.find({ key: { $in: missingNames } }).select('key name').lean() as any[];
    for (const r of rows) names.set(String(r.key).toUpperCase(), r.name || r.key);
  }

  return { prerequisites, names };
}

/* ------------------------------------------------------------------ *
 * Generation
 * ------------------------------------------------------------------ */

export async function generateAssignment(opts: GenerateOptions): Promise<GenerateResult> {
  const { tenantId, studentId, curriculumId } = opts;

  const existing = await StudentCurriculumAssignment.findOne({
    tenantId, studentId: new mongoose.Types.ObjectId(studentId),
    curriculumId: new mongoose.Types.ObjectId(curriculumId), status: 'ACTIVE',
  });

  // Idempotent against a double-click. The unique partial index is the real guarantee; this
  // saves the work.
  if (existing && !opts.replan) {
    return { assignment: existing, created: false, contentGaps: [] };
  }

  const curriculum = await LearningCurriculum.findOne({ _id: curriculumId, tenantId }).lean() as any;
  if (!curriculum) return { assignment: null, created: false, refused: 'CURRICULUM_NOT_FOUND', contentGaps: [] };

  const user = await User.findOne({ _id: studentId, tenantId }).select('passport').lean() as any;
  const passport = user?.passport || {};

  const availability = {
    hoursPerDay: Number(passport.hoursPerDay) || (Number(passport.minutesPerDay) / 60) || 1,
    daysPerWeek: Number(passport.daysPerWeek) || 5,
  };

  const resolved = resolveDirection({
    selectedDirection: passport.selectedDirection,
    primaryRole: passport.primaryRole,
    preferredTechnologies: passport.preferredTechnologies,
  });

  const topics = toPlannableTopics(curriculum);
  const allSkillKeys = Array.from(new Set(topics.flatMap(t => t.skillKeys)));

  const [beliefs, graph] = await Promise.all([
    loadBeliefs(tenantId, studentId, allSkillKeys),
    loadGraph(allSkillKeys),
  ]);

  const plan = personalizeCurriculum({
    topics,
    beliefs,
    graphPrerequisites: graph.prerequisites,
    priorities: new Map(),
    skillNames: graph.names,
    selectedDirection: resolved.direction?.key || null,
    directionStatus: resolved.status,
    explorationDirections: resolved.explorationDirections,
    availability,
  });

  // Content is resolved only for work the student will actually do. Fetching material for a
  // topic marked irrelevant or locked would be wasted queries on every generation.
  const contentGaps = new Set<string>();
  const decisionsWithContent = await Promise.all(plan.decisions.map(async d => {
    if (d.state === 'NOT_RELEVANT' || d.locked || !d.skillKeys.length) {
      return { decision: d, contentIds: [] as string[] };
    }
    const r = await resolveContentForTopic({
      tenantId, skillKeys: d.skillKeys, depth: d.contentDepth,
      difficultyMin: d.difficultyMin, difficultyMax: d.difficultyMax,
      practiceCount: d.practiceCount, direction: resolved.direction?.key || null,
      // Lets material written for this exact topic beat material that merely shares its
      // skills — the difference between six career topics and six copies of one video.
      topicCode: d.topicCode || null,
    });
    for (const k of r.coverage.unmappedSkills) contentGaps.add(k);
    return { decision: d, contentIds: r.contentIds };
  }));

  const moduleAssignments = groupIntoModules(decisionsWithContent);

  const nextVersion = existing ? (existing.version || 1) + 1 : 1;

  /**
   * The new plan is built completely before the old one is retired.
   *
   * A failure halfway through must leave the student with the plan they had, not with none.
   */
  if (existing) {
    existing.status = 'SUPERSEDED';
    existing.supersededAt = new Date();
    await existing.save();
  }

  let created: IStudentCurriculumAssignment;
  try {
    created = await StudentCurriculumAssignment.create({
      tenantId,
      studentId: new mongoose.Types.ObjectId(studentId),
      curriculumId: new mongoose.Types.ObjectId(curriculumId),
      stage: passport.stage || 'foundation',
      academicYear: passport.yearOfStudy,
      selectedDirection: resolved.direction?.key,
      directionStatus: resolved.status,
      explorationDirections: resolved.explorationDirections,
      availability: {
        hoursPerDay: availability.hoursPerDay,
        daysPerWeek: availability.daysPerWeek,
        weeklyPlannableMinutes: plan.pace.weeklyPlannableMinutes,
        activeTopicsPerWeek: plan.pace.activeTopicsPerWeek,
      },
      moduleAssignments,
      totalAssignedMinutes: plan.totalAssignedMinutes,
      estimatedWeeks: plan.estimatedWeeks,
      version: nextVersion,
      status: 'ACTIVE',
      generatedFromAssessmentId: opts.generatedFromAssessmentId
        ? new mongoose.Types.ObjectId(opts.generatedFromAssessmentId) : undefined,
      generatedReason: opts.trigger || (existing ? 'MENTOR_OVERRIDE' : 'DIAGNOSTIC_COMPLETED'),
      policyVersion: ADAPTIVE_CURRICULUM_VERSION,
      generatedAt: new Date(),
      lastReplannedAt: existing ? new Date() : undefined,
    });
  } catch (e: any) {
    // Restore the previous plan rather than leaving the student with nothing.
    if (existing) {
      existing.status = 'ACTIVE';
      existing.supersededAt = undefined;
      await existing.save().catch(() => { /* the throw below is the real signal */ });
    }
    throw e;
  }

  if (existing) {
    existing.supersededBy = created._id as any;
    await existing.save().catch(() => { /* back-link is a convenience, not a correctness need */ });
  }

  await CurriculumEnrollment.updateOne(
    { tenantId, curriculumId: new mongoose.Types.ObjectId(curriculumId), studentId: new mongoose.Types.ObjectId(studentId) },
    { $set: { assignmentId: created._id, currentPlanVersion: nextVersion, lastReplannedAt: new Date(), stage: passport.stage } },
  ).catch(() => { /* an enrollment may not exist yet; the plan is still valid */ });

  console.log(`[adaptive] plan v${nextVersion} for student ${studentId}: `
    + `${plan.decisions.length} topics, ${JSON.stringify(plan.summary)}, `
    + `${plan.estimatedWeeks}w, ${contentGaps.size} unmapped skills`);

  return { assignment: created, created: true, contentGaps: [...contentGaps] };
}

function groupIntoModules(rows: { decision: TopicDecision; contentIds: string[] }[]) {
  const modules = new Map<string, any>();
  for (const { decision: d, contentIds } of rows) {
    if (!modules.has(d.moduleCode)) {
      modules.set(d.moduleCode, {
        moduleCode: d.moduleCode,
        moduleName: d.moduleName,
        displayOrder: d.moduleOrder,
        topicAssignments: [],
      });
    }
    modules.get(d.moduleCode).topicAssignments.push({
      topicId: d.topicId,
      topicCode: d.topicCode,
      title: d.title,
      skillKeys: d.skillKeys,
      state: d.state,
      priority: d.priority,
      contentDepth: d.contentDepth,
      difficultyMin: d.difficultyMin,
      difficultyMax: d.difficultyMax,
      practiceCount: d.practiceCount,
      assignedContentIds: contentIds.map(id => new mongoose.Types.ObjectId(id)),
      reason: d.reason,
      reasonText: d.reasonText,
      mandatory: d.mandatory,
      locked: d.locked,
      lockedBy: d.lockedBy,
      scoreAtAssignment: d.scoreAtAssignment,
    });
  }
  return [...modules.values()].sort((a, b) => a.displayOrder - b.displayOrder);
}

/* ------------------------------------------------------------------ *
 * Reading
 * ------------------------------------------------------------------ */

export async function getActiveAssignment(tenantId: string, studentId: string, curriculumId: string) {
  return StudentCurriculumAssignment.findOne({
    tenantId,
    studentId: new mongoose.Types.ObjectId(studentId),
    curriculumId: new mongoose.Types.ObjectId(curriculumId),
    status: 'ACTIVE',
  }).lean();
}

/**
 * Whether a plan is now out of step with what we know.
 *
 * Reported, never acted on automatically — the decision to replan is the student's or an
 * admin's. A system that rebuilds a plan the moment it can justify doing so produces a plan
 * that never stands still long enough to be followed.
 */
export async function assessReplanNeed(tenantId: string, studentId: string, curriculumId: string): Promise<{
  needed: boolean;
  changedSkills: string[];
  reason: string | null;
}> {
  const assignment = await getActiveAssignment(tenantId, studentId, curriculumId) as any;
  if (!assignment) return { needed: false, changedSkills: [], reason: null };

  const assigned = new Map<string, { state: string; score: number | null }>();
  for (const m of assignment.moduleAssignments || []) {
    for (const t of m.topicAssignments || []) {
      for (const k of t.skillKeys || []) {
        assigned.set(String(k).toUpperCase(), { state: t.state, score: t.scoreAtAssignment ?? null });
      }
    }
  }
  if (!assigned.size) return { needed: false, changedSkills: [], reason: null };

  const now = await loadBeliefs(tenantId, studentId, [...assigned.keys()]);

  const changed: string[] = [];
  for (const [key, before] of assigned) {
    const belief = now.get(key);
    const afterState = stateForScore({
      score: belief?.score ?? null, confidence: belief?.confidence ?? null,
    });
    if (isSignificantChange({
      beforeScore: before.score,
      afterScore: belief?.score ?? null,
      beforeState: before.state as any,
      afterState,
    })) changed.push(key);
  }

  return {
    needed: changed.length > 0,
    changedSkills: changed,
    reason: changed.length ? 'SIGNIFICANT_MASTERY_CHANGE' : null,
  };
}

/* ------------------------------------------------------------------ *
 * Getting a new member onto a plan at all
 * ------------------------------------------------------------------ */

/**
 * Enrol a student in the curriculum for their stage, and build them a plan.
 *
 * THE GAP THIS CLOSES. Replanning only ever looked at curricula a student was already enrolled
 * in, so a brand-new member finished their diagnostic, had Skill DNA written, and got nothing:
 * no enrollment, therefore no curriculum, therefore no plan. Every plan that existed had been
 * created by hand from a script, which is fine for one test account and useless for a product.
 *
 * WHICH CURRICULUM. The one that claims their stage via adaptiveStage. Nothing is auto-enrolled
 * until a curriculum is deliberately marked, so a tenant that has not set one up keeps exactly
 * its current behaviour rather than having students dropped into whatever was found first.
 *
 * NEVER FATAL, AND NEVER DUPLICATES. Called from an event handler after a submission is already
 * safe; a unique index on (curriculum, student) is what actually prevents a second enrollment,
 * and the pre-check only saves the work.
 */
export async function ensureAdaptivePlan(input: {
  tenantId: string;
  studentId: string;
  trigger?: ReplanTrigger;
  assessmentId?: string;
}): Promise<{ enrolled: boolean; planned: boolean; curriculumId?: string; reason?: string }> {
  const { tenantId, studentId } = input;

  const user = await User.findOne({ _id: studentId, tenantId }).select('passport firstName lastName email').lean() as any;
  if (!user) return { enrolled: false, planned: false, reason: 'no such student' };

  const stage = String(user.passport?.stage || '').trim();
  if (!stage) return { enrolled: false, planned: false, reason: 'no academic stage resolved' };

  const curriculum = await LearningCurriculum.findOne({
    tenantId, adaptiveStage: stage, isPublished: true, personalizedFor: null,
  }).select('_id title').lean() as any;

  if (!curriculum) {
    // Not an error: this tenant simply has no curriculum for that stage yet.
    return { enrolled: false, planned: false, reason: `no curriculum claims stage "${stage}"` };
  }

  const curriculumId = String(curriculum._id);

  let enrolled = false;
  const existing = await CurriculumEnrollment.findOne({
    curriculumId: new mongoose.Types.ObjectId(curriculumId),
    studentId: new mongoose.Types.ObjectId(studentId),
  }).lean();

  if (!existing) {
    try {
      await CurriculumEnrollment.create({
        tenantId,
        curriculumId: new mongoose.Types.ObjectId(curriculumId),
        curriculumTitle: curriculum.title,
        studentId: new mongoose.Types.ObjectId(studentId),
        studentName: [user.firstName, user.lastName].filter(Boolean).join(' ') || 'Student',
        studentEmail: user.email || '',
        startDate: new Date(),
        status: 'active',
        enrolledBy: 'adaptive-auto',
        assessmentOriginated: true,
        stage,
      });
      enrolled = true;
    } catch (e: any) {
      // 11000 means another request won the race, which is the outcome we wanted anyway.
      if (e?.code !== 11000) throw e;
    }
  }

  const result = await generateAssignment({
    tenantId, studentId, curriculumId,
    replan: true,
    trigger: input.trigger || 'DIAGNOSTIC_COMPLETED',
    generatedFromAssessmentId: input.assessmentId,
  });

  return { enrolled, planned: !!result.assignment, curriculumId };
}
