#!/bin/bash
# ============================================================================
# Fresh VPS provisioning — run as root on a NEW, EMPTY Ubuntu 22.04/24.04 box.
#
#   ssh root@<NEW_IP>
#   git clone <repo> /root/lms && cd /root/lms
#   bash scripts/provision-vps.sh
#
# Brings the host from bare OS to "ready to receive the app image": Docker,
# nginx, TLS tooling, firewall, SSH hardening, and freshly generated secrets.
# It does NOT copy anything from the old server — that is the entire point of
# rebuilding. Data comes across later as a mongodump, which is inert BSON.
#
# Idempotent: safe to re-run. It will not overwrite an existing /root/lms/.env.
# ============================================================================
set -euo pipefail

RED=$'\033[0;31m'; GRN=$'\033[0;32m'; YEL=$'\033[1;33m'; NC=$'\033[0m'
step() { echo ""; echo "${YEL}==> $*${NC}"; }
ok()   { echo "${GRN}   ✅ $*${NC}"; }
die()  { echo "${RED}❌ $*${NC}" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "Run as root."
APP_DIR="/root/lms"
[ -f "$APP_DIR/docker-compose.yml" ] || die "Run this from a clone at $APP_DIR (docker-compose.yml not found)."

# ── Preflight: do not lock yourself out ─────────────────────────────────────
# SSH hardening below disables password login. If no key is installed, that
# turns the box into a brick reachable only through the provider's console.
step "[0/9] Preflight"
if [ ! -s /root/.ssh/authorized_keys ]; then
  die "/root/.ssh/authorized_keys is empty or missing.
   Install your key FIRST, from your laptop:
     ssh-copy-id -i ~/.ssh/github-ci.pub root@<NEW_IP>
   Then confirm 'ssh -i ~/.ssh/github-ci root@<NEW_IP>' works, and rerun this."
fi
ok "$(wc -l < /root/.ssh/authorized_keys) SSH key(s) present"

if docker ps >/dev/null 2>&1 && [ -n "$(docker ps -aq 2>/dev/null)" ]; then
  echo "${YEL}   ⚠️  This box already has Docker containers. Expected a FRESH server.${NC}"
  read -r -p "   Continue anyway? [y/N] " a; [ "$a" = "y" ] || exit 1
fi

# ── Base system ─────────────────────────────────────────────────────────────
step "[1/9] Base packages + automatic security updates"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get upgrade -y -qq
apt-get install -y -qq \
  ca-certificates curl gnupg git ufw fail2ban debsums \
  unattended-upgrades apt-listchanges jq net-tools
# Unpatched CVEs are how a hardened box becomes an unhardened one over months.
cat > /etc/apt/apt.conf.d/20auto-upgrades <<'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
EOF
systemctl enable --now unattended-upgrades >/dev/null 2>&1 || true
ok "base packages + unattended-upgrades"

# ── Docker ──────────────────────────────────────────────────────────────────
step "[2/9] Docker"
if ! command -v docker >/dev/null 2>&1; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io \
                          docker-buildx-plugin docker-compose-plugin
fi
# deploy-image.sh and the runbook both call `docker-compose` (hyphenated).
if ! command -v docker-compose >/dev/null 2>&1; then
  printf '#!/bin/sh\nexec docker compose "$@"\n' > /usr/local/bin/docker-compose
  chmod +x /usr/local/bin/docker-compose
fi
systemctl enable --now docker
ok "docker $(docker --version | awk '{print $3}' | tr -d ,) + compose shim"

# ── Secrets ─────────────────────────────────────────────────────────────────
step "[3/9] Generating secrets"
gen() { openssl rand -base64 36 | tr -d '/+=' | cut -c1-40; }
if [ -f "$APP_DIR/.env" ]; then
  echo "   ${YEL}$APP_DIR/.env already exists — leaving it untouched.${NC}"
else
  cat > "$APP_DIR/.env" <<EOF
# Generated by provision-vps.sh on $(date -u +%FT%TZ)
# Compose-level secrets. NOT server/.env — see .env.example.
MONGO_ROOT_USERNAME=lmsadmin
MONGO_ROOT_PASSWORD=$(gen)
REDIS_PASSWORD=$(gen)
JWT_SECRET=$(gen)
ENCRYPTION_KEY=$(gen)
EOF
  chmod 600 "$APP_DIR/.env"
  ok "wrote $APP_DIR/.env (0600) with 4 fresh secrets"
fi

# server/.env holds app config. ENCRYPTION_KEY/JWT_SECRET/MONGODB_URI are
# supplied by compose and intentionally NOT duplicated here.
if [ ! -f "$APP_DIR/server/.env" ]; then
  cat > "$APP_DIR/server/.env" <<'EOF'
NODE_ENV=production
PORT=5000
LOG_LEVEL=info
FRONTEND_URL=https://platform.codebegun.com
CLIENT_URL=https://platform.codebegun.com
JWT_EXPIRES_IN=7d
# API keys are entered in Platform Settings (encrypted into MongoDB), not here.
EOF
  chmod 600 "$APP_DIR/server/.env"
  ok "wrote $APP_DIR/server/.env"
fi

# ── SSH hardening ───────────────────────────────────────────────────────────
step "[4/9] SSH hardening (key-only)"
cat > /etc/ssh/sshd_config.d/00-hardening.conf <<'EOF'
# A brute-forced root password was the original entry point on the old server.
PasswordAuthentication no
PermitRootLogin prohibit-password
KbdInteractiveAuthentication no
ChallengeResponseAuthentication no
PubkeyAuthentication yes
MaxAuthTries 3
X11Forwarding no
EOF
# Distro defaults can re-enable these later in the file and silently win.
for f in /etc/ssh/sshd_config /etc/ssh/sshd_config.d/50-cloud-init.conf; do
  [ -f "$f" ] && sed -i -E 's/^[[:space:]]*(PasswordAuthentication|PermitRootLogin)[[:space:]]+yes/# &/I' "$f"
done
sshd -t || die "sshd config invalid — NOT reloading. Fix before continuing."
EFF_PW=$(sshd -T 2>/dev/null | awk '/^passwordauthentication/{print $2}')
[ "$EFF_PW" = "no" ] || die "sshd still reports passwordauthentication=$EFF_PW. Investigate before reloading."
systemctl reload ssh 2>/dev/null || systemctl reload sshd
ok "password auth disabled, verified via sshd -T"

# ── Firewall ────────────────────────────────────────────────────────────────
step "[5/9] Firewall"
bash "$APP_DIR/scripts/harden-firewall.sh"

# ── nginx + TLS ─────────────────────────────────────────────────────────────
step "[6/9] nginx + certbot"
apt-get install -y -qq nginx certbot python3-certbot-nginx
mkdir -p /etc/nginx/sites-available
cp "$APP_DIR/nginx/nginx.conf" /etc/nginx/nginx.conf
# Blue first — deploy-image.sh flips to green on the next deploy.
echo "server 127.0.0.1:5001;" > /etc/nginx/active-slot.conf
echo "blue" > "$APP_DIR/.active-slot"
ok "nginx installed; active slot pinned to blue (5001)"
echo "   ${YEL}TLS is issued in runbook step 6, AFTER DNS points here.${NC}"

# ── Data services ───────────────────────────────────────────────────────────
step "[7/9] Starting MongoDB + Redis"
cd "$APP_DIR"
docker-compose up -d mongodb redis
sleep 6
set -a; . "$APP_DIR/.env"; set +a
docker exec lms-redis redis-cli -a "$REDIS_PASSWORD" --no-auth-warning ping | grep -q PONG \
  && ok "redis authenticated" || die "redis not responding to authenticated PING"
ok "mongodb + redis up on 127.0.0.1 only"

# ── Verify exposure ─────────────────────────────────────────────────────────
step "[8/9] Verifying nothing is publicly bound"
BAD=0
for p in 6379 27017 5001 5002; do
  if ss -tln 2>/dev/null | grep -qE "(0\.0\.0\.0|\[::\]):$p"; then
    echo "${RED}   ❌ port $p is publicly bound${NC}"; BAD=1
  else ok "port $p is localhost-only"; fi
done
[ "$BAD" -eq 0 ] || die "Ports are publicly bound. Do NOT proceed."

step "[9/9] Done"
cat <<EOF

${GRN}╔════════════════════════════════════════════════════════════╗
║  Host provisioned. Nothing is exposed except 22/80/443.    ║
╚════════════════════════════════════════════════════════════╝${NC}

Secrets are in $APP_DIR/.env (mode 0600). Back them up to your password
manager now — losing ENCRYPTION_KEY means re-entering every API key.

Next, from docs/runbooks/fresh-vps-deploy.md:
  4. Restore data      — copy the mongodump across and run scripts/restore.sh
  5. Ship the image    — docker save from your laptop, docker load here
  6. DNS + TLS         — point the A record here, then certbot
  7. Verify            — health, login, Piston, then audit admin users

${YEL}Do NOT copy the old server/.env across. Every key it holds is compromised.${NC}
EOF
