/**
 * A first plan is the student's press, never a side effect.
 *
 * Submitting a personalised assessment replans the roadmap, and for a student who already has
 * one that is exactly right: their evidence moved, so their plan should move with it. For a
 * student who has never built one it was wrong — they answered sixteen questions and were
 * handed ninety days of commitments generated by a side effect of a different action, with no
 * screen ever asking them. Building a plan is a decision, and this pins where that decision
 * lives.
 *
 * Tested through the guard rather than through Mongo: `replanOnly` is one branch over whether
 * an active roadmap exists, and exercising it through a database would test the database.
 */

/** Exactly the branch generateRoadmap takes before it reads or writes anything. */
const refusesToCreate = (existing: unknown, opts: { replan?: boolean; replanOnly?: boolean }): boolean =>
  !existing && !!opts.replanOnly;

describe('generateRoadmap with replanOnly', () => {
  it('refuses to bring a first plan into being', () => {
    expect(refusesToCreate(null, { replan: true, replanOnly: true })).toBe(true);
  });

  it('still rebuilds a plan that already exists', () => {
    // The whole point of the call the assessment makes: new evidence, same student, new plan.
    expect(refusesToCreate({ status: 'ACTIVE' }, { replan: true, replanOnly: true })).toBe(false);
  });

  /**
   * The student pressing "Build my 90-day plan" passes no `replanOnly`, so nothing about the
   * deliberate path changed. If this ever starts refusing, the button is dead.
   */
  it('leaves the student’s own press alone', () => {
    expect(refusesToCreate(null, {})).toBe(false);
    expect(refusesToCreate(null, { replan: true })).toBe(false);
  });
});

/**
 * How the completion screen describes each outcome. Every branch has to say a true thing:
 * the version before this one promised "we are analysing your responses to prepare your
 * roadmap" and then, for anyone it could not plan for, did nothing forever.
 */
describe('what the assessment tells a student about their plan', () => {
  type Status = 'READY' | 'MEMBERSHIP_REQUIRED' | 'NOT_ENOUGH_EVIDENCE'
    | 'UNAVAILABLE' | 'NOT_GENERATED' | 'NOT_ATTEMPTED';

  /** Exactly the mapping the controller applies to a refused replan. */
  const statusOf = (o: { available?: boolean; reason?: string; refused?: string }): Status => {
    if (o.available) return 'READY';
    if (o.refused === 'NO_PLAN_TO_REPLAN') return 'NOT_GENERATED';
    const reason = String(o.reason || o.refused || '');
    return /MEMBERSHIP|ENTITLE/i.test(reason) ? 'MEMBERSHIP_REQUIRED'
      : /EVIDENCE|COVERAGE|ROLE_NOT_SELECTED|BLUEPRINT/i.test(reason) ? 'NOT_ENOUGH_EVIDENCE'
        : 'UNAVAILABLE';
  };

  it('says the plan was rebuilt when it was', () => {
    expect(statusOf({ available: true })).toBe('READY');
  });

  /**
   * The case this change creates, and the one that must not be mistaken for either a paywall
   * or a fault. "Never built one" is an invitation; the screen offers the button.
   */
  it('says nothing is wrong when they simply have not built one', () => {
    expect(statusOf({ available: false, reason: 'NO_READINESS_DATA', refused: 'NO_PLAN_TO_REPLAN' }))
      .toBe('NOT_GENERATED');
  });

  it('still tells a free member it is a paywall, not a fault', () => {
    expect(statusOf({ available: false, reason: 'MEMBERSHIP_REQUIRED' })).toBe('MEMBERSHIP_REQUIRED');
  });

  it('separates "we cannot yet" from "something broke"', () => {
    expect(statusOf({ available: false, reason: 'ROLE_NOT_SELECTED' })).toBe('NOT_ENOUGH_EVIDENCE');
    expect(statusOf({ available: false, reason: 'ROLE_BLUEPRINT_NOT_READY' })).toBe('NOT_ENOUGH_EVIDENCE');
    expect(statusOf({ available: false, reason: 'SOMETHING_ELSE' })).toBe('UNAVAILABLE');
  });

  /**
   * NO_PLAN_TO_REPLAN wins over the reason string it travels with. The refusal carries
   * NO_READINESS_DATA as its reason — the same string a student with no role would get — and
   * reading the reason first would tell somebody their evidence was thin when it is fine.
   */
  it('does not mistake a missing plan for missing evidence', () => {
    expect(statusOf({ available: false, reason: 'NO_READINESS_DATA', refused: 'NO_PLAN_TO_REPLAN' }))
      .not.toBe('NOT_ENOUGH_EVIDENCE');
  });
});
